// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub const POLLERR: i32 = 8i32;
pub const POLLHUP: i32 = 16i32;
pub const POLLIN: i32 = 1i32;
pub const POLLMSG: i32 = 1024i32;
pub const POLLNVAL: i32 = 32i32;
pub const POLLOUT: i32 = 4i32;
pub const POLLPRI: i32 = 2i32;
pub const POLLRDBAND: i32 = 128i32;
pub const POLLRDHUP: i32 = 8192i32;
pub const POLLRDNORM: i32 = 64i32;
pub const POLLREMOVE: i32 = 4096i32;
pub const POLLWRBAND: i32 = 512i32;
pub const POLLWRNORM: i32 = 256i32;
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct pollfd {
    pub fd: i32,
    pub events: i16,
    pub revents: i16,
}
