// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __add_wait_queue(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __add_wait_queue_entry_tail(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __add_wait_queue_entry_tail_exclusive(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __add_wait_queue_exclusive(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __finish_swait(q : *mut swait_queue_head, wait : *mut swait_queue));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __init_swait_queue_head(q : *mut swait_queue_head, name : *const i8, key : *mut super::fs:: lock_class_key));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __init_waitqueue_head(wq_head : *mut wait_queue_head, name : *const i8, param2 : *mut super::fs:: lock_class_key));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __remove_wait_queue(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __var_waitqueue(p : *mut core::ffi::c_void) -> *mut wait_queue_head_t);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __wait_on_bit(wq_head : *mut wait_queue_head, wbq_entry : *mut wait_bit_queue_entry, action : *mut wait_bit_action_f, mode : u32) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __wait_on_bit_lock(wq_head : *mut wait_queue_head, wbq_entry : *mut wait_bit_queue_entry, action : *mut wait_bit_action_f, mode : u32) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __wake_up(wq_head : *mut wait_queue_head, mode : u32, nr : i32, key : *mut core::ffi::c_void) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __wake_up_bit(wq_head : *mut wait_queue_head, word : *mut u64, bit : i32));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __wake_up_locked(wq_head : *mut wait_queue_head, mode : u32, nr : i32));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __wake_up_locked_key(wq_head : *mut wait_queue_head, mode : u32, key : *mut core::ffi::c_void));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __wake_up_locked_sync_key(wq_head : *mut wait_queue_head, mode : u32, key : *mut core::ffi::c_void));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __wake_up_on_current_cpu(wq_head : *mut wait_queue_head, mode : u32, key : *mut core::ffi::c_void));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __wake_up_pollfree(wq_head : *mut wait_queue_head));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __wake_up_sync(wq_head : *mut wait_queue_head, mode : u32));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __wake_up_sync_key(wq_head : *mut wait_queue_head, mode : u32, key : *mut core::ffi::c_void));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn add_wait_queue(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn add_wait_queue_exclusive(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn add_wait_queue_priority(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn add_wait_queue_priority_exclusive(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn atomic_dec_and_wake_up(var : *mut super::types:: atomic_t) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn autoremove_wake_function(wq_entry : *mut wait_queue_entry, mode : u32, sync : i32, key : *mut core::ffi::c_void) -> i32);
windows_link::link!("kernel" "C" fn bit_wait(key : *mut wait_bit_key, mode : i32) -> i32);
windows_link::link!("kernel" "C" fn bit_wait_io(key : *mut wait_bit_key, mode : i32) -> i32);
windows_link::link!("kernel" "C" fn bit_wait_timeout(key : *mut wait_bit_key, mode : i32) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn bit_waitqueue(word : *mut u64, bit : i32) -> *mut wait_queue_head);
windows_link::link!("kernel" "C" fn clear_and_wake_up_bit(bit : i32, word : *mut u64));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn complete(param0 : *mut completion));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn complete_acquire(x : *mut completion));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn complete_all(param0 : *mut completion));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn complete_on_current_cpu(x : *mut completion));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn complete_release(x : *mut completion));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn completion_done(x : *mut completion) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn default_wake_function(wq_entry : *mut wait_queue_entry, mode : u32, flags : i32, key : *mut core::ffi::c_void) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn do_wait_intr(param0 : *mut wait_queue_head_t, param1 : *mut wait_queue_entry_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn do_wait_intr_irq(param0 : *mut wait_queue_head_t, param1 : *mut wait_queue_entry_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn finish_swait(q : *mut swait_queue_head, wait : *mut swait_queue));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn finish_wait(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn init_completion(x : *mut completion));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn init_wait_entry(wq_entry : *mut wait_queue_entry, flags : i32));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn init_wait_var_entry(wbq_entry : *mut wait_bit_queue_entry, var : *mut core::ffi::c_void, flags : i32));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn init_waitqueue_entry(wq_entry : *mut wait_queue_entry, p : *mut core::ffi::c_void));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn init_waitqueue_func_entry(wq_entry : *mut wait_queue_entry, func : wait_queue_func_t));
windows_link::link!("kernel" "C" fn out_of_line_wait_on_bit(word : *mut u64, param1 : i32, action : *mut wait_bit_action_f, mode : u32) -> i32);
windows_link::link!("kernel" "C" fn out_of_line_wait_on_bit_lock(word : *mut u64, param1 : i32, action : *mut wait_bit_action_f, mode : u32) -> i32);
windows_link::link!("kernel" "C" fn out_of_line_wait_on_bit_timeout(word : *mut u64, param1 : i32, action : *mut wait_bit_action_f, mode : u32, timeout : u64) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn prepare_to_swait_event(q : *mut swait_queue_head, wait : *mut swait_queue, state : i32) -> i64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn prepare_to_swait_exclusive(q : *mut swait_queue_head, wait : *mut swait_queue, state : i32));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn prepare_to_wait(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry, state : i32));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn prepare_to_wait_event(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry, state : i32) -> i64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn prepare_to_wait_exclusive(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry, state : i32) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn reinit_completion(x : *mut completion));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn remove_wait_queue(wq_head : *mut wait_queue_head, wq_entry : *mut wait_queue_entry));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn swait_active(wq : *mut swait_queue_head) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn swake_up_all(q : *mut swait_queue_head));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn swake_up_locked(q : *mut swait_queue_head, wake_flags : i32));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn swake_up_one(q : *mut swait_queue_head));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn swq_has_sleeper(wq : *mut swait_queue_head) -> bool);
windows_link::link!("kernel" "C" fn task_call_func(p : *mut core::ffi::c_void, func : task_call_f, arg : *mut core::ffi::c_void) -> i32);
windows_link::link!("kernel" "C" fn test_and_clear_wake_up_bit(bit : i32, word : *mut u64) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn try_wait_for_completion(x : *mut completion) -> bool);
windows_link::link!("kernel" "C" fn wait_bit_init());
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn wait_for_completion(param0 : *mut completion));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn wait_for_completion_interruptible(x : *mut completion) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn wait_for_completion_interruptible_timeout(x : *mut completion, timeout : u64) -> i64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn wait_for_completion_io(param0 : *mut completion));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn wait_for_completion_io_timeout(x : *mut completion, timeout : u64) -> u64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn wait_for_completion_killable(x : *mut completion) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn wait_for_completion_killable_timeout(x : *mut completion, timeout : u64) -> i64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn wait_for_completion_state(x : *mut completion, state : u32) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn wait_for_completion_timeout(x : *mut completion, timeout : u64) -> u64);
windows_link::link!("kernel" "C" fn wait_on_bit(word : *mut u64, bit : i32, mode : u32) -> i32);
windows_link::link!("kernel" "C" fn wait_on_bit_action(word : *mut u64, bit : i32, action : *mut wait_bit_action_f, mode : u32) -> i32);
windows_link::link!("kernel" "C" fn wait_on_bit_io(word : *mut u64, bit : i32, mode : u32) -> i32);
windows_link::link!("kernel" "C" fn wait_on_bit_lock(word : *mut u64, bit : i32, mode : u32) -> i32);
windows_link::link!("kernel" "C" fn wait_on_bit_lock_action(word : *mut u64, bit : i32, action : *mut wait_bit_action_f, mode : u32) -> i32);
windows_link::link!("kernel" "C" fn wait_on_bit_lock_io(word : *mut u64, bit : i32, mode : u32) -> i32);
windows_link::link!("kernel" "C" fn wait_on_bit_timeout(word : *mut u64, bit : i32, mode : u32, timeout : u64) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn wait_woken(wq_entry : *mut wait_queue_entry, mode : u32, timeout : i64) -> i64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn waitqueue_active(wq_head : *mut wait_queue_head) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn wake_bit_function(wq_entry : *mut wait_queue_entry, mode : u32, sync : i32, key : *mut core::ffi::c_void) -> i32);
windows_link::link!("kernel" "C" fn wake_up_bit(word : *mut u64, bit : i32));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn wake_up_pollfree(wq_head : *mut wait_queue_head));
windows_link::link!("kernel" "C" fn wake_up_var(var : *mut core::ffi::c_void));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn woken_wake_function(wq_entry : *mut wait_queue_entry, mode : u32, sync : i32, key : *mut core::ffi::c_void) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn wq_has_single_sleeper(wq_head : *mut wait_queue_head) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn wq_has_sleeper(wq_head : *mut wait_queue_head) -> bool);
pub const WQ_FLAG_CUSTOM: i32 = 4i32;
pub const WQ_FLAG_DONE: i32 = 8i32;
pub const WQ_FLAG_EXCLUSIVE: i32 = 1i32;
pub const WQ_FLAG_PRIORITY: i32 = 16i32;
pub const WQ_FLAG_WOKEN: i32 = 2i32;
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct completion {
    pub done: u32,
    pub wait: swait_queue_head,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for completion {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct swait_queue {
    pub task: *mut core::ffi::c_void,
    pub task_list: super::types::list_head,
}
#[cfg(feature = "types")]
impl Default for swait_queue {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct swait_queue_head {
    pub lock: super::sync::raw_spinlock_t,
    pub task_list: super::types::list_head,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for swait_queue_head {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type task_call_f = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const core::ffi::c_void,
    ) -> i32,
>;
pub type wait_bit_action_f =
    Option<unsafe extern "system" fn(param0: *const wait_bit_key, param1: i32) -> i32>;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct wait_bit_key {
    pub flags: *mut u64,
    pub bit_nr: i32,
    pub timeout: u64,
}
impl Default for wait_bit_key {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct wait_bit_queue_entry {
    pub key: wait_bit_key,
    pub wq_entry: wait_queue_entry,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct wait_queue_entry {
    pub flags: u32,
    pub private: *mut core::ffi::c_void,
    pub func: wait_queue_func_t,
    pub entry: super::types::list_head,
}
#[cfg(feature = "types")]
impl Default for wait_queue_entry {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C)]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct wait_queue_entry_t {
    pub Value: wait_queue_entry,
}
#[cfg(feature = "types")]
pub type wait_queue_func_t = Option<
    unsafe extern "system" fn(
        param0: *const wait_queue_entry,
        param1: u32,
        param2: i32,
        param3: *const core::ffi::c_void,
    ) -> i32,
>;
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct wait_queue_head {
    pub lock: super::sync::spinlock_t,
    pub head: super::types::list_head,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for wait_queue_head {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C)]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct wait_queue_head_t {
    pub Value: wait_queue_head,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for wait_queue_head_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
