// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub const ___GFP_ACCOUNT_BIT: u32 = 22u32;
pub const ___GFP_COMP_BIT: u32 = 18u32;
pub const ___GFP_DIRECT_RECLAIM_BIT: u32 = 10u32;
pub const ___GFP_DMA32_BIT: u32 = 2u32;
pub const ___GFP_DMA_BIT: u32 = 0u32;
pub const ___GFP_FS_BIT: u32 = 7u32;
pub const ___GFP_HARDWALL_BIT: u32 = 20u32;
pub const ___GFP_HIGHMEM_BIT: u32 = 1u32;
pub const ___GFP_HIGH_BIT: u32 = 5u32;
pub const ___GFP_IO_BIT: u32 = 6u32;
pub const ___GFP_KSWAPD_RECLAIM_BIT: u32 = 11u32;
pub const ___GFP_LAST_BIT: u32 = 25u32;
pub const ___GFP_MEMALLOC_BIT: u32 = 17u32;
pub const ___GFP_MOVABLE_BIT: u32 = 3u32;
pub const ___GFP_NOFAIL_BIT: u32 = 15u32;
pub const ___GFP_NOLOCKDEP: i32 = 0i32;
pub const ___GFP_NOMEMALLOC_BIT: u32 = 19u32;
pub const ___GFP_NORETRY_BIT: u32 = 16u32;
pub const ___GFP_NOWARN_BIT: u32 = 13u32;
pub const ___GFP_NO_OBJ_EXT_BIT: u32 = 24u32;
pub const ___GFP_RECLAIMABLE_BIT: u32 = 4u32;
pub const ___GFP_RETRY_MAYFAIL_BIT: u32 = 14u32;
pub const ___GFP_SKIP_KASAN: i32 = 0i32;
pub const ___GFP_SKIP_ZERO: i32 = 0i32;
pub const ___GFP_THISNODE_BIT: u32 = 21u32;
pub const ___GFP_UNUSED_BIT: u32 = 9u32;
pub const ___GFP_WRITE_BIT: u32 = 12u32;
pub const ___GFP_ZEROTAGS_BIT: u32 = 23u32;
pub const ___GFP_ZERO_BIT: u32 = 8u32;
