// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __kunit_abort(test : *mut kunit));
windows_link::link!("kernel" "C" fn __kunit_test_suites_exit(suites : *mut *mut kunit_suite, num_suites : i32));
windows_link::link!("kernel" "C" fn __kunit_test_suites_init(suites : *const *const kunit_suite, num_suites : i32, run_tests : bool) -> i32);
windows_link::link!("kernel" "C" fn kunit_action() -> *mut i8);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_array_gen_params(test : *mut kunit, prev : *const core::ffi::c_void, desc : *mut i8) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn kunit_assert_prologue(loc : *const kunit_loc, r#type : kunit_assert_type, stream : *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn kunit_attach_mm() -> i32);
windows_link::link!("kernel" "C" fn kunit_autorun() -> bool);
windows_link::link!("kernel" "C" fn kunit_binary_assert_format(assert : *const kunit_assert, message : *const va_format, stream : *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn kunit_binary_ptr_assert_format(assert : *const kunit_assert, message : *const va_format, stream : *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn kunit_binary_str_assert_format(assert : *const kunit_assert, message : *const va_format, stream : *mut core::ffi::c_void));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_cleanup(test : *mut kunit));
windows_link::link!("kernel" "C" fn kunit_enabled() -> bool);
windows_link::link!("kernel" "C" fn kunit_exec_list_tests(suite_set : *mut kunit_suite_set, include_attr : bool));
windows_link::link!("kernel" "C" fn kunit_exec_run_tests(suite_set : *mut kunit_suite_set, builtin : bool));
windows_link::link!("kernel" "C" fn kunit_fail_assert_format(assert : *const kunit_assert, message : *const va_format, stream : *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn kunit_filter() -> *mut i8);
windows_link::link!("kernel" "C" fn kunit_filter_action() -> *mut i8);
windows_link::link!("kernel" "C" fn kunit_filter_glob() -> *mut i8);
windows_link::link!("kernel" "C" fn kunit_filter_suites(suite_set : *const kunit_suite_set, filter_glob : *const i8, filters : *mut i8, filter_action : *mut i8, err : *mut i32) -> kunit_suite_set);
windows_link::link!("kernel" "C" fn kunit_free_suite_set(suite_set : kunit_suite_set));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_init_test(test : *mut kunit, name : *const i8, log : *mut core::ffi::c_void));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_kcalloc(test : *mut kunit, n : super::types:: size_t, size : super::types:: size_t, gfp : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_kfree(test : *mut kunit, ptr : *const core::ffi::c_void));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_kfree_const(test : *mut kunit, x : *const core::ffi::c_void));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_kmalloc(test : *mut kunit, size : super::types:: size_t, gfp : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_kmalloc_array(test : *mut kunit, n : super::types:: size_t, size : super::types:: size_t, gfp : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_kstrdup(test : *mut kunit, str : *const i8, gfp : super::types:: gfp_t) -> *mut i8);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_kstrdup_const(test : *mut kunit, str : *const i8, gfp : super::types:: gfp_t) -> *mut i8);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_kzalloc(test : *mut kunit, size : super::types:: size_t, gfp : super::types:: gfp_t) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn kunit_mem_assert_format(assert : *const kunit_assert, message : *const va_format, stream : *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn kunit_merge_suite_sets(init_suite_set : kunit_suite_set, suite_set : kunit_suite_set) -> kunit_suite_set);
windows_link::link!("kernel" "C" fn kunit_ptr_not_err_assert_format(assert : *const kunit_assert, message : *const va_format, stream : *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn kunit_run_all_tests() -> i32);
windows_link::link!("kernel" "C" fn kunit_run_tests(suite : *mut kunit_suite) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_set_failure(test : *mut kunit));
windows_link::link!("kernel" "C" fn kunit_status_to_ok_not_ok(status : kunit_status) -> *mut i8);
windows_link::link!("kernel" "C" fn kunit_suite_has_succeeded(suite : *mut kunit_suite) -> kunit_status);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kunit_suite_num_test_cases(suite : *mut kunit_suite) -> super::types:: size_t);
windows_link::link!("kernel" "C" fn kunit_test_case_num(suite : *mut kunit_suite, test_case : *mut kunit_case) -> u32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_try_catch_get_result(try_catch : *mut kunit_try_catch) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_try_catch_run(try_catch : *mut kunit_try_catch, context : *mut core::ffi::c_void));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_try_catch_throw(try_catch : *mut kunit_try_catch));
windows_link::link!("kernel" "C" fn kunit_unary_assert_format(assert : *const kunit_assert, message : *const va_format, stream : *mut core::ffi::c_void));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn kunit_vm_mmap(test : *mut kunit, file : *mut core::ffi::c_void, addr : u64, len : u64, prot : u64, flag : u64, offset : u64) -> u64);
pub const KUNIT_ASSERTION: u32 = 0u32;
pub const KUNIT_EXPECTATION: u32 = 1u32;
pub const KUNIT_FAILURE: u32 = 1u32;
pub const KUNIT_INDENT_LEN: i32 = 4i32;
pub const KUNIT_PARAM_DESC_SIZE: i32 = 128i32;
pub const KUNIT_SKIPPED: u32 = 2u32;
pub const KUNIT_SPEED_MAX: u32 = 3u32;
pub const KUNIT_SPEED_NORMAL: u32 = 3u32;
pub const KUNIT_SPEED_SLOW: u32 = 2u32;
pub const KUNIT_SPEED_UNSET: u32 = 0u32;
pub const KUNIT_SPEED_VERY_SLOW: u32 = 1u32;
pub const KUNIT_STATUS_COMMENT_SIZE: i32 = 256i32;
pub const KUNIT_SUCCESS: u32 = 0u32;
pub type assert_format_t = Option<
    unsafe extern "system" fn(
        param0: *const kunit_assert,
        param1: *const va_format,
        param2: *const core::ffi::c_void,
    ),
>;
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct kunit {
    pub r#priv: *mut core::ffi::c_void,
    pub parent: *mut kunit,
    pub params_array: kunit_params,
    pub name: *mut i8,
    pub log: *mut core::ffi::c_void,
    pub try_catch: kunit_try_catch,
    pub param_value: *mut core::ffi::c_void,
    pub param_index: i32,
    pub lock: super::sync::spinlock_t,
    pub status: kunit_status,
    pub resources: super::types::list_head,
    pub status_comment: [i8; 256],
    pub last_seen: kunit_loc,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for kunit {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(1))]
#[derive(Clone, Copy, Default)]
pub struct kunit_assert(pub u8);
pub type kunit_assert_type = u32;
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct kunit_attributes {
    pub speed: kunit_speed,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct kunit_binary_assert {
    pub assert: kunit_assert,
    pub text: *mut kunit_binary_assert_text,
    pub left_value: i64,
    pub right_value: i64,
}
impl Default for kunit_binary_assert {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct kunit_binary_assert_text {
    pub operation: *mut i8,
    pub left_text: *mut i8,
    pub right_text: *mut i8,
}
impl Default for kunit_binary_assert_text {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct kunit_binary_ptr_assert {
    pub assert: kunit_assert,
    pub text: *mut kunit_binary_assert_text,
    pub left_value: *mut core::ffi::c_void,
    pub right_value: *mut core::ffi::c_void,
}
impl Default for kunit_binary_ptr_assert {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct kunit_binary_str_assert {
    pub assert: kunit_assert,
    pub text: *mut kunit_binary_assert_text,
    pub left_value: *mut i8,
    pub right_value: *mut i8,
}
impl Default for kunit_binary_str_assert {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct kunit_case {
    pub run_case: *mut isize,
    pub name: *mut i8,
    pub generate_params: *mut isize,
    pub attr: kunit_attributes,
    pub param_init: *mut isize,
    pub param_exit: *mut isize,
    pub status: kunit_status,
    pub module_name: *mut i8,
    pub log: *mut core::ffi::c_void,
}
impl Default for kunit_case {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(1))]
#[derive(Clone, Copy, Default)]
pub struct kunit_fail_assert {
    pub assert: kunit_assert,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct kunit_loc {
    pub line: i32,
    pub file: *mut i8,
}
impl Default for kunit_loc {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct kunit_mem_assert {
    pub assert: kunit_assert,
    pub text: *mut kunit_binary_assert_text,
    pub left_value: *mut core::ffi::c_void,
    pub right_value: *mut core::ffi::c_void,
    pub size: super::types::size_t,
}
#[cfg(feature = "types")]
impl Default for kunit_mem_assert {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct kunit_params {
    pub params: *mut core::ffi::c_void,
    pub get_description: *mut isize,
    pub num_params: super::types::size_t,
    pub elem_size: super::types::size_t,
}
#[cfg(feature = "types")]
impl Default for kunit_params {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct kunit_ptr_not_err_assert {
    pub assert: kunit_assert,
    pub text: *mut i8,
    pub value: *mut core::ffi::c_void,
}
impl Default for kunit_ptr_not_err_assert {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type kunit_speed = u32;
pub type kunit_status = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct kunit_suite {
    pub name: [i8; 256],
    pub suite_init: *mut isize,
    pub suite_exit: *mut isize,
    pub init: *mut isize,
    pub exit: *mut isize,
    pub test_cases: *mut kunit_case,
    pub attr: kunit_attributes,
    pub status_comment: [i8; 256],
    pub debugfs: *mut core::ffi::c_void,
    pub log: *mut core::ffi::c_void,
    pub suite_init_err: i32,
    pub is_init: bool,
}
impl Default for kunit_suite {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct kunit_suite_set {
    pub start: *mut *mut kunit_suite,
    pub end: *mut *mut kunit_suite,
}
impl Default for kunit_suite_set {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct kunit_try_catch {
    pub test: *mut kunit,
    pub try_result: i32,
    pub r#try: kunit_try_catch_func_t,
    pub catch: kunit_try_catch_func_t,
    pub timeout: u64,
    pub context: *mut core::ffi::c_void,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for kunit_try_catch {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type kunit_try_catch_func_t =
    Option<unsafe extern "system" fn(param0: *const core::ffi::c_void)>;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct kunit_unary_assert {
    pub assert: kunit_assert,
    pub condition: *mut i8,
    pub expected_true: bool,
}
impl Default for kunit_unary_assert {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct va_format {
    pub _reserved: [u64; 1],
}
impl Default for va_format {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
