// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("kernel" "C" fn __free_kfree(p : *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn __free_kfree_sensitive(p : *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn __free_kvfree(p : *mut core::ffi::c_void));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __kmalloc_cache_node_noprof(s : *mut core::ffi::c_void, gfpflags : super::types:: gfp_t, node : i32, size : super::types:: size_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __kmalloc_cache_noprof(s : *mut core::ffi::c_void, flags : super::types:: gfp_t, size : super::types:: size_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __kmalloc_index(size : super::types:: size_t, size_is_constant : bool) -> u32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __kmalloc_large_node_noprof(size : super::types:: size_t, flags : super::types:: gfp_t, node : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __kmalloc_large_noprof(size : super::types:: size_t, flags : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __kmalloc_node_noprof(size : super::types:: size_t, flags : super::types:: gfp_t, node : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __kmalloc_node_track_caller_noprof(size : super::types:: size_t, flags : super::types:: gfp_t, node : i32, caller : u64) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __kmalloc_noprof(size : super::types:: size_t, flags : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __kmem_cache_create(name : *const i8, size : u32, align : u32, flags : super::types:: slab_flags_t, ctor : *mut isize) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __kmem_cache_create_args(name : *const i8, object_size : u32, args : *mut kmem_cache_args, flags : super::types:: slab_flags_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __kmem_cache_default_args(name : *const i8, size : u32, args : *mut kmem_cache_args, flags : super::types:: slab_flags_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __kvmalloc_node_noprof(size : super::types:: size_t, align : u64, flags : super::types:: gfp_t, node : i32) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn arch_slab_minalign() -> u32);
windows_link::link!("kernel" "C" fn kfree(objp : *const core::ffi::c_void));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kfree_bulk(size : super::types:: size_t, p : *mut *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn kfree_nolock(objp : *const core::ffi::c_void));
windows_link::link!("kernel" "C" fn kfree_rcu_scheduler_running());
windows_link::link!("kernel" "C" fn kfree_sensitive(objp : *const core::ffi::c_void));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmalloc_array_node_noprof(n : super::types:: size_t, size : super::types:: size_t, flags : super::types:: gfp_t, node : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmalloc_array_noprof(n : super::types:: size_t, size : super::types:: size_t, flags : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmalloc_node_noprof(size : super::types:: size_t, flags : super::types:: gfp_t, node : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmalloc_nolock_noprof(size : super::types:: size_t, gfp_flags : super::types:: gfp_t, node : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmalloc_noprof(size : super::types:: size_t, flags : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmalloc_size_roundup(size : super::types:: size_t) -> super::types:: size_t);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmalloc_type(flags : super::types:: gfp_t, caller : u64) -> kmalloc_cache_type);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmem_buckets_create(name : *const i8, flags : super::types:: slab_flags_t, useroffset : u32, usersize : u32, ctor : *mut isize) -> *mut kmem_buckets);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmem_cache_alloc_bulk_noprof(s : *mut core::ffi::c_void, flags : super::types:: gfp_t, size : super::types:: size_t, p : *mut *mut core::ffi::c_void) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmem_cache_alloc_from_sheaf_noprof(cachep : *mut core::ffi::c_void, gfp : super::types:: gfp_t, sheaf : *mut core::ffi::c_void) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmem_cache_alloc_lru_noprof(s : *mut core::ffi::c_void, lru : *mut core::ffi::c_void, gfpflags : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmem_cache_alloc_node_noprof(s : *mut core::ffi::c_void, flags : super::types:: gfp_t, node : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmem_cache_alloc_noprof(cachep : *mut core::ffi::c_void, flags : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmem_cache_charge(objp : *mut core::ffi::c_void, gfpflags : super::types:: gfp_t) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmem_cache_create_usercopy(name : *const i8, size : u32, align : u32, flags : super::types:: slab_flags_t, useroffset : u32, usersize : u32, ctor : *mut isize) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn kmem_cache_destroy(s : *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn kmem_cache_free(s : *mut core::ffi::c_void, objp : *mut core::ffi::c_void));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmem_cache_free_bulk(s : *mut core::ffi::c_void, size : super::types:: size_t, p : *mut *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn kmem_cache_init_late());
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmem_cache_prefill_sheaf(s : *mut core::ffi::c_void, gfp : super::types:: gfp_t, size : u32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmem_cache_refill_sheaf(s : *mut core::ffi::c_void, gfp : super::types:: gfp_t, sheafp : *mut *mut core::ffi::c_void, size : u32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kmem_cache_return_sheaf(s : *mut core::ffi::c_void, gfp : super::types:: gfp_t, sheaf : *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn kmem_cache_sheaf_size(sheaf : *mut core::ffi::c_void) -> u32);
windows_link::link!("kernel" "C" fn kmem_cache_shrink(s : *mut core::ffi::c_void) -> i32);
windows_link::link!("kernel" "C" fn kmem_cache_size(s : *mut core::ffi::c_void) -> u32);
windows_link::link!("kernel" "C" fn kmem_dump_obj(object : *mut core::ffi::c_void) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn krealloc_array_noprof(p : *mut core::ffi::c_void, new_n : super::types:: size_t, new_size : super::types:: size_t, flags : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn krealloc_node_align_noprof(objp : *const core::ffi::c_void, new_size : super::types:: size_t, align : u64, flags : super::types:: gfp_t, nid : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn ksize(objp : *const core::ffi::c_void) -> super::types:: size_t);
windows_link::link!("kernel" "C" fn kvfree(addr : *const core::ffi::c_void));
windows_link::link!("kernel" "C" fn kvfree_rcu_barrier());
windows_link::link!("kernel" "C" fn kvfree_rcu_barrier_on_cache(s : *mut core::ffi::c_void));
windows_link::link!("kernel" "C" fn kvfree_rcu_init());
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kvfree_sensitive(addr : *const core::ffi::c_void, len : super::types:: size_t));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kvmalloc_array_node_noprof(n : super::types:: size_t, size : super::types:: size_t, flags : super::types:: gfp_t, node : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kvrealloc_node_align_noprof(p : *const core::ffi::c_void, size : super::types:: size_t, align : u64, flags : super::types:: gfp_t, nid : i32) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn kzalloc_noprof(size : super::types:: size_t, flags : super::types:: gfp_t) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn slab_is_available() -> bool);
pub const KMALLOC_CGROUP: u32 = 0u32;
pub const KMALLOC_DMA: u32 = 2u32;
pub const KMALLOC_NORMAL: u32 = 0u32;
pub const KMALLOC_RANDOM_END: u32 = 0u32;
pub const KMALLOC_RANDOM_START: u32 = 0u32;
pub const KMALLOC_RECLAIM: u32 = 1u32;
pub const KMALLOC_SHIFT_LOW: i32 = 3i32;
pub const NR_KMALLOC_TYPES: u32 = 3u32;
pub const RANDOM_KMALLOC_CACHES_NR: i32 = 0i32;
pub const _SLAB_CACHE_DMA: u32 = 5u32;
pub const _SLAB_CACHE_DMA32: u32 = 6u32;
pub const _SLAB_CMPXCHG_DOUBLE: u32 = 16u32;
pub const _SLAB_CONSISTENCY_CHECKS: u32 = 0u32;
pub const _SLAB_FLAGS_LAST_BIT: u32 = 18u32;
pub const _SLAB_HWCACHE_ALIGN: u32 = 4u32;
pub const _SLAB_KMALLOC: u32 = 3u32;
pub const _SLAB_NOLEAKTRACE: u32 = 11u32;
pub const _SLAB_NO_MERGE: u32 = 12u32;
pub const _SLAB_NO_OBJ_EXT: u32 = 17u32;
pub const _SLAB_NO_USER_FLAGS: u32 = 13u32;
pub const _SLAB_OBJECT_POISON: u32 = 15u32;
pub const _SLAB_PANIC: u32 = 8u32;
pub const _SLAB_POISON: u32 = 2u32;
pub const _SLAB_RECLAIM_ACCOUNT: u32 = 14u32;
pub const _SLAB_RED_ZONE: u32 = 1u32;
pub const _SLAB_STORE_USER: u32 = 7u32;
pub const _SLAB_TRACE: u32 = 10u32;
pub const _SLAB_TYPESAFE_BY_RCU: u32 = 9u32;
pub type _slab_flag_bits = u32;
pub type kmalloc_cache_type = u32;
#[repr(C)]
#[derive(Clone, Copy)]
pub struct kmem_buckets {
    pub Value: [*mut core::ffi::c_void; 14],
}
impl Default for kmem_buckets {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct kmem_cache_args {
    pub align: u32,
    pub useroffset: u32,
    pub usersize: u32,
    pub freeptr_offset: u32,
    pub use_freeptr_offset: bool,
    pub ctor: *mut isize,
    pub sheaf_capacity: u32,
}
impl Default for kmem_cache_args {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
