// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("kernel" "C" fn INIT_HLIST_BL_NODE(h : *mut hlist_bl_node));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __d_drop(dentry : *mut dentry));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __d_entry_type(dentry : *const dentry) -> u32);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __d_lookup_unhash_wake(dentry : *mut dentry));
windows_link::link!("kernel" "C" fn __d_path(param0 : *const core::ffi::c_void, param1 : *const core::ffi::c_void, param2 : *mut i8, param3 : i32) -> *mut i8);
windows_link::link!("kernel" "C" fn __hlist_bl_del(n : *mut hlist_bl_node));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn cant_mount(dentry : *const dentry) -> i32);
windows_link::link!("kernel" "C" fn d_absolute_path(param0 : *const core::ffi::c_void, param1 : *mut i8, param2 : i32) -> *mut i8);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_add(param0 : *mut dentry, param1 : *mut core::ffi::c_void));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_add_ci(param0 : *mut dentry, param1 : *mut core::ffi::c_void, param2 : *mut qstr) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_alloc(param0 : *mut dentry, param1 : *const qstr) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_alloc_anon(param0 : *mut core::ffi::c_void) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_alloc_parallel(param0 : *mut dentry, param1 : *const qstr, param2 : *mut super::fs:: wait_queue_head_t) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_ancestor(param0 : *mut dentry, param1 : *mut dentry) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_backing_inode(upper : *const dentry) -> *mut core::ffi::c_void);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_can_lookup(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_count(dentry : *const dentry) -> u32);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_delete(param0 : *mut dentry));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_dispose_if_unused(param0 : *mut dentry, param1 : *mut super::types:: list_head));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_drop(dentry : *mut dentry));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_exchange(param0 : *mut dentry, param1 : *mut dentry));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_find_alias(param0 : *mut core::ffi::c_void) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_find_alias_rcu(param0 : *mut core::ffi::c_void) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_find_any_alias(inode : *mut core::ffi::c_void) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_first_child(dentry : *const dentry) -> *mut dentry);
windows_link::link!("kernel" "C" fn d_flags_negative(flags : u32) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_in_lookup(dentry : *const dentry) -> i32);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_inode(dentry : *const dentry) -> *mut core::ffi::c_void);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_inode_rcu(dentry : *const dentry) -> *mut core::ffi::c_void);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_instantiate(param0 : *mut dentry, param1 : *mut core::ffi::c_void));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_instantiate_new(param0 : *mut dentry, param1 : *mut core::ffi::c_void));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_invalidate(param0 : *mut dentry));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_is_autodir(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_is_dir(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_is_file(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_is_miss(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_is_negative(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_is_positive(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_is_reg(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_is_special(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_is_symlink(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_is_whiteout(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_lookup(param0 : *const dentry, param1 : *const qstr) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_lookup_done(dentry : *mut dentry));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_make_discardable(dentry : *mut dentry));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_make_persistent(param0 : *mut dentry, param1 : *mut core::ffi::c_void) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_make_root(param0 : *mut core::ffi::c_void) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_managed(dentry : *const dentry) -> bool);
windows_link::link!("kernel" "C" fn d_mark_tmpfile(param0 : *mut core::ffi::c_void, param1 : *mut core::ffi::c_void));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_mountpoint(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_move(param0 : *mut dentry, param1 : *mut dentry));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_next_sibling(dentry : *const dentry) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_obtain_alias(param0 : *mut core::ffi::c_void) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_obtain_root(param0 : *mut core::ffi::c_void) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_parent_ino(dentry : *mut dentry) -> super::types:: ino_t);
windows_link::link!("kernel" "C" fn d_path(param0 : *const core::ffi::c_void, param1 : *mut i8, param2 : i32) -> *mut i8);
windows_link::link!("kernel" "C" fn d_prune_aliases(param0 : *mut core::ffi::c_void));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_real(dentry : *mut dentry, r#type : d_real_type) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_real_inode(dentry : *const dentry) -> *mut core::ffi::c_void);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_really_is_negative(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_really_is_positive(dentry : *const dentry) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_rehash(param0 : *mut dentry));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_same_name(dentry : *const dentry, parent : *const dentry, name : *const qstr) -> bool);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_splice_alias(param0 : *mut core::ffi::c_void, param1 : *mut dentry) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_splice_alias_ops(param0 : *mut core::ffi::c_void, param1 : *mut dentry, param2 : *const dentry_operations) -> *mut dentry);
windows_link::link!("kernel" "C" fn d_tmpfile(param0 : *mut core::ffi::c_void, param1 : *mut core::ffi::c_void));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_unhashed(dentry : *const dentry) -> i32);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn d_unlinked(dentry : *const dentry) -> i32);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn dentry_path(param0 : *const dentry, param1 : *mut i8, param2 : i32) -> *mut i8);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn dentry_path_raw(param0 : *const dentry, param1 : *mut i8, param2 : i32) -> *mut i8);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn dget(dentry : *mut dentry) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn dget_dlock(dentry : *mut dentry) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn dget_parent(dentry : *mut dentry) -> *mut dentry);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn dont_mount(dentry : *mut dentry));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn dput(param0 : *mut dentry));
windows_link::link!("kernel" "C" fn hlist_bl_add_before(n : *mut hlist_bl_node, next : *mut hlist_bl_node));
windows_link::link!("kernel" "C" fn hlist_bl_add_behind(n : *mut hlist_bl_node, prev : *mut hlist_bl_node));
windows_link::link!("kernel" "C" fn hlist_bl_add_head(n : *mut hlist_bl_node, h : *mut hlist_bl_head));
windows_link::link!("kernel" "C" fn hlist_bl_del(n : *mut hlist_bl_node));
windows_link::link!("kernel" "C" fn hlist_bl_del_init(n : *mut hlist_bl_node));
windows_link::link!("kernel" "C" fn hlist_bl_empty(h : *const hlist_bl_head) -> bool);
windows_link::link!("kernel" "C" fn hlist_bl_first(h : *mut hlist_bl_head) -> *mut hlist_bl_node);
windows_link::link!("kernel" "C" fn hlist_bl_is_locked(b : *mut hlist_bl_head) -> bool);
windows_link::link!("kernel" "C" fn hlist_bl_lock(b : *mut hlist_bl_head));
windows_link::link!("kernel" "C" fn hlist_bl_set_first(h : *mut hlist_bl_head, n : *mut hlist_bl_node));
windows_link::link!("kernel" "C" fn hlist_bl_unhashed(h : *const hlist_bl_node) -> bool);
windows_link::link!("kernel" "C" fn hlist_bl_unlock(b : *mut hlist_bl_head));
windows_link::link!("kernel" "C" fn path_has_submounts(param0 : *const core::ffi::c_void) -> i32);
windows_link::link!("kernel" "C" fn release_dentry_name_snapshot(param0 : *mut name_snapshot));
windows_link::link!("kernel" "C" fn set_default_d_op(param0 : *mut core::ffi::c_void, param1 : *const dentry_operations));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn shrink_dcache_parent(param0 : *mut dentry));
windows_link::link!("kernel" "C" fn shrink_dcache_sb(param0 : *mut core::ffi::c_void));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn shrink_dentry_list(param0 : *mut super::types:: list_head));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn simple_positive(dentry : *const dentry) -> i32);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn take_dentry_name_snapshot(param0 : *mut name_snapshot, param1 : *mut dentry));
windows_link::link!("kernel" "C" fn vfs_pressure_ratio(val : u64) -> u64);
pub const DCACHE_AUTODIR_TYPE: u32 = 1572864u32;
pub const DCACHE_CANT_MOUNT: u32 = 256u32;
pub const DCACHE_DENTRY_CURSOR: u32 = 33554432u32;
pub const DCACHE_DENTRY_KILLED: u32 = 16384u32;
pub const DCACHE_DIRECTORY_TYPE: u32 = 1048576u32;
pub const DCACHE_DISCONNECTED: u32 = 32u32;
pub const DCACHE_DONTCACHE: u32 = 128u32;
pub const DCACHE_ENTRY_TYPE: u32 = 3670016u32;
pub const DCACHE_FSNOTIFY_PARENT_WATCHED: u32 = 8192u32;
pub const DCACHE_LRU_LIST: u32 = 262144u32;
pub const DCACHE_MANAGE_TRANSIT: u32 = 131072u32;
pub const DCACHE_MISS_TYPE: u32 = 0u32;
pub const DCACHE_MOUNTED: u32 = 32768u32;
pub const DCACHE_NEED_AUTOMOUNT: u32 = 65536u32;
pub const DCACHE_NFSFS_RENAMED: u32 = 4096u32;
pub const DCACHE_NOKEY_NAME: u32 = 4194304u32;
pub const DCACHE_NORCU: u32 = 67108864u32;
pub const DCACHE_OP_COMPARE: u32 = 2u32;
pub const DCACHE_OP_DELETE: u32 = 8u32;
pub const DCACHE_OP_HASH: u32 = 1u32;
pub const DCACHE_OP_PRUNE: u32 = 16u32;
pub const DCACHE_OP_REAL: u32 = 8388608u32;
pub const DCACHE_OP_REVALIDATE: u32 = 4u32;
pub const DCACHE_OP_WEAK_REVALIDATE: u32 = 2048u32;
pub const DCACHE_PAR_LOOKUP: u32 = 16777216u32;
pub const DCACHE_PERSISTENT: u32 = 134217728u32;
pub const DCACHE_REFERENCED: u32 = 64u32;
pub const DCACHE_REGULAR_TYPE: u32 = 2097152u32;
pub const DCACHE_SHRINK_LIST: u32 = 1024u32;
pub const DCACHE_SPECIAL_TYPE: u32 = 2621440u32;
pub const DCACHE_SYMLINK_TYPE: u32 = 3145728u32;
pub const DCACHE_WHITEOUT_TYPE: u32 = 524288u32;
pub const DENTRY_D_LOCK_NESTED: u32 = 1u32;
pub const DENTRY_D_LOCK_NORMAL: u32 = 0u32;
pub const DNAME_INLINE_WORDS: i32 = 5i32;
pub const D_REAL_DATA: u32 = 0u32;
pub const D_REAL_METADATA: u32 = 1u32;
pub const LIST_BL_LOCKMASK: i32 = 1i32;
pub type d_real_type = u32;
#[repr(C, packed(8))]
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct dentry {
    pub d_flags: u32,
    pub d_seq: seqcount_spinlock,
    pub d_hash: hlist_bl_node,
    pub d_parent: *mut dentry,
    pub dentry__anon_0: dentry__anon_0,
    pub d_inode: *mut core::ffi::c_void,
    pub d_shortname: shortname_store,
    pub d_op: *mut dentry_operations,
    pub d_sb: *mut core::ffi::c_void,
    pub d_time: u64,
    pub d_fsdata: *mut core::ffi::c_void,
    pub d_lockref: super::sync::lockref,
    pub dentry__anon_1: dentry__anon_1,
    pub d_sib: super::types::hlist_node,
    pub d_children: super::types::hlist_head,
    pub d_u: dentry_d_u,
}
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
impl Default for dentry {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union dentry__anon_0 {
    pub __d_name: qstr,
    pub d_name: qstr,
}
impl Default for dentry__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub union dentry__anon_1 {
    pub d_lru: super::types::list_head,
    pub d_wait: *mut super::fs::wait_queue_head_t,
}
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
impl Default for dentry__anon_1 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type dentry_d_lock_class = u32;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union dentry_d_u {
    pub d_alias: super::types::hlist_node,
    pub d_in_lookup_hash: hlist_bl_node,
    pub d_rcu: super::types::callback_head,
}
#[cfg(feature = "types")]
impl Default for dentry_d_u {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type dentry_flags = u32;
#[repr(C, packed(64))]
#[derive(Clone, Copy)]
pub struct dentry_operations {
    pub d_revalidate: *mut isize,
    pub d_weak_revalidate: *mut isize,
    pub d_hash: *mut isize,
    pub d_compare: *mut isize,
    pub d_delete: *mut isize,
    pub d_init: *mut isize,
    pub d_release: *mut isize,
    pub d_prune: *mut isize,
    pub d_iput: *mut isize,
    pub d_dname: *mut isize,
    pub d_automount: *mut isize,
    pub d_manage: *mut isize,
    pub d_real: *mut isize,
    pub d_unalias_trylock: *mut isize,
    pub d_unalias_unlock: *mut isize,
    pub _padding: [u8; 8],
}
impl Default for dentry_operations {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct hlist_bl_head {
    pub first: *mut hlist_bl_node,
}
impl Default for hlist_bl_head {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct hlist_bl_node {
    pub next: *mut hlist_bl_node,
    pub pprev: *mut *mut hlist_bl_node,
}
impl Default for hlist_bl_node {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct name_snapshot {
    pub name: qstr,
    pub inline_name: shortname_store,
}
impl Default for name_snapshot {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct qstr {
    pub qstr__anon_0: qstr__anon_0,
    pub name: *mut u8,
}
impl Default for qstr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union qstr__anon_0 {
    pub qstr__anon_0__anon_0: qstr__anon_0__anon_0,
    pub hash_len: u64,
}
impl Default for qstr__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct qstr__anon_0__anon_0 {
    pub hash: u32,
    pub len: u32,
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct seqcount_spinlock {
    pub _reserved: [u32; 1],
}
impl Default for seqcount_spinlock {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union shortname_store {
    pub string: [u8; 40],
    pub words: [u64; 5],
}
impl Default for shortname_store {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
