// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub const READ: i32 = 0i32;
pub const WRITE: i32 = 1i32;
pub const __FD_SETSIZE: i32 = 1024i32;
pub type __be16 = __u16;
pub type __be32 = __u32;
pub type __be64 = __u64;
pub type __kernel_caddr_t = *mut i8;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_clockid_t = i32;
pub type __kernel_daddr_t = i32;
pub type __kernel_dev_t = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __kernel_fd_set {
    pub fds_bits: [u64; 16],
}
impl Default for __kernel_fd_set {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct __kernel_fsid_t {
    pub val: [i32; 2],
}
impl Default for __kernel_fsid_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type __kernel_gid16_t = u16;
pub type __kernel_gid32_t = u32;
pub type __kernel_gid_t = u32;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_ipc_pid_t = i32;
pub type __kernel_key_t = i32;
pub type __kernel_loff_t = i64;
pub type __kernel_long_t = i64;
pub type __kernel_mode_t = u32;
pub type __kernel_mqd_t = i32;
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_old_dev_t = u64;
pub type __kernel_old_gid_t = u16;
pub type __kernel_old_time_t = __kernel_long_t;
pub type __kernel_old_uid_t = u16;
pub type __kernel_pid_t = i32;
pub type __kernel_ptrdiff_t = __kernel_long_t;
pub type __kernel_sighandler_t = Option<unsafe extern "system" fn(param0: i32)>;
pub type __kernel_size_t = __kernel_ulong_t;
pub type __kernel_ssize_t = __kernel_long_t;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_time64_t = i64;
pub type __kernel_timer_t = i32;
pub type __kernel_uid16_t = u16;
pub type __kernel_uid32_t = u32;
pub type __kernel_uid_t = u32;
pub type __kernel_ulong_t = u64;
pub type __kernel_uoff_t = u64;
pub type __le16 = __u16;
pub type __le32 = __u32;
pub type __le64 = __u64;
pub type __poll_t = u32;
pub type __s16 = i16;
pub type __s32 = i32;
pub type __s64 = i64;
pub type __s8 = i8;
pub type __sum16 = __u16;
pub type __u16 = u16;
pub type __u32 = u32;
pub type __u64 = u64;
pub type __u8 = u8;
pub type __wsum = __u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy, Default)]
pub struct atomic64_t {
    pub counter: i64,
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct atomic_t {
    pub counter: i32,
}
pub type blkcnt_t = u64;
pub type caddr_t = __kernel_caddr_t;
pub type call_rcu_func_t =
    Option<unsafe extern "system" fn(param0: *const callback_head, param1: rcu_callback_t)>;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct callback_head {
    pub next: *mut callback_head,
    pub func: *mut isize,
}
impl Default for callback_head {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type clock_t = __kernel_clock_t;
pub type clockid_t = __kernel_clockid_t;
pub type cmp_func_t = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const core::ffi::c_void,
    ) -> i32,
>;
pub type cmp_r_func_t = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const core::ffi::c_void,
        param2: *const core::ffi::c_void,
    ) -> i32,
>;
pub type daddr_t = __kernel_daddr_t;
pub type dev_t = __kernel_dev_t;
pub type dma_addr_t = u64;
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct fd_set {
    pub Value: __kernel_fd_set,
}
pub type fmode_t = u32;
pub type gfp_t = u32;
pub type gid16_t = __kernel_gid16_t;
pub type gid_t = __kernel_gid32_t;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct hlist_head {
    pub first: *mut hlist_node,
}
impl Default for hlist_head {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct hlist_node {
    pub next: *mut hlist_node,
    pub pprev: *mut *mut hlist_node,
}
impl Default for hlist_node {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type ino_t = __kernel_ulong_t;
pub type int16_t = i16;
pub type int32_t = i32;
pub type int64_t = i64;
pub type int8_t = i8;
pub type intptr_t = i64;
pub type irq_hw_number_t = u64;
pub type key_t = __kernel_key_t;
pub type ktime_t = i64;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct list_head {
    pub next: *mut list_head,
    pub prev: *mut list_head,
}
impl Default for list_head {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type loff_t = __kernel_loff_t;
pub type mode_t = __kernel_mode_t;
pub type mqd_t = __kernel_mqd_t;
pub type nlink_t = u32;
pub type off_t = __kernel_off_t;
pub type phys_addr_t = u64;
#[repr(C, packed(8))]
#[derive(Clone, Copy, Default)]
pub struct phys_vec {
    pub paddr: phys_addr_t,
    pub len: size_t,
}
pub type pid_t = __kernel_pid_t;
pub type ptrdiff_t = __kernel_ptrdiff_t;
pub type rcu_callback_t = Option<unsafe extern "system" fn(param0: *const callback_head)>;
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct rcuref_t {
    pub refcnt: atomic_t,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rcuwait {
    pub task: *mut core::ffi::c_void,
}
impl Default for rcuwait {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type resource_size_t = phys_addr_t;
pub type sector_t = u64;
pub type size_t = __kernel_size_t;
pub type slab_flags_t = u32;
pub type ssize_t = __kernel_ssize_t;
pub type suseconds_t = __kernel_suseconds_t;
pub type swap_func_t = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const core::ffi::c_void,
        param2: i32,
    ),
>;
pub type swap_r_func_t = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const core::ffi::c_void,
        param2: i32,
        param3: *const core::ffi::c_void,
    ),
>;
pub type timer_t = __kernel_timer_t;
pub type u_char = u8;
pub type u_int = u32;
pub type u_int16_t = u16;
pub type u_int32_t = u32;
pub type u_int64_t = u64;
pub type u_int8_t = u8;
pub type u_long = u64;
pub type u_short = u16;
pub type uid16_t = __kernel_uid16_t;
pub type uid_t = __kernel_uid32_t;
pub type uint = u32;
pub type uint16_t = u16;
pub type uint32_t = u32;
pub type uint64_t = u64;
pub type uint8_t = u8;
pub type uintptr_t = u64;
pub type ullong = u64;
pub type ulong = u64;
pub type umode_t = u16;
pub type unchar = u8;
pub type uoff_t = __kernel_uoff_t;
pub type ushort = u16;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct ustat {
    pub f_tfree: __kernel_daddr_t,
    pub f_tinode: u64,
    pub f_fname: [i8; 6],
    pub f_fpack: [i8; 6],
}
impl Default for ustat {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
