// SPDX-License-Identifier: GPL-2.0
//
// C helper wrappers for kernel functions that are macros or static inlines.
// These create real symbols that Rust can link against.
//
// The Rust FFI bindings for these functions are auto-generated by bnd-winmd
// from helpers.h.

#include <linux/kconfig.h>
#include <linux/mm.h>
#include <linux/fs.h>
#include <linux/pagemap.h>
#include <linux/highmem.h>
#include <linux/slab.h>
#include <linux/mutex.h>
#include <linux/spinlock.h>
#include <linux/rcupdate.h>
#include <linux/lockdep.h>
#include <linux/sched.h>
#include <linux/sched/task.h>
#include <linux/kthread.h>
#include <linux/net.h>
#include <net/net_namespace.h>
#include <linux/workqueue.h>

#include "helpers.h"

// Folio helpers

void rust_helper_folio_get(struct folio *folio)
{
	folio_get(folio);
}

void rust_helper_folio_put(struct folio *folio)
{
	folio_put(folio);
}

loff_t rust_helper_folio_pos(struct folio *folio)
{
	return folio_pos(folio);
}

size_t rust_helper_folio_size(struct folio *folio)
{
	return folio_size(folio);
}

void rust_helper_folio_mark_uptodate(struct folio *folio)
{
	folio_mark_uptodate(folio);
}

void rust_helper_folio_end_read(struct folio *folio, bool success)
{
	folio_end_read(folio, success);
}

void rust_helper_flush_dcache_folio(struct folio *folio)
{
	flush_dcache_folio(folio);
}

void *rust_helper_kmap_local_folio(struct folio *folio, size_t offset)
{
	return kmap_local_folio(folio, offset);
}

void rust_helper_kunmap_local(const void *vaddr)
{
	kunmap_local(vaddr);
}

// Inode helpers

void *rust_helper_alloc_inode_sb(struct super_block *sb,
				 struct kmem_cache *cache, gfp_t gfp)
{
	return alloc_inode_sb(sb, cache, gfp);
}

void rust_helper_i_uid_write(struct inode *inode, uid_t uid)
{
	i_uid_write(inode, uid);
}

void rust_helper_i_gid_write(struct inode *inode, gid_t gid)
{
	i_gid_write(inode, gid);
}

void rust_helper_mapping_set_large_folios(struct address_space *mapping)
{
	mapping_set_large_folios(mapping);
}

void rust_helper_inode_set_flags(struct inode *inode,
				 unsigned int flags, unsigned int mask)
{
	inode_set_flags(inode, flags, mask);
}

void rust_helper_set_nlink(struct inode *inode, unsigned int nlink)
{
	set_nlink(inode, nlink);
}

// Directory emit helper

bool rust_helper_dir_emit(struct dir_context *ctx, const char *name,
			  int namelen, u64 ino, unsigned char type)
{
	return dir_emit(ctx, name, namelen, ino, type);
}

// Device number helper

unsigned int rust_helper_MKDEV(unsigned int major, unsigned int minor)
{
	return MKDEV(major, minor);
}

const struct inode_operations *rust_helper_page_symlink_inode_operations(void)
{
	return &page_symlink_inode_operations;
}

const struct inode_operations *rust_helper_simple_symlink_inode_operations(void)
{
	return &simple_symlink_inode_operations;
}

// kmem_cache helper

struct kmem_cache *rust_helper_kmem_cache_create(const char *name,
						  unsigned int size,
						  unsigned int align,
						  unsigned long flags,
						  void (*ctor)(void *))
{
	return kmem_cache_create(name, size, align, flags, ctor);
}

// Dentry name helpers

const unsigned char *rust_helper_dentry_name(const struct dentry *dentry)
{
	return dentry->d_name.name;
}

unsigned int rust_helper_dentry_name_len(const struct dentry *dentry)
{
	return dentry->d_name.len;
}

// ERR_PTR / IS_ERR / PTR_ERR helpers

void *rust_helper_ERR_PTR(long error)
{
	return ERR_PTR(error);
}

long rust_helper_PTR_ERR(const void *ptr)
{
	return PTR_ERR(ptr);
}

bool rust_helper_IS_ERR(const void *ptr)
{
	return IS_ERR(ptr);
}

// file->f_inode accessor

struct inode *rust_helper_file_inode(const struct file *f)
{
	return f->f_inode;
}

// inode ops setters (i_fop is in an anonymous union, not visible to bnd)

void rust_helper_inode_set_fop(struct inode *inode,
			       const struct file_operations *fop)
{
	inode->i_fop = fop;
}

void rust_helper_inode_set_aops(struct inode *inode,
				const struct address_space_operations *aops)
{
	inode->i_data.a_ops = aops;
}

// generic_file_read_iter wrapper

ssize_t rust_helper_generic_file_read_iter(struct kiocb *iocb,
					   struct iov_iter *to)
{
	return generic_file_read_iter(iocb, to);
}

// is_bad_inode wrapper

bool rust_helper_is_bad_inode(struct inode *inode)
{
	return is_bad_inode(inode);
}

// Mutex helpers

void rust_helper___mutex_init(struct mutex *lock, const char *name,
			      struct lock_class_key *key)
{
	__mutex_init(lock, name, key);
}

void rust_helper_mutex_lock(struct mutex *lock)
{
	mutex_lock(lock);
}

void rust_helper_mutex_unlock(struct mutex *lock)
{
	mutex_unlock(lock);
}

int rust_helper_mutex_trylock(struct mutex *lock)
{
	return mutex_trylock(lock);
}

bool rust_helper_mutex_is_locked(struct mutex *lock)
{
	return mutex_is_locked(lock);
}

// Spinlock helpers

void rust_helper___spin_lock_init(spinlock_t *lock, const char *name,
				  struct lock_class_key *key)
{
	spin_lock_init(lock);
	(void)name;
	(void)key;
}

void rust_helper_spin_lock(spinlock_t *lock)
{
	spin_lock(lock);
}

void rust_helper_spin_unlock(spinlock_t *lock)
{
	spin_unlock(lock);
}

int rust_helper_spin_trylock(spinlock_t *lock)
{
	return spin_trylock(lock);
}

int rust_helper_spin_is_locked(spinlock_t *lock)
{
	return spin_is_locked(lock);
}

// RCU helpers

void rust_helper_rcu_read_lock(void)
{
	rcu_read_lock();
}

void rust_helper_rcu_read_unlock(void)
{
	rcu_read_unlock();
}

// Lockdep helpers

void rust_helper_lockdep_register_key(struct lock_class_key *key)
{
	lockdep_register_key(key);
}

void rust_helper_lockdep_unregister_key(struct lock_class_key *key)
{
	lockdep_unregister_key(key);
}

// Waitqueue helpers

void rust_helper___init_waitqueue_head(struct wait_queue_head *wq_head,
				       const char *name,
				       struct lock_class_key *key)
{
	__init_waitqueue_head(wq_head, name, key);
}

void rust_helper___wake_up(struct wait_queue_head *wq_head,
			   unsigned int mode, int nr_exclusive, void *key)
{
	__wake_up(wq_head, mode, nr_exclusive, key);
}

// Task helpers

struct task_struct *rust_helper_get_current(void)
{
	return current;
}

void rust_helper_get_task_struct(struct task_struct *t)
{
	get_task_struct(t);
}

void rust_helper_put_task_struct(struct task_struct *t)
{
	put_task_struct(t);
}

int rust_helper_kthread_should_stop(void)
{
	return kthread_should_stop();
}

// Network helpers

void *rust_helper_get_net(void *net)
{
	return get_net((struct net *)net);
}

void rust_helper_put_net(void *net)
{
	put_net((struct net *)net);
}

void rust_helper_set_wq_entry_private(struct wait_queue_entry *wq, void *p)
{
	wq->private = p;
}

void *rust_helper_get_wq_entry_private(struct wait_queue_entry *wq)
{
	return wq->private;
}

// Workqueue helpers

void rust_helper_init_work_with_key(struct work_struct *work,
				    work_func_t func, bool onstack,
				    const char *name,
				    struct lock_class_key *key)
{
	__init_work(work, onstack);
	work->data = (atomic_long_t) WORK_DATA_INIT();
	lockdep_init_map(&work->lockdep_map, name, key, 0);
	INIT_LIST_HEAD(&work->entry);
	work->func = func;
}

// Schedule helper — schedule() is not inline but linux/sched.h is not
// traversed, so we provide a thin wrapper.

void rust_helper_schedule(void)
{
	schedule();
}


// init_waitqueue_func_entry — inline in linux/wait.h
void rust_helper_init_waitqueue_func_entry(struct wait_queue_entry *wq_entry,
                                           wait_queue_func_t func)
{
init_waitqueue_func_entry(wq_entry, func);
}

// bdev_nr_sectors — inline in linux/blkdev.h
unsigned long long rust_helper_bdev_nr_sectors(void *bdev)
{
	return bdev_nr_sectors((struct block_device *)bdev);
}

// sb_min_blocksize — inline in linux/buffer_head.h
#include <linux/buffer_head.h>
int rust_helper_sb_min_blocksize(struct super_block *sb, int size)
{
	return sb_min_blocksize(sb, size);
}

// sb_set_blocksize — inline in linux/buffer_head.h
int rust_helper_sb_set_blocksize(struct super_block *sb, int size)
{
	return sb_set_blocksize(sb, size);
}

// sb_bdev_mapping — get the block device's address_space from superblock
struct address_space *rust_helper_sb_bdev_mapping(struct super_block *sb)
{
	return sb->s_bdev->bd_mapping;
}

// iomap helpers — inline wrappers in iomap.h
#include <linux/iomap.h>

void rust_helper_iomap_bio_read_folio(struct folio *folio,
				      const struct iomap_ops *ops)
{
	iomap_bio_read_folio(folio, ops);
}

void rust_helper_iomap_bio_readahead(struct readahead_control *rac,
				     const struct iomap_ops *ops)
{
	iomap_bio_readahead(rac, ops);
}
