// SPDX-License-Identifier: GPL-2.0
//
// C helper wrappers for kernel functions that are macros or static inlines.
// These create real symbols that Rust can link against.
//
// The Rust FFI bindings for these functions are auto-generated by bnd-winmd
// from helpers.h.

// No helpers needed yet — krealloc_node_align_noprof and kfree are real
// exported symbols available via the rko.slab partition.
