//! Rust FFI bindings for Linux kernel-internal APIs.
//!
//! Generated by `rko-sys-gen` — do not edit `src/rko/` manually.
//! Hand-written modules: `printk`, `module`.

#![no_std]

pub mod rko;

pub mod module;
pub mod printk;
