//! Manual printk declarations for kernel logging.
//!
//! `_printk` is variadic and `KERN_*` are string-literal macros — neither
//! can be auto-generated by bnd-winmd. These match the kernel's own bindgen
//! output in `linux_bin/rust/bindings/bindings_generated.rs`.

unsafe extern "C" {
    /// Kernel printk implementation.
    ///
    /// This is the actual symbol exported by the kernel. The `printk` name
    /// in C is a macro that expands to `_printk`.
    pub safe fn _printk(fmt: *const core::ffi::c_char, ...) -> core::ffi::c_int;
}

/// ASCII Start Of Header — prefix byte used by all `KERN_*` level strings.
pub const KERN_SOH: &[u8; 2] = b"\x01\0";
pub const KERN_SOH_ASCII: u8 = b'\x01';

/// System is unusable (level 0).
pub const KERN_EMERG: &[u8; 3] = b"\x010\0";
/// Action must be taken immediately (level 1).
pub const KERN_ALERT: &[u8; 3] = b"\x011\0";
/// Critical conditions (level 2).
pub const KERN_CRIT: &[u8; 3] = b"\x012\0";
/// Error conditions (level 3).
pub const KERN_ERR: &[u8; 3] = b"\x013\0";
/// Warning conditions (level 4).
pub const KERN_WARNING: &[u8; 3] = b"\x014\0";
/// Normal but significant condition (level 5).
pub const KERN_NOTICE: &[u8; 3] = b"\x015\0";
/// Informational (level 6).
pub const KERN_INFO: &[u8; 3] = b"\x016\0";
/// Debug-level messages (level 7).
pub const KERN_DEBUG: &[u8; 3] = b"\x017\0";
/// Default kernel loglevel.
pub const KERN_DEFAULT: &[u8; 1] = b"\0";
/// Continuation of a previous log line.
pub const KERN_CONT: &[u8; 3] = b"\x01c\0";
