// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn __init_rwsem(sem : *mut rw_semaphore, name : *const i8, key : *mut super::fs:: lock_class_key));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __lockref_is_dead(l : *const lockref) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_read_constructor(_t : *mut rw_semaphore) -> *mut rw_semaphore);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_read_destructor(p : *mut *mut rw_semaphore));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_read_intr_constructor(_t : class_rwsem_read_t) -> class_rwsem_read_t);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_read_intr_destructor(p : *mut class_rwsem_read_t));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_read_intr_lock_err(_t : *mut class_rwsem_read_t) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_read_intr_lock_ptr(_t : *mut class_rwsem_read_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_read_lock_err(_t : *mut class_rwsem_read_t) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_read_lock_ptr(_t : *mut class_rwsem_read_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_read_try_constructor(_t : class_rwsem_read_t) -> class_rwsem_read_t);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_read_try_destructor(p : *mut class_rwsem_read_t));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_read_try_lock_err(_t : *mut class_rwsem_read_t) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_read_try_lock_ptr(_t : *mut class_rwsem_read_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_write_constructor(_t : *mut rw_semaphore) -> *mut rw_semaphore);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_write_destructor(p : *mut *mut rw_semaphore));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_write_kill_constructor(_t : class_rwsem_write_t) -> class_rwsem_write_t);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_write_kill_destructor(p : *mut class_rwsem_write_t));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_write_kill_lock_err(_t : *mut class_rwsem_write_t) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_write_kill_lock_ptr(_t : *mut class_rwsem_write_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_write_lock_err(_t : *mut class_rwsem_write_t) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_write_lock_ptr(_t : *mut class_rwsem_write_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_write_try_constructor(_t : class_rwsem_write_t) -> class_rwsem_write_t);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_write_try_destructor(p : *mut class_rwsem_write_t));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_write_try_lock_err(_t : *mut class_rwsem_write_t) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn class_rwsem_write_try_lock_ptr(_t : *mut class_rwsem_write_t) -> *mut core::ffi::c_void);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn down_read(sem : *mut rw_semaphore));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn down_read_interruptible(sem : *mut rw_semaphore) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn down_read_killable(sem : *mut rw_semaphore) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn down_read_trylock(sem : *mut rw_semaphore) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn down_write(sem : *mut rw_semaphore));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn down_write_killable(sem : *mut rw_semaphore) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn down_write_trylock(sem : *mut rw_semaphore) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn downgrade_write(sem : *mut rw_semaphore));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn lockref_get(lockref : *mut lockref));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn lockref_get_not_dead(lockref : *mut lockref) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn lockref_get_not_zero(lockref : *mut lockref) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn lockref_init(lockref : *mut lockref));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn lockref_mark_dead(lockref : *mut lockref));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn lockref_put_or_lock(lockref : *mut lockref) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn lockref_put_return(lockref : *mut lockref) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn osq_is_locked(lock : *mut optimistic_spin_queue) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn osq_lock(lock : *mut optimistic_spin_queue) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn osq_lock_init(lock : *mut optimistic_spin_queue));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn osq_unlock(lock : *mut optimistic_spin_queue));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn rwsem_assert_held(sem : *const rw_semaphore));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn rwsem_assert_held_nolockdep(sem : *const rw_semaphore));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn rwsem_assert_held_write(sem : *const rw_semaphore));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn rwsem_assert_held_write_nolockdep(sem : *const rw_semaphore));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn rwsem_is_contended(sem : *mut rw_semaphore) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn rwsem_is_locked(sem : *mut rw_semaphore) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn up_read(sem : *mut rw_semaphore));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn up_write(sem : *mut rw_semaphore));
pub const RWSEM_UNLOCKED_VALUE: i32 = 0i32;
pub const SPINLOCK_MAGIC: i32 = -559067475i32;
pub const _Q_LOCKED_BITS: i32 = 8i32;
pub const _Q_LOCKED_OFFSET: i32 = 0i32;
pub const _Q_PENDING_BITS: i32 = 8i32;
pub const _Q_TAIL_IDX_BITS: i32 = 2i32;
#[repr(C)]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct arch_spinlock_t {
    pub Value: qspinlock,
}
#[cfg(feature = "types")]
impl Default for arch_spinlock_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type class_rwsem_read_intr_t = class_rwsem_read_t;
pub type class_rwsem_read_t = *mut rw_semaphore;
pub type class_rwsem_read_try_t = class_rwsem_read_t;
pub type class_rwsem_write_kill_t = class_rwsem_write_t;
pub type class_rwsem_write_t = *mut rw_semaphore;
pub type class_rwsem_write_try_t = class_rwsem_write_t;
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct lockref {
    pub lockref__anon_0: lockref__anon_0,
}
#[cfg(feature = "types")]
impl Default for lockref {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union lockref__anon_0 {
    pub lockref__anon_0__anon_0: lockref__anon_0__anon_0,
}
#[cfg(feature = "types")]
impl Default for lockref__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct lockref__anon_0__anon_0 {
    pub lock: spinlock_t,
    pub count: i32,
}
#[cfg(feature = "types")]
impl Default for lockref__anon_0__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct mutex {
    pub owner: super::types::atomic64_t,
    pub wait_lock: raw_spinlock_t,
    pub osq: optimistic_spin_queue,
    pub wait_list: super::types::list_head,
}
#[cfg(feature = "types")]
impl Default for mutex {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct optimistic_spin_queue {
    pub tail: super::types::atomic_t,
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct qspinlock {
    pub qspinlock__anon_0: qspinlock__anon_0,
}
#[cfg(feature = "types")]
impl Default for qspinlock {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union qspinlock__anon_0 {
    pub val: super::types::atomic_t,
    pub qspinlock__anon_0__anon_0: qspinlock__anon_0__anon_0,
    pub qspinlock__anon_0__anon_1: qspinlock__anon_0__anon_1,
}
#[cfg(feature = "types")]
impl Default for qspinlock__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(2))]
#[derive(Clone, Copy, Default)]
pub struct qspinlock__anon_0__anon_0 {
    pub tail: u16,
    pub locked_pending: u16,
}
#[repr(C, packed(1))]
#[derive(Clone, Copy)]
pub struct qspinlock__anon_0__anon_1 {
    pub reserved: [u8; 2],
    pub pending: u8,
    pub locked: u8,
}
impl Default for qspinlock__anon_0__anon_1 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct raw_spinlock {
    pub raw_lock: arch_spinlock_t,
}
#[cfg(feature = "types")]
impl Default for raw_spinlock {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C)]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct raw_spinlock_t {
    pub Value: raw_spinlock,
}
#[cfg(feature = "types")]
impl Default for raw_spinlock_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct refcount_struct {
    pub refs: super::types::atomic_t,
}
#[repr(C)]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct refcount_t {
    pub Value: refcount_struct,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct rw_semaphore {
    pub count: super::types::atomic64_t,
    pub owner: super::types::atomic64_t,
    pub osq: optimistic_spin_queue,
    pub wait_lock: raw_spinlock_t,
    pub wait_list: super::types::list_head,
}
#[cfg(feature = "types")]
impl Default for rw_semaphore {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct spinlock {
    pub spinlock__anon_0: spinlock__anon_0,
}
#[cfg(feature = "types")]
impl Default for spinlock {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union spinlock__anon_0 {
    pub rlock: raw_spinlock,
}
#[cfg(feature = "types")]
impl Default for spinlock__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C)]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct spinlock_t {
    pub Value: spinlock,
}
#[cfg(feature = "types")]
impl Default for spinlock_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
