// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __cmsg_nxthdr(__ctl : *mut core::ffi::c_void, __size : super::types:: __kernel_size_t, __cmsg : *mut cmsghdr) -> *mut cmsghdr);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __copy_msghdr(kmsg : *mut msghdr, umsg : *mut user_msghdr, save_addr : *mut *mut sockaddr) -> i32);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __import_iovec(r#type : i32, uvec : *const iovec, nr_segs : u32, fast_segs : u32, iovp : *mut *mut iovec, i : *mut iov_iter, compat : bool) -> super::types:: ssize_t);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __sock_create(net : *mut core::ffi::c_void, family : i32, r#type : i32, proto : i32, res : *mut *mut socket, kern : i32) -> i32);
windows_link::link!("kernel" "C" fn __sys_accept4(fd : i32, upeer_sockaddr : *mut sockaddr, upeer_addrlen : *mut i32, flags : i32) -> i32);
windows_link::link!("kernel" "C" fn __sys_bind(fd : i32, umyaddr : *mut sockaddr, addrlen : i32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __sys_bind_socket(sock : *mut socket, address : *mut __kernel_sockaddr_storage, addrlen : i32) -> i32);
windows_link::link!("kernel" "C" fn __sys_connect(fd : i32, uservaddr : *mut sockaddr, addrlen : i32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __sys_connect_file(file : *mut super::fs:: file, addr : *mut __kernel_sockaddr_storage, addrlen : i32, file_flags : i32) -> i32);
windows_link::link!("kernel" "C" fn __sys_getsockname(fd : i32, usockaddr : *mut sockaddr, usockaddr_len : *mut i32, peer : i32) -> i32);
windows_link::link!("kernel" "C" fn __sys_listen(fd : i32, backlog : i32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __sys_listen_socket(sock : *mut socket, backlog : i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __sys_recvfrom(fd : i32, ubuf : *mut core::ffi::c_void, size : super::types:: size_t, flags : u32, addr : *mut sockaddr, addr_len : *mut i32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __sys_recvmmsg(fd : i32, mmsg : *mut mmsghdr, vlen : u32, flags : u32, timeout : *mut __kernel_timespec, timeout32 : *mut old_timespec32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __sys_recvmsg(fd : i32, msg : *mut user_msghdr, flags : u32, forbid_cmsg_compat : bool) -> i64);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __sys_recvmsg_sock(sock : *mut socket, msg : *mut msghdr, umsg : *mut user_msghdr, uaddr : *mut sockaddr, flags : u32) -> i64);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __sys_sendmmsg(fd : i32, mmsg : *mut mmsghdr, vlen : u32, flags : u32, forbid_cmsg_compat : bool) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __sys_sendmsg(fd : i32, msg : *mut user_msghdr, flags : u32, forbid_cmsg_compat : bool) -> i64);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __sys_sendmsg_sock(sock : *mut socket, msg : *mut msghdr, flags : u32) -> i64);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn __sys_sendto(fd : i32, buff : *mut core::ffi::c_void, len : super::types:: size_t, flags : u32, addr : *mut sockaddr, addr_len : i32) -> i32);
windows_link::link!("kernel" "C" fn __sys_shutdown(fd : i32, how : i32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __sys_shutdown_sock(sock : *mut socket, how : i32) -> i32);
windows_link::link!("kernel" "C" fn __sys_socket(family : i32, r#type : i32, protocol : i32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __sys_socket_file(family : i32, r#type : i32, protocol : i32) -> *mut super::fs:: file);
windows_link::link!("kernel" "C" fn __sys_socketpair(family : i32, r#type : i32, protocol : i32, usockvec : *mut i32) -> i32);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn _copy_from_iter(addr : *mut core::ffi::c_void, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn _copy_from_iter_flushcache(addr : *mut core::ffi::c_void, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn _copy_from_iter_nocache(addr : *mut core::ffi::c_void, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn _copy_mc_to_iter(addr : *const core::ffi::c_void, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn _copy_to_iter(addr : *const core::ffi::c_void, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn cmsg_nxthdr(__msg : *mut msghdr, __cmsg : *mut cmsghdr) -> *mut cmsghdr);
#[cfg(all(
    feature = "ds",
    feature = "mm_types",
    feature = "sync",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn copy_folio_from_iter(folio : *mut super::mm_types:: folio, offset : super::types:: size_t, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(
    feature = "ds",
    feature = "mm_types",
    feature = "sync",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn copy_folio_from_iter_atomic(folio : *mut super::mm_types:: folio, offset : super::types:: size_t, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(
    feature = "ds",
    feature = "mm_types",
    feature = "sync",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn copy_folio_to_iter(folio : *mut super::mm_types:: folio, offset : super::types:: size_t, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn copy_from_iter(addr : *mut core::ffi::c_void, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn copy_from_iter_full(addr : *mut core::ffi::c_void, bytes : super::types:: size_t, i : *mut iov_iter) -> bool);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn copy_from_iter_full_nocache(addr : *mut core::ffi::c_void, bytes : super::types:: size_t, i : *mut iov_iter) -> bool);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn copy_from_iter_nocache(addr : *mut core::ffi::c_void, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(
    feature = "ds",
    feature = "mm_types",
    feature = "sync",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn copy_page_from_iter(page : *mut super::mm_types:: page, offset : super::types:: size_t, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(
    feature = "ds",
    feature = "mm_types",
    feature = "sync",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn copy_page_to_iter(page : *mut super::mm_types:: page, offset : super::types:: size_t, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(
    feature = "ds",
    feature = "mm_types",
    feature = "sync",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn copy_page_to_iter_nofault(page : *mut super::mm_types:: page, offset : u32, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn copy_to_iter(addr : *const core::ffi::c_void, bytes : super::types:: size_t, i : *mut iov_iter) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn copy_to_iter_full(addr : *const core::ffi::c_void, bytes : super::types:: size_t, i : *mut iov_iter) -> bool);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn do_accept(file : *mut super::fs:: file, arg : *mut core::ffi::c_void, upeer_sockaddr : *mut sockaddr, upeer_addrlen : *mut i32, flags : i32) -> *mut super::fs:: file);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn do_getsockname(sock : *mut socket, peer : i32, usockaddr : *mut sockaddr, usockaddr_len : *mut i32) -> i32);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn dup_iter(new : *mut iov_iter, old : *mut iov_iter, flags : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn extract_iter_to_sg(iter : *mut iov_iter, len : super::types:: size_t, sgtable : *mut core::ffi::c_void, sg_max : u32, extraction_flags : iov_iter_extraction_t) -> super::types:: ssize_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn fault_in_iov_iter_readable(i : *const iov_iter, bytes : super::types:: size_t) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn fault_in_iov_iter_writeable(i : *const iov_iter, bytes : super::types:: size_t) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn import_iovec(r#type : i32, uvec : *const iovec, nr_segs : u32, fast_segs : u32, iovp : *mut *mut iovec, i : *mut iov_iter) -> super::types:: ssize_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn import_ubuf(r#type : i32, buf : *mut core::ffi::c_void, len : super::types:: size_t, i : *mut iov_iter) -> i32);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_advance(i : *mut iov_iter, bytes : super::types:: size_t));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_alignment(i : *const iov_iter) -> u64);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_bvec(i : *mut iov_iter, direction : u32, bvec : *const core::ffi::c_void, nr_segs : u64, count : super::types:: size_t));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_count(i : *const iov_iter) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_discard(i : *mut iov_iter, direction : u32, count : super::types:: size_t));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_extract_bvecs(iter : *mut iov_iter, bv : *mut core::ffi::c_void, max_size : super::types:: size_t, nr_vecs : *mut u16, max_vecs : u16, extraction_flags : iov_iter_extraction_t) -> super::types:: ssize_t);
#[cfg(all(
    feature = "ds",
    feature = "mm_types",
    feature = "sync",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn iov_iter_extract_pages(i : *mut iov_iter, pages : *mut *mut *mut super::mm_types:: page, maxsize : super::types:: size_t, maxpages : u32, extraction_flags : iov_iter_extraction_t, offset0 : *mut super::types:: size_t) -> super::types:: ssize_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_extract_will_pin(iter : *const iov_iter) -> bool);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_folio_queue(i : *mut iov_iter, direction : u32, folioq : *const core::ffi::c_void, first_slot : u32, offset : u32, count : super::types:: size_t));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_gap_alignment(i : *const iov_iter) -> u64);
#[cfg(all(
    feature = "ds",
    feature = "mm_types",
    feature = "sync",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn iov_iter_get_pages2(i : *mut iov_iter, pages : *mut *mut super::mm_types:: page, maxsize : super::types:: size_t, maxpages : u32, start : *mut super::types:: size_t) -> super::types:: ssize_t);
#[cfg(all(
    feature = "ds",
    feature = "mm_types",
    feature = "sync",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn iov_iter_get_pages_alloc2(i : *mut iov_iter, pages : *mut *mut *mut super::mm_types:: page, maxsize : super::types:: size_t, start : *mut super::types:: size_t) -> super::types:: ssize_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_init(i : *mut iov_iter, direction : u32, iov : *const iovec, nr_segs : u64, count : super::types:: size_t));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_is_bvec(i : *const iov_iter) -> bool);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_is_discard(i : *const iov_iter) -> bool);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_is_folioq(i : *const iov_iter) -> bool);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_is_kvec(i : *const iov_iter) -> bool);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_is_xarray(i : *const iov_iter) -> bool);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_kvec(i : *mut iov_iter, direction : u32, kvec : *const kvec, nr_segs : u64, count : super::types:: size_t));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_npages(i : *const iov_iter, maxpages : i32) -> i32);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_npages_cap(i : *mut iov_iter, maxpages : i32, max_bytes : super::types:: size_t) -> i32);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_reexpand(i : *mut iov_iter, count : super::types:: size_t));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_restore(i : *mut iov_iter, state : *mut iov_iter_state));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_revert(i : *mut iov_iter, bytes : super::types:: size_t));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_rw(i : *const iov_iter) -> u8);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_save_state(iter : *mut iov_iter, state : *mut iov_iter_state));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_single_seg_count(i : *const iov_iter) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_truncate(i : *mut iov_iter, count : u64));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_type(i : *const iov_iter) -> iter_type);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_ubuf(i : *mut iov_iter, direction : u32, buf : *mut core::ffi::c_void, count : super::types:: size_t));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_xarray(i : *mut iov_iter, direction : u32, xarray : *mut super::ds:: xarray, start : super::types:: loff_t, count : super::types:: size_t));
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iov_iter_zero(bytes : super::types:: size_t, param1 : *mut iov_iter) -> super::types:: size_t);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn iov_length(iov : *const iovec, nr_segs : u64) -> super::types:: size_t);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn iovec_from_user(uvector : *const iovec, nr_segs : u64, fast_segs : u64, fast_iov : *mut iovec, compat : bool) -> *mut iovec);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iter_iov(iter : *const iov_iter) -> *mut iovec);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iter_iov_len(i : *const iov_iter) -> super::types:: size_t);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iter_is_iovec(i : *const iov_iter) -> bool);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn iter_is_ubuf(i : *const iov_iter) -> bool);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn kernel_accept(sock : *mut socket, newsock : *mut *mut socket, flags : i32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn kernel_bind(sock : *mut socket, addr : *mut sockaddr_unsized, addrlen : i32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn kernel_connect(sock : *mut socket, addr : *mut sockaddr_unsized, addrlen : i32, flags : i32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn kernel_getpeername(sock : *mut socket, addr : *mut sockaddr) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn kernel_getsockname(sock : *mut socket, addr : *mut sockaddr) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn kernel_listen(sock : *mut socket, backlog : i32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn kernel_recvmsg(sock : *mut socket, msg : *mut msghdr, vec : *mut kvec, num : super::types:: size_t, len : super::types:: size_t, flags : i32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn kernel_sendmsg(sock : *mut socket, msg : *mut msghdr, vec : *mut kvec, num : super::types:: size_t, len : super::types:: size_t) -> i32);
windows_link::link!("kernel" "C" fn kernel_sock_ip_overhead(sk : *mut core::ffi::c_void) -> u32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn kernel_sock_shutdown(sock : *mut socket, how : sock_shutdown_cmd) -> i32);
windows_link::link!("kernel" "C" fn move_addr_to_kernel(uaddr : *mut core::ffi::c_void, ulen : i32, kaddr : *mut __kernel_sockaddr_storage) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn msg_data_left(msg : *const msghdr) -> super::types:: size_t);
windows_link::link!("kernel" "C" fn net_ratelimit() -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn put_cmsg(param0 : *mut msghdr, level : i32, r#type : i32, len : i32, data : *mut core::ffi::c_void) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn put_cmsg_notrunc(msg : *mut msghdr, level : i32, r#type : i32, len : i32, data : *mut core::ffi::c_void) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn put_cmsg_scm_timestamping(msg : *mut msghdr, tss : *mut scm_timestamping_internal));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn put_cmsg_scm_timestamping64(msg : *mut msghdr, tss : *mut scm_timestamping_internal));
#[cfg(all(feature = "ds", feature = "mm_types", feature = "types"))]
windows_link::link!("kernel" "C" fn sendpage_ok(page : *mut super::mm_types:: page) -> bool);
#[cfg(all(feature = "ds", feature = "mm_types", feature = "types"))]
windows_link::link!("kernel" "C" fn sendpages_ok(page : *mut super::mm_types:: page, len : super::types:: size_t, offset : super::types:: size_t) -> bool);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn sock_alloc() -> *mut socket);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn sock_alloc_file(sock : *mut socket, flags : i32, dname : *const i8) -> *mut super::fs:: file);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn sock_create(family : i32, r#type : i32, proto : i32, res : *mut *mut socket) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn sock_create_kern(net : *mut core::ffi::c_void, family : i32, r#type : i32, proto : i32, res : *mut *mut socket) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn sock_create_lite(family : i32, r#type : i32, proto : i32, res : *mut *mut socket) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn sock_from_file(file : *mut super::fs:: file) -> *mut socket);
windows_link::link!("kernel" "C" fn sock_is_registered(family : i32) -> bool);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn sock_recvmsg(sock : *mut socket, msg : *mut msghdr, flags : i32) -> i32);
windows_link::link!("kernel" "C" fn sock_register(fam : *const net_proto_family) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn sock_release(sock : *mut socket));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn sock_sendmsg(sock : *mut socket, msg : *mut msghdr) -> i32);
windows_link::link!("kernel" "C" fn sock_unregister(family : i32));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn sock_wake_async(sk_wq : *mut socket_wq, how : i32, band : i32) -> i32);
windows_link::link!("kernel" "C" fn socket_seq_show(seq : *mut core::ffi::c_void));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn sockfd_lookup(fd : i32, err : *mut i32) -> *mut socket);
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn user_backed_iter(i : *const iov_iter) -> bool);
pub const AF_ALG: i32 = 38i32;
pub const AF_APPLETALK: i32 = 5i32;
pub const AF_ASH: i32 = 18i32;
pub const AF_ATMPVC: i32 = 8i32;
pub const AF_ATMSVC: i32 = 20i32;
pub const AF_AX25: i32 = 3i32;
pub const AF_BLUETOOTH: i32 = 31i32;
pub const AF_BRIDGE: i32 = 7i32;
pub const AF_CAIF: i32 = 37i32;
pub const AF_CAN: i32 = 29i32;
pub const AF_DECnet: i32 = 12i32;
pub const AF_ECONET: i32 = 19i32;
pub const AF_IB: i32 = 27i32;
pub const AF_IEEE802154: i32 = 36i32;
pub const AF_INET: i32 = 2i32;
pub const AF_INET6: i32 = 10i32;
pub const AF_IPX: i32 = 4i32;
pub const AF_IRDA: i32 = 23i32;
pub const AF_ISDN: i32 = 34i32;
pub const AF_IUCV: i32 = 32i32;
pub const AF_KCM: i32 = 41i32;
pub const AF_KEY: i32 = 15i32;
pub const AF_LLC: i32 = 26i32;
pub const AF_LOCAL: i32 = 1i32;
pub const AF_MAX: i32 = 46i32;
pub const AF_MCTP: i32 = 45i32;
pub const AF_MPLS: i32 = 28i32;
pub const AF_NETBEUI: i32 = 13i32;
pub const AF_NETLINK: i32 = 16i32;
pub const AF_NETROM: i32 = 6i32;
pub const AF_NFC: i32 = 39i32;
pub const AF_PACKET: i32 = 17i32;
pub const AF_PHONET: i32 = 35i32;
pub const AF_PPPOX: i32 = 24i32;
pub const AF_QIPCRTR: i32 = 42i32;
pub const AF_RDS: i32 = 21i32;
pub const AF_ROSE: i32 = 11i32;
pub const AF_RXRPC: i32 = 33i32;
pub const AF_SECURITY: i32 = 14i32;
pub const AF_SMC: i32 = 43i32;
pub const AF_SNA: i32 = 22i32;
pub const AF_TIPC: i32 = 30i32;
pub const AF_UNIX: i32 = 1i32;
pub const AF_UNSPEC: i32 = 0i32;
pub const AF_VSOCK: i32 = 40i32;
pub const AF_WANPIPE: i32 = 25i32;
pub const AF_X25: i32 = 9i32;
pub const AF_XDP: i32 = 44i32;
pub const IPX_TYPE: i32 = 1i32;
pub const ITER_BVEC: u32 = 2u32;
pub const ITER_DEST: i32 = 0i32;
pub const ITER_DISCARD: u32 = 6u32;
pub const ITER_FOLIOQ: u32 = 4u32;
pub const ITER_IOVEC: u32 = 1u32;
pub const ITER_KVEC: u32 = 3u32;
pub const ITER_SOURCE: i32 = 1i32;
pub const ITER_UBUF: u32 = 0u32;
pub const ITER_XARRAY: u32 = 5u32;
pub const MSG_BATCH: i32 = 262144i32;
pub const MSG_CMSG_CLOEXEC: i32 = 1073741824i32;
pub const MSG_CMSG_COMPAT: i32 = 0i32;
pub const MSG_CONFIRM: i32 = 2048i32;
pub const MSG_CTRUNC: i32 = 8i32;
pub const MSG_DONTROUTE: i32 = 4i32;
pub const MSG_DONTWAIT: i32 = 64i32;
pub const MSG_EOR: i32 = 128i32;
pub const MSG_ERRQUEUE: i32 = 8192i32;
pub const MSG_FASTOPEN: i32 = 536870912i32;
pub const MSG_FIN: i32 = 512i32;
pub const MSG_MORE: i32 = 32768i32;
pub const MSG_NOSIGNAL: i32 = 16384i32;
pub const MSG_NO_SHARED_FRAGS: i32 = 524288i32;
pub const MSG_OOB: i32 = 1i32;
pub const MSG_PEEK: i32 = 2i32;
pub const MSG_PROBE: i32 = 16i32;
pub const MSG_RST: i32 = 4096i32;
pub const MSG_SENDPAGE_DECRYPTED: i32 = 1048576i32;
pub const MSG_SENDPAGE_NOPOLICY: i32 = 65536i32;
pub const MSG_SOCK_DEVMEM: i32 = 33554432i32;
pub const MSG_SPLICE_PAGES: i32 = 134217728i32;
pub const MSG_SYN: i32 = 1024i32;
pub const MSG_TRUNC: i32 = 32i32;
pub const MSG_TRYHARD: i32 = 4i32;
pub const MSG_WAITALL: i32 = 256i32;
pub const MSG_WAITFORONE: i32 = 65536i32;
pub const MSG_ZEROCOPY: i32 = 67108864i32;
pub const SCM_CREDENTIALS: i32 = 2i32;
pub const SCM_PIDFD: i32 = 4i32;
pub const SCM_RIGHTS: i32 = 1i32;
pub const SCM_SECURITY: i32 = 3i32;
pub const SHUT_RD: u32 = 0u32;
pub const SHUT_RDWR: u32 = 2u32;
pub const SHUT_WR: u32 = 1u32;
pub const SOCKWQ_ASYNC_NOSPACE: u32 = 0u32;
pub const SOCKWQ_ASYNC_WAITDATA: u32 = 1u32;
pub const SOCK_CUSTOM_SOCKOPT: u32 = 4u32;
pub const SOCK_DCCP: u32 = 6u32;
pub const SOCK_DGRAM: u32 = 2u32;
pub const SOCK_NOSPACE: u32 = 2u32;
pub const SOCK_PACKET: u32 = 10u32;
pub const SOCK_RAW: u32 = 3u32;
pub const SOCK_RCVBUF_LOCK: i32 = 2i32;
pub const SOCK_RDM: u32 = 4u32;
pub const SOCK_SEQPACKET: u32 = 5u32;
pub const SOCK_SNDBUF_LOCK: i32 = 1i32;
pub const SOCK_STREAM: u32 = 1u32;
pub const SOCK_SUPPORT_ZC: u32 = 3u32;
pub const SOCK_TXREHASH_DEFAULT: i32 = 255i32;
pub const SOCK_TXREHASH_DISABLED: i32 = 0i32;
pub const SOCK_TXREHASH_ENABLED: i32 = 1i32;
pub const SOCK_TYPE_MASK: i32 = 15i32;
pub const SOCK_WAKE_IO: u32 = 0u32;
pub const SOCK_WAKE_SPACE: u32 = 2u32;
pub const SOCK_WAKE_URG: u32 = 3u32;
pub const SOCK_WAKE_WAITD: u32 = 1u32;
pub const SOL_AAL: i32 = 265i32;
pub const SOL_ALG: i32 = 279i32;
pub const SOL_ATALK: i32 = 258i32;
pub const SOL_ATM: i32 = 264i32;
pub const SOL_AX25: i32 = 257i32;
pub const SOL_BLUETOOTH: i32 = 274i32;
pub const SOL_CAIF: i32 = 278i32;
pub const SOL_DCCP: i32 = 269i32;
pub const SOL_DECNET: i32 = 261i32;
pub const SOL_ICMPV6: i32 = 58i32;
pub const SOL_IP: i32 = 0i32;
pub const SOL_IPV6: i32 = 41i32;
pub const SOL_IPX: i32 = 256i32;
pub const SOL_IRDA: i32 = 266i32;
pub const SOL_IUCV: i32 = 277i32;
pub const SOL_KCM: i32 = 281i32;
pub const SOL_LLC: i32 = 268i32;
pub const SOL_MCTP: i32 = 285i32;
pub const SOL_MPTCP: i32 = 284i32;
pub const SOL_NETBEUI: i32 = 267i32;
pub const SOL_NETLINK: i32 = 270i32;
pub const SOL_NETROM: i32 = 259i32;
pub const SOL_NFC: i32 = 280i32;
pub const SOL_PACKET: i32 = 263i32;
pub const SOL_PNPIPE: i32 = 275i32;
pub const SOL_PPPOL2TP: i32 = 273i32;
pub const SOL_RAW: i32 = 255i32;
pub const SOL_RDS: i32 = 276i32;
pub const SOL_ROSE: i32 = 260i32;
pub const SOL_RXRPC: i32 = 272i32;
pub const SOL_SCTP: i32 = 132i32;
pub const SOL_SMC: i32 = 286i32;
pub const SOL_TCP: i32 = 6i32;
pub const SOL_TIPC: i32 = 271i32;
pub const SOL_TLS: i32 = 282i32;
pub const SOL_UDP: i32 = 17i32;
pub const SOL_UDPLITE: i32 = 136i32;
pub const SOL_VSOCK: i32 = 287i32;
pub const SOL_X25: i32 = 262i32;
pub const SOL_XDP: i32 = 283i32;
pub const SOMAXCONN: i32 = 4096i32;
pub const SS_CONNECTED: u32 = 3u32;
pub const SS_CONNECTING: u32 = 2u32;
pub const SS_DISCONNECTING: u32 = 4u32;
pub const SS_FREE: u32 = 0u32;
pub const SS_UNCONNECTED: u32 = 1u32;
pub const SYS_ACCEPT: i32 = 5i32;
pub const SYS_ACCEPT4: i32 = 18i32;
pub const SYS_BIND: i32 = 2i32;
pub const SYS_CONNECT: i32 = 3i32;
pub const SYS_GETPEERNAME: i32 = 7i32;
pub const SYS_GETSOCKNAME: i32 = 6i32;
pub const SYS_GETSOCKOPT: i32 = 15i32;
pub const SYS_LISTEN: i32 = 4i32;
pub const SYS_RECV: i32 = 10i32;
pub const SYS_RECVFROM: i32 = 12i32;
pub const SYS_RECVMMSG: i32 = 19i32;
pub const SYS_RECVMSG: i32 = 17i32;
pub const SYS_SEND: i32 = 9i32;
pub const SYS_SENDMMSG: i32 = 20i32;
pub const SYS_SENDMSG: i32 = 16i32;
pub const SYS_SENDTO: i32 = 11i32;
pub const SYS_SETSOCKOPT: i32 = 14i32;
pub const SYS_SHUTDOWN: i32 = 13i32;
pub const SYS_SOCKET: i32 = 1i32;
pub const SYS_SOCKETPAIR: i32 = 8i32;
pub const UIO_FASTIOV: i32 = 8i32;
pub const UIO_MAXIOV: i32 = 1024i32;
pub const _K_SS_MAXSIZE: i32 = 128i32;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct __kernel_itimerspec {
    pub it_interval: __kernel_timespec,
    pub it_value: __kernel_timespec,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct __kernel_old_itimerval {
    pub it_interval: __kernel_old_timeval,
    pub it_value: __kernel_old_timeval,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct __kernel_old_timespec {
    pub tv_sec: super::types::__kernel_old_time_t,
    pub tv_nsec: i64,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct __kernel_old_timeval {
    pub tv_sec: super::types::__kernel_long_t,
    pub tv_usec: super::types::__kernel_long_t,
}
pub type __kernel_sa_family_t = u16;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct __kernel_sock_timeval {
    pub tv_sec: super::types::__s64,
    pub tv_usec: super::types::__s64,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct __kernel_sockaddr_storage {
    pub __kernel_sockaddr_storage__anon_0: __kernel_sockaddr_storage__anon_0,
}
impl Default for __kernel_sockaddr_storage {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union __kernel_sockaddr_storage__anon_0 {
    pub __kernel_sockaddr_storage__anon_0__anon_0: __kernel_sockaddr_storage__anon_0__anon_0,
    pub __align: *mut core::ffi::c_void,
}
impl Default for __kernel_sockaddr_storage__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(2))]
#[derive(Clone, Copy)]
pub struct __kernel_sockaddr_storage__anon_0__anon_0 {
    pub ss_family: __kernel_sa_family_t,
    pub __data: [i8; 126],
}
impl Default for __kernel_sockaddr_storage__anon_0__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct __kernel_timespec {
    pub tv_sec: super::types::__kernel_time64_t,
    pub tv_nsec: i64,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct cmsghdr {
    pub cmsg_len: super::types::__kernel_size_t,
    pub cmsg_level: i32,
    pub cmsg_type: i32,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct dmabuf_cmsg {
    pub frag_offset: super::types::__u64,
    pub frag_size: super::types::__u32,
    pub frag_token: super::types::__u32,
    pub dmabuf_id: super::types::__u32,
    pub flags: super::types::__u32,
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct dmabuf_token {
    pub token_start: super::types::__u32,
    pub token_count: super::types::__u32,
}
#[repr(C, packed(8))]
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct iov_iter {
    pub iter_type: u8,
    pub nofault: bool,
    pub data_source: bool,
    pub iov_offset: super::types::size_t,
    pub iov_iter__anon_0: iov_iter__anon_0,
    pub iov_iter__anon_1: iov_iter__anon_1,
}
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
impl Default for iov_iter {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub union iov_iter__anon_0 {
    pub __ubuf_iovec: iovec,
    pub iov_iter__anon_0__anon_0: iov_iter__anon_0__anon_0,
}
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
impl Default for iov_iter__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct iov_iter__anon_0__anon_0 {
    pub iov_iter__anon_0__anon_0__anon_0: iov_iter__anon_0__anon_0__anon_0,
    pub count: super::types::size_t,
}
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
impl Default for iov_iter__anon_0__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub union iov_iter__anon_0__anon_0__anon_0 {
    pub __iov: *mut iovec,
    pub kvec: *mut kvec,
    pub bvec: *mut core::ffi::c_void,
    pub folioq: *mut core::ffi::c_void,
    pub xarray: *mut super::ds::xarray,
    pub ubuf: *mut core::ffi::c_void,
}
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
impl Default for iov_iter__anon_0__anon_0__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union iov_iter__anon_1 {
    pub nr_segs: u64,
    pub folioq_slot: u8,
    pub xarray_start: super::types::loff_t,
}
#[cfg(feature = "types")]
impl Default for iov_iter__anon_1 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type iov_iter_extraction_t = u32;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct iov_iter_state {
    pub iov_offset: super::types::size_t,
    pub count: super::types::size_t,
    pub nr_segs: u64,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct iovec {
    pub iov_base: *mut core::ffi::c_void,
    pub iov_len: super::types::__kernel_size_t,
}
#[cfg(feature = "types")]
impl Default for iovec {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type iter_type = u32;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct kvec {
    pub iov_base: *mut core::ffi::c_void,
    pub iov_len: super::types::size_t,
}
#[cfg(feature = "types")]
impl Default for kvec {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct linger {
    pub l_onoff: i32,
    pub l_linger: i32,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct mmsghdr {
    pub msg_hdr: user_msghdr,
    pub msg_len: u32,
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct msghdr {
    pub msg_name: *mut core::ffi::c_void,
    pub msg_namelen: i32,
    pub msg_inq: i32,
    pub msg_iter: iov_iter,
    pub msghdr__anon_0: msghdr__anon_0,
    pub _bitfield_0: u8,
    pub msg_flags: u32,
    pub msg_controllen: super::types::__kernel_size_t,
    pub msg_iocb: *mut super::fs::kiocb,
    pub msg_ubuf: *mut core::ffi::c_void,
    pub sg_from_iter: *mut isize,
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for msghdr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union msghdr__anon_0 {
    pub msg_control: *mut core::ffi::c_void,
    pub msg_control_user: *mut core::ffi::c_void,
}
impl Default for msghdr__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct net_proto_family {
    pub family: i32,
    pub create: *mut isize,
    pub owner: *mut core::ffi::c_void,
}
impl Default for net_proto_family {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type old_time32_t = i32;
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct old_timespec32 {
    pub tv_sec: old_time32_t,
    pub tv_nsec: i32,
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct old_timeval32 {
    pub tv_sec: old_time32_t,
    pub tv_usec: i32,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct proto_ops {
    pub family: i32,
    pub owner: *mut core::ffi::c_void,
    pub release: *mut isize,
    pub bind: *mut isize,
    pub connect: *mut isize,
    pub socketpair: *mut isize,
    pub accept: *mut isize,
    pub getname: *mut isize,
    pub poll: *mut isize,
    pub ioctl: *mut isize,
    pub gettstamp: *mut isize,
    pub listen: *mut isize,
    pub shutdown: *mut isize,
    pub setsockopt: *mut isize,
    pub getsockopt: *mut isize,
    pub show_fdinfo: *mut isize,
    pub sendmsg: *mut isize,
    pub recvmsg: *mut isize,
    pub mmap: *mut isize,
    pub splice_read: *mut isize,
    pub splice_eof: *mut isize,
    pub set_peek_off: *mut isize,
    pub peek_len: *mut isize,
    pub read_sock: *mut isize,
    pub read_skb: *mut isize,
    pub sendmsg_locked: *mut isize,
    pub set_rcvlowat: *mut isize,
}
impl Default for proto_ops {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct read_descriptor_t {
    pub written: super::types::size_t,
    pub count: super::types::size_t,
    pub arg: read_descriptor_t_arg,
    pub error: i32,
}
#[cfg(feature = "types")]
impl Default for read_descriptor_t {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union read_descriptor_t_arg {
    pub buf: *mut i8,
    pub data: *mut core::ffi::c_void,
}
impl Default for read_descriptor_t_arg {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type sa_family_t = __kernel_sa_family_t;
#[repr(C, packed(8))]
#[cfg(all(feature = "fs", feature = "types"))]
#[derive(Clone, Copy)]
pub struct scm_timestamping_internal {
    pub ts: [super::fs::timespec64; 3],
}
#[cfg(all(feature = "fs", feature = "types"))]
impl Default for scm_timestamping_internal {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[cfg(feature = "types")]
pub type sk_read_actor_t = Option<
    unsafe extern "system" fn(
        param0: *const read_descriptor_t,
        param1: *const core::ffi::c_void,
        param2: u32,
        param3: super::types::size_t,
    ) -> i32,
>;
pub type skb_read_actor_t = Option<
    unsafe extern "system" fn(
        param0: *const core::ffi::c_void,
        param1: *const core::ffi::c_void,
    ) -> i32,
>;
pub type sock_shutdown_cmd = u32;
pub type sock_type = u32;
#[repr(C, packed(2))]
#[derive(Clone, Copy)]
pub struct sockaddr {
    pub sa_family: sa_family_t,
    pub sa_data: [i8; 14],
}
impl Default for sockaddr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(2))]
#[derive(Clone, Copy)]
pub struct sockaddr_unsized {
    pub sa_family: __kernel_sa_family_t,
    pub sa_data: *mut i8,
}
impl Default for sockaddr_unsized {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(64))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct socket {
    pub state: socket_state,
    pub r#type: i16,
    pub flags: u64,
    pub file: *mut super::fs::file,
    pub sk: *mut core::ffi::c_void,
    pub ops: *mut proto_ops,
    pub _pad_0: [u8; 24],
    pub wq: socket_wq,
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for socket {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type socket_flags = u32;
pub type socket_state = u32;
#[repr(C, packed(64))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct socket_wq {
    pub wait: super::wait::wait_queue_head_t,
    pub fasync_list: *mut super::fs::fasync_struct,
    pub flags: u64,
    pub rcu: super::types::callback_head,
    pub _padding: [u8; 8],
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for socket_wq {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct ucred {
    pub pid: super::types::__u32,
    pub uid: super::types::__u32,
    pub gid: super::types::__u32,
}
#[repr(C, packed(8))]
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct uio_meta {
    pub flags: uio_meta_flags_t,
    pub app_tag: u16,
    pub seed: u64,
    pub iter: iov_iter,
}
#[cfg(all(feature = "ds", feature = "sync", feature = "types"))]
impl Default for uio_meta {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type uio_meta_flags_t = super::types::__u16;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct user_msghdr {
    pub msg_name: *mut core::ffi::c_void,
    pub msg_namelen: i32,
    pub msg_iov: *mut iovec,
    pub msg_iovlen: super::types::__kernel_size_t,
    pub msg_control: *mut core::ffi::c_void,
    pub msg_controllen: super::types::__kernel_size_t,
    pub msg_flags: u32,
}
#[cfg(feature = "types")]
impl Default for user_msghdr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
