// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("kernel" "C" fn rust_helper_ERR_PTR(error : i64) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn rust_helper_IS_ERR(ptr : *const core::ffi::c_void) -> bool);
windows_link::link!("kernel" "C" fn rust_helper_MKDEV(major : u32, minor : u32) -> u32);
windows_link::link!("kernel" "C" fn rust_helper_PTR_ERR(ptr : *const core::ffi::c_void) -> i64);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "fs_context",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn rust_helper_alloc_inode_sb(sb : *mut super::fs:: super_block, cache : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn rust_helper_dentry_name(dentry : *const super::dcache:: dentry) -> *mut u8);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn rust_helper_dentry_name_len(dentry : *const super::dcache:: dentry) -> u32);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn rust_helper_dir_emit(ctx : *mut super::fs:: dir_context, name : *const i8, namelen : i32, ino : u64, r#type : u8) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "fs_context",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn rust_helper_file_inode(f : *const super::fs:: file) -> *mut super::fs:: inode);
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn rust_helper_flush_dcache_folio(folio : *mut super::fs:: folio));
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn rust_helper_folio_end_read(folio : *mut super::fs:: folio, success : bool));
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn rust_helper_folio_get(folio : *mut super::fs:: folio));
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn rust_helper_folio_mark_uptodate(folio : *mut super::fs:: folio));
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn rust_helper_folio_pos(folio : *mut super::fs:: folio) -> i64);
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn rust_helper_folio_put(folio : *mut super::fs:: folio));
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn rust_helper_folio_size(folio : *mut super::fs:: folio) -> u64);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "fs_context",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn rust_helper_generic_file_read_iter(iocb : *mut super::fs:: kiocb, to : *mut core::ffi::c_void) -> i64);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "fs_context",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn rust_helper_i_gid_write(inode : *mut super::fs:: inode, gid : u32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "fs_context",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn rust_helper_i_uid_write(inode : *mut super::fs:: inode, uid : u32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "fs_context",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn rust_helper_inode_set_aops(inode : *mut super::fs:: inode, aops : *const super::fs:: address_space_operations));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "fs_context",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn rust_helper_inode_set_flags(inode : *mut super::fs:: inode, flags : u32, mask : u32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "fs_context",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn rust_helper_inode_set_fop(inode : *mut super::fs:: inode, fop : *const super::fs:: file_operations));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "fs_context",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn rust_helper_is_bad_inode(inode : *mut super::fs:: inode) -> bool);
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn rust_helper_kmap_local_folio(folio : *mut super::fs:: folio, offset : u64) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn rust_helper_kmem_cache_create(name : *const i8, size : u32, align : u32, flags : u64, ctor : *mut isize) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn rust_helper_kunmap_local(vaddr : *const core::ffi::c_void));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "fs_context",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn rust_helper_mapping_set_large_folios(mapping : *mut super::fs:: address_space));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "fs_context",
    feature = "types"
))]
windows_link::link!("kernel" "C" fn rust_helper_set_nlink(inode : *mut super::fs:: inode, nlink : u32));
