// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(all(feature = "iomap", feature = "types"))]
windows_link::link!("kernel" "C" fn misc_deregister(misc : *mut miscdevice));
#[cfg(all(feature = "iomap", feature = "types"))]
windows_link::link!("kernel" "C" fn misc_register(misc : *mut miscdevice) -> i32);
pub const AC_MINOR: i32 = 157i32;
pub const AGPGART_MINOR: i32 = 175i32;
pub const APM_MINOR_DEV: i32 = 134i32;
pub const APOLLO_MOUSE_MINOR: i32 = 7i32;
pub const ATARIMOUSE_MINOR: i32 = 5i32;
pub const ATIXL_BUSMOUSE_MINOR: i32 = 3i32;
pub const AUTOFS_MINOR: i32 = 235i32;
pub const BTRFS_MINOR: i32 = 234i32;
pub const BUTTON_MINOR: i32 = 158i32;
pub const CUSE_MINOR: i32 = 203i32;
pub const D7S_MINOR: i32 = 193i32;
pub const DMAPI_MINOR: i32 = 140i32;
pub const EISA_EEPROM_MINOR: i32 = 241i32;
pub const ENVCTRL_MINOR: i32 = 162i32;
pub const FUSE_MINOR: i32 = 229i32;
pub const HPET_MINOR: i32 = 228i32;
pub const HWRNG_MINOR: i32 = 183i32;
pub const I2O_MINOR: i32 = 166i32;
pub const IRNET_MINOR: i32 = 187i32;
pub const KEYPAD_MINOR: i32 = 185i32;
pub const KVM_MINOR: i32 = 232i32;
pub const LCD_MINOR: i32 = 156i32;
pub const LOOP_CTRL_MINOR: i32 = 237i32;
pub const MAPPER_CTRL_MINOR: i32 = 236i32;
pub const MISC_DYNAMIC_MINOR: i32 = 255i32;
pub const MISC_MCELOG_MINOR: i32 = 227i32;
pub const MPT2SAS_MINOR: i32 = 221i32;
pub const MPT3SAS_MINOR: i32 = 222i32;
pub const MPT_MINOR: i32 = 220i32;
pub const MS_BUSMOUSE_MINOR: i32 = 2i32;
pub const NVRAM_MINOR: i32 = 144i32;
pub const NWFLASH_MINOR: i32 = 160i32;
pub const PC110PAD_MINOR: i32 = 9i32;
pub const PMU_MINOR: i32 = 154i32;
pub const PSMOUSE_MINOR: i32 = 1i32;
pub const PXA3XX_GCU_MINOR: i32 = 197i32;
pub const RFKILL_MINOR: i32 = 242i32;
pub const RTC_MINOR: i32 = 135i32;
pub const SBUS_FLASH_MINOR: i32 = 152i32;
pub const SGI_MMTIMER: i32 = 153i32;
pub const SNAPSHOT_MINOR: i32 = 231i32;
pub const STORE_QUEUE_MINOR: i32 = 155i32;
pub const SUN_MOUSE_MINOR: i32 = 6i32;
pub const SUN_OPENPROM_MINOR: i32 = 139i32;
pub const TEMP_MINOR: i32 = 131i32;
pub const TOSH_MINOR_DEV: i32 = 181i32;
pub const TUN_MINOR: i32 = 200i32;
pub const UCTRL_MINOR: i32 = 174i32;
pub const UHID_MINOR: i32 = 239i32;
pub const UINPUT_MINOR: i32 = 223i32;
pub const USERIO_MINOR: i32 = 240i32;
pub const VFIO_MINOR: i32 = 196i32;
pub const VHCI_MINOR: i32 = 137i32;
pub const VHOST_NET_MINOR: i32 = 238i32;
pub const VHOST_VSOCK_MINOR: i32 = 241i32;
pub const WATCHDOG_MINOR: i32 = 130i32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct attribute_group {
    pub _reserved: [u64; 6],
}
impl Default for attribute_group {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "iomap", feature = "types"))]
#[derive(Clone, Copy)]
pub struct miscdevice {
    pub minor: i32,
    pub name: *mut i8,
    pub fops: *mut core::ffi::c_void,
    pub list: super::types::list_head,
    pub parent: *mut super::iomap::device,
    pub this_device: *mut super::iomap::device,
    pub groups: *mut *mut attribute_group,
    pub nodename: *mut i8,
    pub mode: super::types::umode_t,
}
#[cfg(all(feature = "iomap", feature = "types"))]
impl Default for miscdevice {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
