// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("kernel" "C" fn __flush_workqueue(wq : *mut core::ffi::c_void));
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn __init_work(work : *mut work_struct, onstack : i32));
windows_link::link!("kernel" "C" fn __warn_flushing_systemwide_wq());
windows_link::link!("kernel" "C" fn alloc_workqueue_attrs_noprof() -> *mut workqueue_attrs);
windows_link::link!("kernel" "C" fn apply_workqueue_attrs(wq : *mut core::ffi::c_void, attrs : *const workqueue_attrs) -> i32);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn cancel_delayed_work(dwork : *mut delayed_work) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn cancel_delayed_work_sync(dwork : *mut delayed_work) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn cancel_work(work : *mut work_struct) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn cancel_work_sync(work : *mut work_struct) -> bool);
windows_link::link!("kernel" "C" fn current_is_workqueue_rescuer() -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn current_work() -> *mut work_struct);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn delayed_work_timer_fn(t : *mut super::fs:: timer_list));
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn destroy_delayed_work_on_stack(work : *mut delayed_work));
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn destroy_work_on_stack(work : *mut work_struct));
windows_link::link!("kernel" "C" fn destroy_workqueue(wq : *mut core::ffi::c_void));
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn disable_delayed_work(dwork : *mut delayed_work) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn disable_delayed_work_sync(dwork : *mut delayed_work) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn disable_work(work : *mut work_struct) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn disable_work_sync(work : *mut work_struct) -> bool);
windows_link::link!("kernel" "C" fn drain_workqueue(wq : *mut core::ffi::c_void));
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn enable_and_queue_work(wq : *mut core::ffi::c_void, work : *mut work_struct) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn enable_delayed_work(dwork : *mut delayed_work) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn enable_work(work : *mut work_struct) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn execute_in_process_context(r#fn : super::fs:: work_func_t, param1 : *mut execute_work) -> i32);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn flush_delayed_work(dwork : *mut delayed_work) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn flush_rcu_work(rwork : *mut rcu_work) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn flush_work(work : *mut work_struct) -> bool);
windows_link::link!("kernel" "C" fn free_workqueue_attrs(attrs : *mut workqueue_attrs));
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn mod_delayed_work(wq : *mut core::ffi::c_void, dwork : *mut delayed_work, delay : u64) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn mod_delayed_work_on(cpu : i32, wq : *mut core::ffi::c_void, dwork : *mut delayed_work, delay : u64) -> bool);
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn print_worker_info(log_lvl : *const i8, task : *mut super::fs:: task_struct));
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn queue_delayed_work(wq : *mut core::ffi::c_void, dwork : *mut delayed_work, delay : u64) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn queue_delayed_work_on(cpu : i32, wq : *mut core::ffi::c_void, work : *mut delayed_work, delay : u64) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn queue_rcu_work(wq : *mut core::ffi::c_void, rwork : *mut rcu_work) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn queue_work(wq : *mut core::ffi::c_void, work : *mut work_struct) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn queue_work_node(node : i32, wq : *mut core::ffi::c_void, work : *mut work_struct) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn queue_work_on(cpu : i32, wq : *mut core::ffi::c_void, work : *mut work_struct) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn schedule_delayed_work(dwork : *mut delayed_work, delay : u64) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn schedule_delayed_work_on(cpu : i32, dwork : *mut delayed_work, delay : u64) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn schedule_on_each_cpu(func : super::fs:: work_func_t) -> i32);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn schedule_work(work : *mut work_struct) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn schedule_work_on(cpu : i32, work : *mut work_struct) -> bool);
windows_link::link!("kernel" "C" fn show_all_workqueues());
windows_link::link!("kernel" "C" fn show_freezable_workqueues());
windows_link::link!("kernel" "C" fn show_one_workqueue(wq : *mut core::ffi::c_void));
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn to_delayed_work(work : *mut work_struct) -> *mut delayed_work);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn to_rcu_work(work : *mut work_struct) -> *mut rcu_work);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn work_busy(work : *mut work_struct) -> u32);
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn work_on_cpu_key(cpu : i32, r#fn : *mut isize, arg : *mut core::ffi::c_void, key : *mut super::fs:: lock_class_key) -> i64);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn work_static(work : *mut work_struct) -> u32);
windows_link::link!("kernel" "C" fn workqueue_congested(cpu : i32, wq : *mut core::ffi::c_void) -> bool);
windows_link::link!("kernel" "C" fn workqueue_init());
windows_link::link!("kernel" "C" fn workqueue_init_early());
windows_link::link!("kernel" "C" fn workqueue_init_topology());
windows_link::link!("kernel" "C" fn workqueue_offline_cpu(cpu : u32) -> i32);
windows_link::link!("kernel" "C" fn workqueue_online_cpu(cpu : u32) -> i32);
windows_link::link!("kernel" "C" fn workqueue_prepare_cpu(cpu : u32) -> i32);
windows_link::link!("kernel" "C" fn workqueue_set_max_active(wq : *mut core::ffi::c_void, max_active : i32));
windows_link::link!("kernel" "C" fn workqueue_set_min_active(wq : *mut core::ffi::c_void, min_active : i32));
windows_link::link!("kernel" "C" fn workqueue_softirq_action(highpri : bool));
windows_link::link!("kernel" "C" fn workqueue_softirq_dead(cpu : u32));
windows_link::link!("kernel" "C" fn workqueue_sysfs_register(wq : *mut core::ffi::c_void) -> i32);
windows_link::link!("kernel" "C" fn workqueue_unbound_housekeeping_update(hk : *const cpumask) -> i32);
windows_link::link!("kernel" "C" fn wq_watchdog_touch(cpu : i32));
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn wq_worker_comm(buf : *mut i8, size : super::types:: size_t, task : *mut super::fs:: task_struct));
pub const WORKER_DESC_LEN: u32 = 32u32;
pub const WORK_BUSY_PENDING: u32 = 1u32;
pub const WORK_BUSY_RUNNING: u32 = 2u32;
pub const WORK_CPU_UNBOUND: u32 = 2u32;
pub const WORK_NR_COLORS: u32 = 16u32;
pub const WORK_OFFQ_BH_BIT: u32 = 4u32;
pub const WORK_OFFQ_DISABLE_BITS: u32 = 16u32;
pub const WORK_OFFQ_DISABLE_SHIFT: u32 = 5u32;
pub const WORK_OFFQ_FLAG_BITS: u32 = 1u32;
pub const WORK_OFFQ_FLAG_END: u32 = 5u32;
pub const WORK_OFFQ_FLAG_SHIFT: u32 = 4u32;
pub const WORK_OFFQ_LEFT: u32 = 43u32;
pub const WORK_OFFQ_POOL_BITS: u32 = 31u32;
pub const WORK_OFFQ_POOL_SHIFT: u32 = 21u32;
pub const WORK_STRUCT_COLOR_BITS: u32 = 4u32;
pub const WORK_STRUCT_COLOR_SHIFT: u32 = 4u32;
pub const WORK_STRUCT_FLAG_BITS: u32 = 4u32;
pub const WORK_STRUCT_INACTIVE: u32 = 2u32;
pub const WORK_STRUCT_INACTIVE_BIT: u32 = 1u32;
pub const WORK_STRUCT_LINKED: u32 = 8u32;
pub const WORK_STRUCT_LINKED_BIT: u32 = 3u32;
pub const WORK_STRUCT_PENDING: u32 = 1u32;
pub const WORK_STRUCT_PENDING_BIT: u32 = 0u32;
pub const WORK_STRUCT_PWQ: u32 = 4u32;
pub const WORK_STRUCT_PWQ_BIT: u32 = 2u32;
pub const WORK_STRUCT_PWQ_SHIFT: u32 = 8u32;
pub const WORK_STRUCT_STATIC: u32 = 0u32;
pub const WQ_AFFN_CACHE: u32 = 3u32;
pub const WQ_AFFN_CPU: u32 = 1u32;
pub const WQ_AFFN_DFL: u32 = 0u32;
pub const WQ_AFFN_NR_TYPES: u32 = 6u32;
pub const WQ_AFFN_NUMA: u32 = 4u32;
pub const WQ_AFFN_SMT: u32 = 2u32;
pub const WQ_AFFN_SYSTEM: u32 = 5u32;
pub const WQ_BH: u32 = 1u32;
pub const WQ_CPU_INTENSIVE: u32 = 32u32;
pub const WQ_DFL_ACTIVE: u32 = 1024u32;
pub const WQ_DFL_MIN_ACTIVE: u32 = 8u32;
pub const WQ_FREEZABLE: u32 = 4u32;
pub const WQ_HIGHPRI: u32 = 16u32;
pub const WQ_MAX_ACTIVE: u32 = 2048u32;
pub const WQ_MEM_RECLAIM: u32 = 8u32;
pub const WQ_PERCPU: u32 = 256u32;
pub const WQ_POWER_EFFICIENT: u32 = 128u32;
pub const WQ_SYSFS: u32 = 64u32;
pub const WQ_UNBOUND: u32 = 2u32;
pub const WQ_UNBOUND_MAX_ACTIVE: u32 = 2048u32;
pub const __WQ_BH_ALLOWS: u32 = 273u32;
pub const __WQ_DESTROYING: u32 = 32768u32;
pub const __WQ_DRAINING: u32 = 65536u32;
pub const __WQ_LEGACY: u32 = 262144u32;
pub const __WQ_ORDERED: u32 = 131072u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct cpumask {
    pub _reserved: [u64; 1],
}
impl Default for cpumask {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "fs", feature = "types"))]
#[derive(Clone, Copy)]
pub struct delayed_work {
    pub work: work_struct,
    pub timer: super::fs::timer_list,
    pub wq: *mut core::ffi::c_void,
    pub cpu: i32,
}
#[cfg(all(feature = "fs", feature = "types"))]
impl Default for delayed_work {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "fs", feature = "types"))]
#[derive(Clone, Copy, Default)]
pub struct execute_work {
    pub work: work_struct,
}
#[repr(C, packed(8))]
#[cfg(all(feature = "fs", feature = "types"))]
#[derive(Clone, Copy)]
pub struct rcu_work {
    pub work: work_struct,
    pub rcu: super::types::callback_head,
    pub wq: *mut core::ffi::c_void,
}
#[cfg(all(feature = "fs", feature = "types"))]
impl Default for rcu_work {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type work_bits = u32;
pub type work_flags = u32;
#[repr(C, packed(8))]
#[cfg(all(feature = "fs", feature = "types"))]
#[derive(Clone, Copy, Default)]
pub struct work_struct {
    pub data: super::types::atomic64_t,
    pub entry: super::types::list_head,
    pub func: super::fs::work_func_t,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct workqueue_attrs {
    pub nice: i32,
    pub cpumask: [cpumask; 1],
    pub __pod_cpumask: [cpumask; 1],
    pub affn_strict: bool,
    pub affn_scope: wq_affn_scope,
    pub ordered: bool,
}
impl Default for workqueue_attrs {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type wq_affn_scope = u32;
pub type wq_consts = u32;
pub type wq_flags = u32;
pub type wq_misc_consts = u32;
