// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "dcache")]
pub mod dcache;
#[cfg(feature = "err")]
pub mod err;
#[cfg(feature = "fs")]
pub mod fs;
#[cfg(feature = "fs_context")]
pub mod fs_context;
#[cfg(feature = "gfp")]
pub mod gfp;
#[cfg(feature = "helpers")]
pub mod helpers;
#[cfg(feature = "highmem")]
pub mod highmem;
#[cfg(feature = "iomap")]
pub mod iomap;
#[cfg(feature = "net")]
pub mod net;
#[cfg(feature = "pagemap")]
pub mod pagemap;
#[cfg(feature = "poll")]
pub mod poll;
#[cfg(feature = "slab")]
pub mod slab;
#[cfg(feature = "statfs")]
pub mod statfs;
#[cfg(feature = "sync")]
pub mod sync;
#[cfg(feature = "types")]
pub mod types;
#[cfg(feature = "workqueue")]
pub mod workqueue;
#[cfg(feature = "xattr")]
pub mod xattr;
