// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "err")]
pub mod err;
#[cfg(feature = "gfp")]
pub mod gfp;
#[cfg(feature = "slab")]
pub mod slab;
#[cfg(feature = "types")]
pub mod types;
