// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn fc_drop_locked(fc : *mut fs_context));
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn fs_context_for_mount(fs_type : *mut super::fs:: file_system_type, sb_flags : u32) -> *mut fs_context);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn fs_context_for_reconfigure(dentry : *mut super::dcache:: dentry, sb_flags : u32, sb_flags_mask : u32) -> *mut fs_context);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn fs_context_for_submount(fs_type : *mut super::fs:: file_system_type, reference : *mut super::dcache:: dentry) -> *mut fs_context);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn generic_parse_monolithic(fc : *mut fs_context, data : *mut core::ffi::c_void) -> i32);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn get_tree_bdev(fc : *mut fs_context, fill_super : *mut isize) -> i32);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn get_tree_bdev_flags(fc : *mut fs_context, fill_super : *mut isize, flags : u32) -> i32);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn get_tree_keyed(fc : *mut fs_context, fill_super : *mut isize, key : *mut core::ffi::c_void) -> i32);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn get_tree_nodev(fc : *mut fs_context, fill_super : *mut isize) -> i32);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn get_tree_single(fc : *mut fs_context, fill_super : *mut isize) -> i32);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn put_fs_context(fc : *mut fs_context));
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn setup_bdev_super(sb : *mut super::fs:: super_block, sb_flags : i32, fc : *mut fs_context) -> i32);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn vfs_dup_fs_context(fc : *mut fs_context) -> *mut fs_context);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn vfs_get_tree(fc : *mut fs_context) -> i32);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn vfs_parse_fs_param(fc : *mut fs_context, param : *mut fs_parameter) -> i32);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn vfs_parse_fs_param_source(fc : *mut fs_context, param : *mut fs_parameter) -> i32);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn vfs_parse_fs_qstr(fc : *mut fs_context, key : *const i8, value : *const super::dcache:: qstr) -> i32);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn vfs_parse_fs_string(fc : *mut fs_context, key : *const i8, value : *const i8) -> i32);
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn vfs_parse_monolithic_sep(fc : *mut fs_context, data : *mut core::ffi::c_void, sep : *mut isize) -> i32);
pub const FS_CONTEXT_AWAITING_MOUNT: u32 = 2u32;
pub const FS_CONTEXT_AWAITING_RECONF: u32 = 3u32;
pub const FS_CONTEXT_CREATE_PARAMS: u32 = 0u32;
pub const FS_CONTEXT_CREATING: u32 = 1u32;
pub const FS_CONTEXT_FAILED: u32 = 6u32;
pub const FS_CONTEXT_FOR_MOUNT: u32 = 0u32;
pub const FS_CONTEXT_FOR_RECONFIGURE: u32 = 2u32;
pub const FS_CONTEXT_FOR_SUBMOUNT: u32 = 1u32;
pub const FS_CONTEXT_RECONFIGURING: u32 = 5u32;
pub const FS_CONTEXT_RECONF_PARAMS: u32 = 4u32;
pub const GET_TREE_BDEV_QUIET_LOOKUP: i32 = 1i32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct fc_log {
    pub usage: refcount_struct,
    pub head: u8,
    pub tail: u8,
    pub need_free: u8,
    pub owner: *mut module,
    pub buffer: [*mut i8; 8],
}
impl Default for fc_log {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
#[derive(Clone, Copy)]
pub struct fs_context {
    pub ops: *mut fs_context_operations,
    pub uapi_mutex: mutex,
    pub fs_type: *mut super::fs::file_system_type,
    pub fs_private: *mut core::ffi::c_void,
    pub sget_key: *mut core::ffi::c_void,
    pub root: *mut super::dcache::dentry,
    pub user_ns: *mut user_namespace,
    pub net_ns: *mut core::ffi::c_void,
    pub cred: *mut super::fs::cred,
    pub log: p_log,
    pub source: *mut i8,
    pub security: *mut core::ffi::c_void,
    pub s_fs_info: *mut core::ffi::c_void,
    pub sb_flags: u32,
    pub sb_flags_mask: u32,
    pub s_iflags: u32,
    pub purpose: fs_context_purpose,
    pub phase: fs_context_phase,
    pub need_free: bool,
    pub global: bool,
    pub oldapi: bool,
    pub exclusive: bool,
}
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
impl Default for fs_context {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct fs_context_operations {
    pub free: *mut isize,
    pub dup: *mut isize,
    pub parse_param: *mut isize,
    pub parse_monolithic: *mut isize,
    pub get_tree: *mut isize,
    pub reconfigure: *mut isize,
}
impl Default for fs_context_operations {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type fs_context_phase = u32;
pub type fs_context_purpose = u32;
#[repr(C, packed(8))]
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
#[derive(Clone, Copy)]
pub struct fs_parameter {
    pub key: *mut i8,
    pub r#type: fs_value_type,
    pub fs_parameter__anon_0: fs_parameter__anon_0,
    pub size: super::types::size_t,
    pub dirfd: i32,
}
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
impl Default for fs_parameter {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
#[derive(Clone, Copy)]
pub union fs_parameter__anon_0 {
    pub string: *mut i8,
    pub blob: *mut core::ffi::c_void,
    pub name: *mut super::fs::filename,
    pub file: *mut super::fs::file,
}
#[cfg(all(feature = "dcache", feature = "fs", feature = "types"))]
impl Default for fs_parameter__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const fs_value_is_blob: u32 = 3u32;
pub const fs_value_is_file: u32 = 5u32;
pub const fs_value_is_filename: u32 = 4u32;
pub const fs_value_is_flag: u32 = 1u32;
pub const fs_value_is_string: u32 = 2u32;
pub const fs_value_is_undefined: u32 = 0u32;
pub type fs_value_type = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct module {
    pub _reserved: [u64; 152],
}
impl Default for module {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct mutex {
    pub _reserved: [u64; 4],
}
impl Default for mutex {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct p_log {
    pub prefix: *mut i8,
    pub log: *mut fc_log,
}
impl Default for p_log {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct refcount_struct {
    pub _reserved: [u32; 1],
}
impl Default for refcount_struct {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct user_namespace {
    pub _reserved: [u64; 95],
}
impl Default for user_namespace {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
