// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn u64_to_fsid(v : u64) -> super::types:: __kernel_fsid_t);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn uuid_to_fsid(uuid : *mut super::types:: __u8) -> super::types:: __kernel_fsid_t);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn vfs_get_fsid(dentry : *mut core::ffi::c_void, fsid : *mut super::types:: __kernel_fsid_t) -> i32);
pub const ST_MANDLOCK: i32 = 64i32;
pub const ST_NOATIME: i32 = 1024i32;
pub const ST_NODEV: i32 = 4i32;
pub const ST_NODIRATIME: i32 = 2048i32;
pub const ST_NOEXEC: i32 = 8i32;
pub const ST_NOSUID: i32 = 2i32;
pub const ST_NOSYMFOLLOW: i32 = 8192i32;
pub const ST_RDONLY: i32 = 1i32;
pub const ST_RELATIME: i32 = 4096i32;
pub const ST_SYNCHRONOUS: i32 = 16i32;
pub const ST_VALID: i32 = 32i32;
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct compat_statfs64 {
    pub f_type: super::types::__u32,
    pub f_bsize: super::types::__u32,
    pub f_blocks: super::types::__u64,
    pub f_bfree: super::types::__u64,
    pub f_bavail: super::types::__u64,
    pub f_files: super::types::__u64,
    pub f_ffree: super::types::__u64,
    pub f_fsid: super::types::__kernel_fsid_t,
    pub f_namelen: super::types::__u32,
    pub f_frsize: super::types::__u32,
    pub f_flags: super::types::__u32,
    pub f_spare: [super::types::__u32; 4],
}
#[cfg(feature = "types")]
impl Default for compat_statfs64 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct kstatfs {
    pub f_type: i64,
    pub f_bsize: i64,
    pub f_blocks: u64,
    pub f_bfree: u64,
    pub f_bavail: u64,
    pub f_files: u64,
    pub f_ffree: u64,
    pub f_fsid: super::types::__kernel_fsid_t,
    pub f_namelen: i64,
    pub f_frsize: i64,
    pub f_flags: i64,
    pub f_spare: [i64; 4],
}
#[cfg(feature = "types")]
impl Default for kstatfs {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct statfs {
    pub f_type: super::types::__kernel_long_t,
    pub f_bsize: super::types::__kernel_long_t,
    pub f_blocks: super::types::__kernel_long_t,
    pub f_bfree: super::types::__kernel_long_t,
    pub f_bavail: super::types::__kernel_long_t,
    pub f_files: super::types::__kernel_long_t,
    pub f_ffree: super::types::__kernel_long_t,
    pub f_fsid: super::types::__kernel_fsid_t,
    pub f_namelen: super::types::__kernel_long_t,
    pub f_frsize: super::types::__kernel_long_t,
    pub f_flags: super::types::__kernel_long_t,
    pub f_spare: [super::types::__kernel_long_t; 4],
}
#[cfg(feature = "types")]
impl Default for statfs {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct statfs64 {
    pub f_type: super::types::__kernel_long_t,
    pub f_bsize: super::types::__kernel_long_t,
    pub f_blocks: super::types::__u64,
    pub f_bfree: super::types::__u64,
    pub f_bavail: super::types::__u64,
    pub f_files: super::types::__u64,
    pub f_ffree: super::types::__u64,
    pub f_fsid: super::types::__kernel_fsid_t,
    pub f_namelen: super::types::__kernel_long_t,
    pub f_frsize: super::types::__kernel_long_t,
    pub f_flags: super::types::__kernel_long_t,
    pub f_spare: [super::types::__kernel_long_t; 4],
}
#[cfg(feature = "types")]
impl Default for statfs64 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
