// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "pagemap",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __bio_add_page(bio : *mut bio, page : *mut super::pagemap:: page, len : u32, off : u32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __bio_advance(param0 : *mut bio, bytes : u32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __bio_release_pages(bio : *mut bio, mark_dirty : bool));
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn __folio_batch_release(pvec : *mut folio_batch));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "net",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __iomap_dio_rw(iocb : *mut super::fs:: kiocb, iter : *mut super::net:: iov_iter, ops : *const iomap_ops, dops : *const iomap_dio_ops, dio_flags : u32, private : *mut core::ffi::c_void, done_before : super::types:: size_t) -> *mut core::ffi::c_void);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bdev_rw_virt(bdev : *mut block_device, sector : super::types:: sector_t, data : *mut core::ffi::c_void, len : super::types:: size_t, op : req_op) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_add_folio(bio : *mut bio, folio : *mut super::fs:: folio, len : super::types:: size_t, off : super::types:: size_t) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_add_folio_nofail(bio : *mut bio, folio : *mut super::fs:: folio, len : super::types:: size_t, off : super::types:: size_t));
windows_link::link!("kernel" "C" fn bio_add_max_vecs(kaddr : *mut core::ffi::c_void, len : u32) -> u32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "pagemap",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_add_page(bio : *mut bio, page : *mut super::pagemap:: page, len : u32, off : u32) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_add_virt_nofail(bio : *mut bio, vaddr : *mut core::ffi::c_void, len : u32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_add_vmalloc(bio : *mut bio, vaddr : *mut core::ffi::c_void, len : u32) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_add_vmalloc_chunk(bio : *mut bio, vaddr : *mut core::ffi::c_void, len : u32) -> u32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_advance(bio : *mut bio, nbytes : u32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_advance_iter(bio : *const bio, iter : *mut bvec_iter, bytes : u32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_advance_iter_single(bio : *const bio, iter : *mut bvec_iter, bytes : u32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_alloc(bdev : *mut block_device, nr_vecs : u16, opf : blk_opf_t, gfp_mask : super::types:: gfp_t) -> *mut bio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_alloc_bioset(bdev : *mut block_device, nr_vecs : u16, opf : blk_opf_t, gfp_mask : super::types:: gfp_t, bs : *mut bio_set) -> *mut bio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_alloc_clone(bdev : *mut block_device, bio_src : *mut bio, gfp : super::types:: gfp_t, bs : *mut bio_set) -> *mut bio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_associate_blkg(bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_associate_blkg_from_css(bio : *mut bio, css : *mut core::ffi::c_void));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_chain(param0 : *mut bio, param1 : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_chain_and_submit(prev : *mut bio, new : *mut bio) -> *mut bio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_check_pages_dirty(bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_clear_flag(bio : *mut bio, bit : u32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_clear_polled(bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_clone_blkg_association(dst : *mut bio, src : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_cnt_set(bio : *mut bio, count : u32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_copy_data(dst : *mut bio, src : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_copy_data_iter(dst : *mut bio, dst_iter : *mut bvec_iter, src : *mut bio, src_iter : *mut bvec_iter));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_data(bio : *mut bio) -> *mut core::ffi::c_void);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_endio(param0 : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_first_bvec_all(bio : *mut bio) -> *mut bio_vec);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_first_folio(fi : *mut folio_iter, bio : *mut bio, i : i32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_first_folio_all(bio : *mut bio) -> *mut super::fs:: folio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "pagemap",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_first_page_all(bio : *mut bio) -> *mut super::pagemap:: page);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_flagged(bio : *const bio, bit : u32) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_free_pages(bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_get(bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_has_data(bio : *mut bio) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_inc_remaining(bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_init(bio : *mut bio, bdev : *mut block_device, table : *mut bio_vec, max_vecs : u16, opf : blk_opf_t));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_init_clone(bdev : *mut block_device, bio : *mut bio, bio_src : *mut bio, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_init_inline(bio : *mut bio, bdev : *mut block_device, max_vecs : u16, opf : blk_opf_t));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_inline_vecs(bio : *mut bio) -> *mut bio_vec);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_io_error(bio : *mut bio));
#[cfg(all(feature = "fs", feature = "net", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn bio_iov_bounce_nr_vecs(iter : *mut super::net:: iov_iter, op : blk_opf_t) -> u16);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "net",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_iov_bvec_set(bio : *mut bio, iter : *const super::net:: iov_iter));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "net",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_iov_iter_bounce(bio : *mut bio, iter : *mut super::net:: iov_iter) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "net",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_iov_iter_get_pages(bio : *mut bio, iter : *mut super::net:: iov_iter, len_align_mask : u32) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_iov_iter_unbounce(bio : *mut bio, is_error : bool, mark_dirty : bool));
#[cfg(all(feature = "fs", feature = "net", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn bio_iov_vecs_to_alloc(iter : *mut super::net:: iov_iter, max_segs : i32) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_is_zone_append(bio : *mut bio) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_kmalloc(nr_vecs : u16, gfp_mask : super::types:: gfp_t) -> *mut bio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_list_add(bl : *mut bio_list, bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_list_add_head(bl : *mut bio_list, bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_list_empty(bl : *const bio_list) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_list_get(bl : *mut bio_list) -> *mut bio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_list_init(bl : *mut bio_list));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_list_merge(bl : *mut bio_list, bl2 : *mut bio_list));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_list_merge_head(bl : *mut bio_list, bl2 : *mut bio_list));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_list_merge_init(bl : *mut bio_list, bl2 : *mut bio_list));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_list_peek(bl : *mut bio_list) -> *mut bio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_list_pop(bl : *mut bio_list) -> *mut bio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_list_size(bl : *const bio_list) -> u32);
windows_link::link!("kernel" "C" fn bio_max_segs(nr_segs : u32) -> u32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_next_folio(fi : *mut folio_iter, bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_next_segment(bio : *const bio, iter : *mut bvec_iter_all) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_next_split(bio : *mut bio, sectors : i32, gfp : super::types:: gfp_t, bs : *mut bio_set) -> *mut bio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_no_advance_iter(bio : *const bio) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_op(bio : *const bio) -> req_op);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_put(param0 : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_release_pages(bio : *mut bio, mark_dirty : bool));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_reset(bio : *mut bio, bdev : *mut block_device, opf : blk_opf_t));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_reuse(bio : *mut bio, opf : blk_opf_t));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_seg_gap(q : *mut request_queue, prev : *mut bio, next : *mut bio, gaps_bit : u8) -> u8);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_segments(bio : *mut bio) -> u32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_set_dev(bio : *mut bio, bdev : *mut block_device));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_set_flag(bio : *mut bio, bit : u32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_set_pages_dirty(bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_set_polled(bio : *mut bio, kiocb : *mut super::fs:: kiocb));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_split(bio : *mut bio, sectors : i32, gfp : super::types:: gfp_t, bs : *mut bio_set) -> *mut bio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_split_io_at(bio : *mut bio, lim : *const queue_limits, segs : *mut u32, max_bytes : u32, len_align : u32) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_trim(bio : *mut bio, offset : super::types:: sector_t, size : super::types:: sector_t));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_uninit(param0 : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bio_wouldblock_error(bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bioset_exit(param0 : *mut bio_set));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bioset_init(param0 : *mut bio_set, param1 : u32, param2 : u32, flags : i32) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn bioset_initialized(bs : *mut bio_set) -> bool);
windows_link::link!("kernel" "C" fn biovec_init_pool(pool : *mut mempool, pool_entries : i32) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn blk_alloc_discard_bio(bdev : *mut block_device, sector : *mut super::types:: sector_t, nr_sects : *mut super::types:: sector_t, gfp_mask : super::types:: gfp_t) -> *mut bio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn blk_next_bio(bio : *mut bio, bdev : *mut block_device, nr_pages : u32, opf : blk_opf_t, gfp : super::types:: gfp_t) -> *mut bio);
windows_link::link!("kernel" "C" fn blk_path_error(error : blk_status_t) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn blkcg_punt_bio_submit(bio : *mut bio));
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn folio_batch_add(fbatch : *mut folio_batch, folio : *mut super::fs:: folio) -> u32);
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn folio_batch_count(fbatch : *const folio_batch) -> u32);
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn folio_batch_init(fbatch : *mut folio_batch));
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn folio_batch_next(fbatch : *mut folio_batch) -> *mut super::fs:: folio);
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn folio_batch_reinit(fbatch : *mut folio_batch));
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn folio_batch_release(fbatch : *mut folio_batch));
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn folio_batch_remove_exceptionals(fbatch : *mut folio_batch));
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn folio_batch_space(fbatch : *const folio_batch) -> u32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn guard_bio_eod(bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_add_to_ioend(wpc : *mut iomap_writepage_ctx, folio : *mut super::fs:: folio, pos : super::types:: loff_t, end_pos : super::types:: loff_t, dirty_len : u32) -> super::types:: ssize_t);
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn iomap_bio_read_folio(folio : *mut super::fs:: folio, ops : *const iomap_ops));
windows_link::link!("kernel" "C" fn iomap_bio_readahead(rac : *mut core::ffi::c_void, ops : *const iomap_ops));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_bmap(mapping : *mut super::fs:: address_space, bno : super::types:: sector_t, ops : *const iomap_ops) -> super::types:: sector_t);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_dio_bio_end_io(bio : *mut bio));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn iomap_dio_complete(dio : *mut core::ffi::c_void) -> super::types:: ssize_t);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "net",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_dio_rw(iocb : *mut super::fs:: kiocb, iter : *mut super::net:: iov_iter, ops : *const iomap_ops, dops : *const iomap_dio_ops, dio_flags : u32, private : *mut core::ffi::c_void, done_before : super::types:: size_t) -> super::types:: ssize_t);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_dirty_folio(mapping : *mut super::fs:: address_space, folio : *mut super::fs:: folio) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_fiemap(inode : *mut super::fs:: inode, fieinfo : *mut core::ffi::c_void, start : u64, len : u64, ops : *const iomap_ops) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "net",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_file_buffered_write(iocb : *mut super::fs:: kiocb, from : *mut super::net:: iov_iter, ops : *const iomap_ops, write_ops : *const iomap_write_ops, private : *mut core::ffi::c_void) -> super::types:: ssize_t);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_file_unshare(inode : *mut super::fs:: inode, pos : super::types:: loff_t, len : super::types:: loff_t, ops : *const iomap_ops, write_ops : *const iomap_write_ops) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_fill_dirty_folios(iter : *mut iomap_iter, start : *mut super::types:: loff_t, end : super::types:: loff_t, iomap_flags : *mut u32) -> u32);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn iomap_finish_folio_read(folio : *mut super::fs:: folio, off : super::types:: size_t, len : super::types:: size_t, error : i32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_finish_folio_write(inode : *mut super::fs:: inode, folio : *mut super::fs:: folio, len : super::types:: size_t));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_finish_ioends(ioend : *mut iomap_ioend, error : i32));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_get_folio(iter : *mut iomap_iter, pos : super::types:: loff_t, len : super::types:: size_t) -> *mut super::fs:: folio);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_init_ioend(inode : *mut super::fs:: inode, bio : *mut bio, file_offset : super::types:: loff_t, ioend_flags : u16) -> *mut iomap_ioend);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_inline_data(iomap : *const iomap, pos : super::types:: loff_t) -> *mut core::ffi::c_void);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_inline_data_valid(iomap : *const iomap) -> bool);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn iomap_invalidate_folio(folio : *mut super::fs:: folio, offset : super::types:: size_t, len : super::types:: size_t));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_ioend_from_bio(bio : *mut bio) -> *mut iomap_ioend);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_ioend_try_merge(ioend : *mut iomap_ioend, more_ioends : *mut super::types:: list_head));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_ioend_writeback_submit(wpc : *mut iomap_writepage_ctx, error : i32) -> i32);
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn iomap_is_partially_uptodate(param0 : *mut super::fs:: folio, from : super::types:: size_t, count : super::types:: size_t) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_iter(iter : *mut iomap_iter, ops : *const iomap_ops) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_iter_advance(iter : *mut iomap_iter, count : u64) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_iter_advance_full(iter : *mut iomap_iter) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_iter_srcmap(i : *const iomap_iter) -> *mut iomap);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_last_written_block(inode : *mut super::fs:: inode, pos : super::types:: loff_t, written : super::types:: ssize_t) -> super::types:: loff_t);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_length(iter : *const iomap_iter) -> u64);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_length_trim(iter : *const iomap_iter, pos : super::types:: loff_t, len : u64) -> u64);
#[cfg(feature = "pagemap")]
windows_link::link!("kernel" "C" fn iomap_page_mkwrite(vmf : *mut super::pagemap:: vm_fault, ops : *const iomap_ops, private : *mut core::ffi::c_void) -> u32);
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn iomap_read_folio(ops : *const iomap_ops, ctx : *mut iomap_read_folio_ctx, private : *mut core::ffi::c_void));
#[cfg(feature = "fs")]
windows_link::link!("kernel" "C" fn iomap_readahead(ops : *const iomap_ops, ctx : *mut iomap_read_folio_ctx, private : *mut core::ffi::c_void));
#[cfg(all(feature = "fs", feature = "types"))]
windows_link::link!("kernel" "C" fn iomap_release_folio(folio : *mut super::fs:: folio, gfp_flags : super::types:: gfp_t) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_sector(iomap : *const iomap, pos : super::types:: loff_t) -> super::types:: sector_t);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_seek_data(inode : *mut super::fs:: inode, offset : super::types:: loff_t, ops : *const iomap_ops) -> super::types:: loff_t);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_seek_hole(inode : *mut super::fs:: inode, offset : super::types:: loff_t, ops : *const iomap_ops) -> super::types:: loff_t);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn iomap_sort_ioends(ioend_list : *mut super::types:: list_head));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_split_ioend(ioend : *mut iomap_ioend, max_len : u32, is_append : bool) -> *mut iomap_ioend);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_swapfile_activate(sis : *mut core::ffi::c_void, swap_file : *mut super::fs:: file, pagespan : *mut super::types:: sector_t, ops : *const iomap_ops) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_truncate_page(inode : *mut super::fs:: inode, pos : super::types:: loff_t, did_zero : *mut bool, ops : *const iomap_ops, write_ops : *const iomap_write_ops, private : *mut core::ffi::c_void) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_want_unshare_iter(iter : *const iomap_iter) -> bool);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_write_delalloc_release(inode : *mut super::fs:: inode, start_byte : super::types:: loff_t, end_byte : super::types:: loff_t, flags : u32, iomap : *mut iomap, punch : iomap_punch_t));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_writeback_folio(wpc : *mut iomap_writepage_ctx, folio : *mut super::fs:: folio) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_writepages(wpc : *mut iomap_writepage_ctx) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn iomap_zero_range(inode : *mut super::fs:: inode, pos : super::types:: loff_t, len : super::types:: loff_t, did_zero : *mut bool, ops : *const iomap_ops, write_ops : *const iomap_write_ops, private : *mut core::ffi::c_void) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn op_is_discard(op : blk_opf_t) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn op_is_flush(op : blk_opf_t) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn op_is_sync(op : blk_opf_t) -> bool);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn op_is_write(op : blk_opf_t) -> bool);
windows_link::link!("kernel" "C" fn op_is_zone_mgmt(op : req_op) -> bool);
windows_link::link!("kernel" "C" fn op_stat_group(op : req_op) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn submit_bio(bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn submit_bio_wait(bio : *mut bio) -> i32);
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn zero_fill_bio(bio : *mut bio));
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn zero_fill_bio_iter(bio : *mut bio, iter : bvec_iter));
pub const BD_PARTNO: i32 = 255i32;
pub const BIOSET_NEED_BVECS: u32 = 1u32;
pub const BIOSET_NEED_RESCUER: u32 = 2u32;
pub const BIOSET_PERCPU_CACHE: u32 = 4u32;
pub const BIO_BPS_THROTTLED: u32 = 5u32;
pub const BIO_CGROUP_ACCT: u32 = 7u32;
pub const BIO_CHAIN: u32 = 3u32;
pub const BIO_CLONED: u32 = 1u32;
pub const BIO_EMULATES_ZONE_APPEND: u32 = 12u32;
pub const BIO_FLAG_LAST: u32 = 13u32;
pub const BIO_MAX_VECS: i32 = 256i32;
pub const BIO_PAGE_PINNED: u32 = 0u32;
pub const BIO_POOL_SIZE: i32 = 2i32;
pub const BIO_QOS_MERGED: u32 = 9u32;
pub const BIO_QOS_THROTTLED: u32 = 8u32;
pub const BIO_QUIET: u32 = 2u32;
pub const BIO_REFFED: u32 = 4u32;
pub const BIO_REMAPPED: u32 = 10u32;
pub const BIO_TG_BPS_THROTTLED: u32 = 8u32;
pub const BIO_TRACE_COMPLETION: u32 = 6u32;
pub const BIO_ZONE_WRITE_PLUGGING: u32 = 11u32;
pub const BLK_QC_T_NONE: i32 = -1i32;
pub const BLK_STS_OK: i32 = 0i32;
pub const IOMAP_DAX: i32 = 0i32;
pub const IOMAP_DELALLOC: i32 = 1i32;
pub const IOMAP_F_BUFFER_HEAD: i32 = 0i32;
pub const IOMAP_HOLE: i32 = 0i32;
pub const IOMAP_INLINE: i32 = 4i32;
pub const IOMAP_MAPPED: i32 = 2i32;
pub const IOMAP_NULL_ADDR: i32 = -1i32;
pub const IOMAP_UNWRITTEN: i32 = 3i32;
pub const LINUX_IOMAP_H: i32 = 1i32;
pub const NR_STAT_GROUPS: u32 = 4u32;
pub const PAGEVEC_SIZE: i32 = 31i32;
pub const REQ_FLAG_BITS: i32 = 24i32;
pub const REQ_OP_BITS: i32 = 8i32;
pub const REQ_OP_DISCARD: u32 = 3u32;
pub const REQ_OP_DRV_IN: u32 = 34u32;
pub const REQ_OP_DRV_OUT: u32 = 35u32;
pub const REQ_OP_FLUSH: u32 = 2u32;
pub const REQ_OP_LAST: u32 = 36u32;
pub const REQ_OP_READ: u32 = 0u32;
pub const REQ_OP_SECURE_ERASE: u32 = 5u32;
pub const REQ_OP_WRITE: u32 = 1u32;
pub const REQ_OP_WRITE_ZEROES: u32 = 9u32;
pub const REQ_OP_ZONE_APPEND: u32 = 7u32;
pub const REQ_OP_ZONE_CLOSE: u32 = 13u32;
pub const REQ_OP_ZONE_FINISH: u32 = 15u32;
pub const REQ_OP_ZONE_OPEN: u32 = 11u32;
pub const REQ_OP_ZONE_RESET: u32 = 17u32;
pub const REQ_OP_ZONE_RESET_ALL: u32 = 19u32;
pub const SECTOR_SHIFT: i32 = 9i32;
pub const STAT_DISCARD: u32 = 2u32;
pub const STAT_FLUSH: u32 = 3u32;
pub const STAT_READ: u32 = 0u32;
pub const STAT_WRITE: u32 = 1u32;
pub const __REQ_ALLOC_CACHE: u32 = 23u32;
pub const __REQ_ATOMIC: u32 = 27u32;
pub const __REQ_BACKGROUND: u32 = 20u32;
pub const __REQ_DRV: u32 = 25u32;
pub const __REQ_FAILFAST_DEV: u32 = 8u32;
pub const __REQ_FAILFAST_DRIVER: u32 = 10u32;
pub const __REQ_FAILFAST_TRANSPORT: u32 = 9u32;
pub const __REQ_FS_PRIVATE: u32 = 26u32;
pub const __REQ_FUA: u32 = 17u32;
pub const __REQ_IDLE: u32 = 15u32;
pub const __REQ_INTEGRITY: u32 = 16u32;
pub const __REQ_META: u32 = 12u32;
pub const __REQ_NOMERGE: u32 = 14u32;
pub const __REQ_NOUNMAP: u32 = 28u32;
pub const __REQ_NOWAIT: u32 = 21u32;
pub const __REQ_NR_BITS: u32 = 29u32;
pub const __REQ_POLLED: u32 = 22u32;
pub const __REQ_PREFLUSH: u32 = 18u32;
pub const __REQ_PRIO: u32 = 13u32;
pub const __REQ_RAHEAD: u32 = 19u32;
pub const __REQ_SWAP: u32 = 24u32;
pub const __REQ_SYNC: u32 = 11u32;
#[repr(C, packed(8))]
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct bio {
    pub bi_next: *mut bio,
    pub bi_bdev: *mut block_device,
    pub bi_opf: blk_opf_t,
    pub bi_flags: u16,
    pub bi_ioprio: u16,
    pub bi_write_hint: super::fs::rw_hint,
    pub bi_write_stream: u8,
    pub bi_status: blk_status_t,
    pub bi_bvec_gap_bit: u8,
    pub __bi_remaining: super::types::atomic_t,
    pub bi_io_vec: *mut bio_vec,
    pub bi_iter: bvec_iter,
    pub bio__anon_0: bio__anon_0,
    pub bi_end_io: *mut bio_end_io_t,
    pub bi_private: *mut core::ffi::c_void,
    pub bi_vcnt: u16,
    pub bi_max_vecs: u16,
    pub __bi_cnt: super::types::atomic_t,
    pub bi_pool: *mut bio_set,
}
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for bio {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub union bio__anon_0 {
    pub bi_cookie: blk_qc_t,
    pub __bi_nr_segments: u32,
}
impl Default for bio__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
pub type bio_end_io_t = Option<unsafe extern "system" fn(param0: *const bio)>;
#[repr(C, packed(8))]
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct bio_list {
    pub head: *mut bio,
    pub tail: *mut bio,
}
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for bio_list {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct bio_set {
    pub bio_slab: *mut core::ffi::c_void,
    pub front_pad: u32,
    pub cache: *mut core::ffi::c_void,
    pub bio_pool: mempool,
    pub bvec_pool: mempool,
    pub back_pad: u32,
    pub rescue_lock: super::sync::spinlock_t,
    pub rescue_list: bio_list,
    pub rescue_work: super::workqueue::work_struct,
    pub rescue_workqueue: *mut core::ffi::c_void,
    pub cpuhp_dead: super::types::hlist_node,
}
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for bio_set {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct bio_vec {
    pub _reserved: [u64; 2],
}
impl Default for bio_vec {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct blk_holder_ops {
    pub _reserved: [u64; 1],
}
impl Default for blk_holder_ops {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type blk_mq_req_flags_t = super::types::__u32;
pub type blk_opf_t = super::types::__u32;
pub type blk_qc_t = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy, Default)]
pub struct blk_rq_stat {
    pub mean: u64,
    pub min: u64,
    pub max: u64,
    pub nr_samples: u32,
    pub batch: u64,
}
pub type blk_short_t = u16;
pub type blk_status_t = u8;
#[repr(C, packed(8))]
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct block_device {
    pub bd_start_sect: super::types::sector_t,
    pub bd_nr_sectors: super::types::sector_t,
    pub bd_disk: *mut gendisk,
    pub bd_queue: *mut request_queue,
    pub bd_stats: *mut core::ffi::c_void,
    pub bd_stamp: u64,
    pub __bd_flags: super::types::atomic_t,
    pub bd_dev: super::types::dev_t,
    pub bd_mapping: *mut super::fs::address_space,
    pub bd_openers: super::types::atomic_t,
    pub bd_size_lock: super::sync::spinlock_t,
    pub bd_claiming: *mut core::ffi::c_void,
    pub bd_holder: *mut core::ffi::c_void,
    pub bd_holder_ops: *mut blk_holder_ops,
    pub bd_holder_lock: super::sync::mutex,
    pub bd_holders: i32,
    pub bd_holder_dir: *mut kobject,
    pub bd_fsfreeze_count: super::types::atomic_t,
    pub bd_fsfreeze_mutex: super::sync::mutex,
    pub bd_meta_info: *mut partition_meta_info,
    pub bd_writers: i32,
    pub bd_device: device,
}
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for block_device {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy)]
pub struct bvec_iter {
    pub _reserved: [u32; 4],
}
impl Default for bvec_iter {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct bvec_iter_all {
    pub _reserved: [u64; 3],
}
impl Default for bvec_iter_all {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct device {
    pub _reserved: [u64; 1],
}
impl Default for device {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "fs")]
#[derive(Clone, Copy)]
pub struct folio_batch {
    pub nr: u8,
    pub i: u8,
    pub percpu_pvec_drained: bool,
    pub folios: [*mut super::fs::folio; 31],
}
#[cfg(feature = "fs")]
impl Default for folio_batch {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "fs", feature = "types"))]
#[derive(Clone, Copy)]
pub struct folio_iter {
    pub folio: *mut super::fs::folio,
    pub offset: super::types::size_t,
    pub length: super::types::size_t,
    pub _next: *mut super::fs::folio,
    pub _seg_count: super::types::size_t,
    pub _i: i32,
}
#[cfg(all(feature = "fs", feature = "types"))]
impl Default for folio_iter {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct gendisk {
    pub _reserved: [u64; 1],
}
impl Default for gendisk {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct iomap {
    pub addr: u64,
    pub offset: super::types::loff_t,
    pub length: u64,
    pub r#type: u16,
    pub flags: u16,
    pub bdev: *mut block_device,
    pub dax_dev: *mut core::ffi::c_void,
    pub inline_data: *mut core::ffi::c_void,
    pub private: *mut core::ffi::c_void,
    pub validity_cookie: u64,
}
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for iomap {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct iomap_dio_ops {
    pub end_io: *mut isize,
    pub submit_io: *mut isize,
    pub bio_set: *mut bio_set,
}
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for iomap_dio_ops {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct iomap_ioend {
    pub io_list: super::types::list_head,
    pub io_flags: u16,
    pub io_inode: *mut super::fs::inode,
    pub io_size: super::types::size_t,
    pub io_remaining: super::types::atomic_t,
    pub io_error: i32,
    pub io_parent: *mut iomap_ioend,
    pub io_offset: super::types::loff_t,
    pub io_sector: super::types::sector_t,
    pub io_private: *mut core::ffi::c_void,
    pub io_bio: bio,
}
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for iomap_ioend {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct iomap_iter {
    pub inode: *mut super::fs::inode,
    pub pos: super::types::loff_t,
    pub len: u64,
    pub iter_start_pos: super::types::loff_t,
    pub status: i32,
    pub flags: u32,
    pub iomap: iomap,
    pub srcmap: iomap,
    pub fbatch: *mut folio_batch,
    pub private: *mut core::ffi::c_void,
}
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for iomap_iter {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct iomap_ops {
    pub iomap_begin: *mut isize,
    pub iomap_end: *mut isize,
}
impl Default for iomap_ops {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
pub type iomap_punch_t = Option<
    unsafe extern "system" fn(
        param0: *const super::fs::inode,
        param1: super::types::loff_t,
        param2: super::types::loff_t,
        param3: *const iomap,
    ),
>;
#[repr(C, packed(8))]
#[cfg(feature = "fs")]
#[derive(Clone, Copy)]
pub struct iomap_read_folio_ctx {
    pub ops: *mut iomap_read_ops,
    pub cur_folio: *mut super::fs::folio,
    pub rac: *mut core::ffi::c_void,
    pub read_ctx: *mut core::ffi::c_void,
}
#[cfg(feature = "fs")]
impl Default for iomap_read_folio_ctx {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct iomap_read_ops {
    pub read_folio_range: *mut isize,
    pub submit_read: *mut isize,
}
impl Default for iomap_read_ops {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct iomap_write_ops {
    pub get_folio: *mut isize,
    pub put_folio: *mut isize,
    pub iomap_valid: *mut isize,
    pub read_folio_range: *mut isize,
}
impl Default for iomap_write_ops {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct iomap_writeback_ops {
    pub writeback_range: *mut isize,
    pub writeback_submit: *mut isize,
}
impl Default for iomap_writeback_ops {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct iomap_writepage_ctx {
    pub iomap: iomap,
    pub inode: *mut super::fs::inode,
    pub wbc: *mut core::ffi::c_void,
    pub ops: *mut iomap_writeback_ops,
    pub nr_folios: u32,
    pub wb_ctx: *mut core::ffi::c_void,
}
#[cfg(all(
    feature = "dcache",
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for iomap_writepage_ctx {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct kobject {
    pub _reserved: [u64; 8],
}
impl Default for kobject {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct mempool {
    pub _reserved: [u64; 1],
}
impl Default for mempool {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct partition_meta_info {
    pub _reserved: [u64; 1],
}
impl Default for partition_meta_info {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct queue_limits {
    pub _reserved: [u64; 1],
}
impl Default for queue_limits {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type req_flag_bits = u32;
pub type req_op = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct request_queue {
    pub _reserved: [u64; 1],
}
impl Default for request_queue {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type stat_group = u32;
