// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(all(feature = "fs", feature = "sync", feature = "types", feature = "wait"))]
windows_link::link!("kernel" "C" fn __list_lru_init(lru : *mut list_lru, memcg_aware : bool, shrinker : *mut super::fs:: shrinker) -> i32);
windows_link::link!("kernel" "C" fn __llist_add(new : *mut llist_node, head : *mut llist_head) -> bool);
windows_link::link!("kernel" "C" fn __llist_add_batch(new_first : *mut llist_node, new_last : *mut llist_node, head : *mut llist_head) -> bool);
windows_link::link!("kernel" "C" fn __llist_del_all(head : *mut llist_head) -> *mut llist_node);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __mas_set_range(mas : *mut ma_state, start : u64, last : u64));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __mt_destroy(mt : *mut maple_tree));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __mt_dup(mt : *mut maple_tree, new : *mut maple_tree, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __xa_alloc(param0 : *mut xarray, id : *mut u32, entry : *mut core::ffi::c_void, param3 : xa_limit, param4 : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __xa_alloc_cyclic(param0 : *mut xarray, id : *mut u32, entry : *mut core::ffi::c_void, param3 : xa_limit, next : *mut u32, param5 : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __xa_clear_mark(param0 : *mut xarray, index : u64, param2 : xa_mark_t));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __xa_cmpxchg(param0 : *mut xarray, index : u64, old : *mut core::ffi::c_void, entry : *mut core::ffi::c_void, param4 : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __xa_erase(param0 : *mut xarray, index : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __xa_insert(param0 : *mut xarray, index : u64, entry : *mut core::ffi::c_void, param3 : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __xa_set_mark(param0 : *mut xarray, index : u64, param2 : xa_mark_t));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __xa_store(param0 : *mut xarray, index : u64, entry : *mut core::ffi::c_void, param3 : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __xas_next(param0 : *mut xa_state) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn __xas_prev(param0 : *mut xa_state) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn init_llist_head(list : *mut llist_head));
windows_link::link!("kernel" "C" fn init_llist_node(node : *mut llist_node));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_add(lru : *mut list_lru, item : *mut super::types:: list_head, nid : i32, memcg : *mut core::ffi::c_void) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_add_obj(lru : *mut list_lru, item : *mut super::types:: list_head) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_count(lru : *mut list_lru) -> u64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_count_node(lru : *mut list_lru, nid : i32) -> u64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_count_one(lru : *mut list_lru, nid : i32, memcg : *mut core::ffi::c_void) -> u64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_del(lru : *mut list_lru, item : *mut super::types:: list_head, nid : i32, memcg : *mut core::ffi::c_void) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_del_obj(lru : *mut list_lru, item : *mut super::types:: list_head) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_destroy(lru : *mut list_lru));
#[cfg(all(feature = "fs", feature = "sync", feature = "types", feature = "wait"))]
windows_link::link!("kernel" "C" fn list_lru_init_memcg_key(lru : *mut list_lru, shrinker : *mut super::fs:: shrinker, key : *mut super::fs:: lock_class_key) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_isolate(list : *mut list_lru_one, item : *mut super::types:: list_head));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_isolate_move(list : *mut list_lru_one, item : *mut super::types:: list_head, head : *mut super::types:: list_head));
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_shrink_count(lru : *mut list_lru, sc : *mut super::fs:: shrink_control) -> u64);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_shrink_walk(lru : *mut list_lru, sc : *mut super::fs:: shrink_control, isolate : list_lru_walk_cb, cb_arg : *mut core::ffi::c_void) -> u64);
#[cfg(all(feature = "fs", feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_shrink_walk_irq(lru : *mut list_lru, sc : *mut super::fs:: shrink_control, isolate : list_lru_walk_cb, cb_arg : *mut core::ffi::c_void) -> u64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_walk(lru : *mut list_lru, isolate : list_lru_walk_cb, cb_arg : *mut core::ffi::c_void, nr_to_walk : u64) -> u64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_walk_node(lru : *mut list_lru, nid : i32, isolate : list_lru_walk_cb, cb_arg : *mut core::ffi::c_void, nr_to_walk : *mut u64) -> u64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_walk_one(lru : *mut list_lru, nid : i32, memcg : *mut core::ffi::c_void, isolate : list_lru_walk_cb, cb_arg : *mut core::ffi::c_void, nr_to_walk : *mut u64) -> u64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn list_lru_walk_one_irq(lru : *mut list_lru, nid : i32, memcg : *mut core::ffi::c_void, isolate : list_lru_walk_cb, cb_arg : *mut core::ffi::c_void, nr_to_walk : *mut u64) -> u64);
windows_link::link!("kernel" "C" fn llist_add(new : *mut llist_node, head : *mut llist_head) -> bool);
windows_link::link!("kernel" "C" fn llist_add_batch(new_first : *mut llist_node, new_last : *mut llist_node, head : *mut llist_head) -> bool);
windows_link::link!("kernel" "C" fn llist_del_all(head : *mut llist_head) -> *mut llist_node);
windows_link::link!("kernel" "C" fn llist_del_first(head : *mut llist_head) -> *mut llist_node);
windows_link::link!("kernel" "C" fn llist_del_first_init(head : *mut llist_head) -> *mut llist_node);
windows_link::link!("kernel" "C" fn llist_del_first_this(head : *mut llist_head, this : *mut llist_node) -> bool);
windows_link::link!("kernel" "C" fn llist_empty(head : *const llist_head) -> bool);
windows_link::link!("kernel" "C" fn llist_next(node : *mut llist_node) -> *mut llist_node);
windows_link::link!("kernel" "C" fn llist_on_list(node : *const llist_node) -> bool);
windows_link::link!("kernel" "C" fn llist_reverse_order(head : *mut llist_node) -> *mut llist_node);
windows_link::link!("kernel" "C" fn maple_tree_init());
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_alloc_cyclic(mas : *mut ma_state, startp : *mut u64, entry : *mut core::ffi::c_void, range_lo : u64, range_hi : u64, next : *mut u64, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_destroy(mas : *mut ma_state));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_empty_area(mas : *mut ma_state, min : u64, max : u64, size : u64) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_empty_area_rev(mas : *mut ma_state, min : u64, max : u64, size : u64) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_erase(mas : *mut ma_state) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_find(mas : *mut ma_state, max : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_find_range(mas : *mut ma_state, max : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_find_range_rev(mas : *mut ma_state, max : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_find_rev(mas : *mut ma_state, min : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_init(mas : *mut ma_state, tree : *mut maple_tree, addr : u64));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_is_active(mas : *mut ma_state) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_is_err(mas : *mut ma_state) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_next(mas : *mut ma_state, max : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_next_range(mas : *mut ma_state, max : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_nomem(mas : *mut ma_state, gfp : super::types:: gfp_t) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_pause(mas : *mut ma_state));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_preallocate(mas : *mut ma_state, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_prev(mas : *mut ma_state, min : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_prev_range(mas : *mut ma_state, max : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_reset(mas : *mut ma_state));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_set(mas : *mut ma_state, index : u64));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_set_range(mas : *mut ma_state, start : u64, last : u64));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_store(mas : *mut ma_state, entry : *mut core::ffi::c_void) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_store_gfp(mas : *mut ma_state, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_store_prealloc(mas : *mut ma_state, entry : *mut core::ffi::c_void));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mas_walk(mas : *mut ma_state) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn memcg_list_lru_alloc(memcg : *mut core::ffi::c_void, lru : *mut list_lru, gfp : super::types:: gfp_t) -> i32);
windows_link::link!("kernel" "C" fn memcg_reparent_list_lrus(memcg : *mut core::ffi::c_void, parent : *mut core::ffi::c_void));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mt_clear_in_rcu(mt : *mut maple_tree));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mt_external_lock(mt : *const maple_tree) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mt_find(mt : *mut maple_tree, index : *mut u64, max : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mt_find_after(mt : *mut maple_tree, index : *mut u64, max : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mt_height(mt : *const maple_tree) -> u32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mt_in_rcu(mt : *mut maple_tree) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mt_init(mt : *mut maple_tree));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mt_init_flags(mt : *mut maple_tree, flags : u32));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mt_next(mt : *mut maple_tree, index : u64, max : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mt_prev(mt : *mut maple_tree, index : u64, min : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mt_set_in_rcu(mt : *mut maple_tree));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mtree_alloc_cyclic(mt : *mut maple_tree, startp : *mut u64, entry : *mut core::ffi::c_void, range_lo : u64, range_hi : u64, next : *mut u64, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mtree_alloc_range(mt : *mut maple_tree, startp : *mut u64, entry : *mut core::ffi::c_void, size : u64, min : u64, max : u64, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mtree_alloc_rrange(mt : *mut maple_tree, startp : *mut u64, entry : *mut core::ffi::c_void, size : u64, min : u64, max : u64, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mtree_destroy(mt : *mut maple_tree));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mtree_dup(mt : *mut maple_tree, new : *mut maple_tree, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mtree_empty(mt : *const maple_tree) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mtree_erase(mt : *mut maple_tree, index : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mtree_insert(mt : *mut maple_tree, index : u64, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mtree_insert_range(mt : *mut maple_tree, first : u64, last : u64, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mtree_load(mt : *mut maple_tree, index : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mtree_store(mt : *mut maple_tree, index : u64, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn mtree_store_range(mt : *mut maple_tree, first : u64, last : u64, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn rhashtable_init_noprof(ht : *mut rhashtable, params : *const rhashtable_params) -> i32);
#[cfg(all(
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn rhltable_init_noprof(hlt : *mut rhltable, params : *const rhashtable_params) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_alloc(xa : *mut xarray, id : *mut u32, entry : *mut core::ffi::c_void, limit : xa_limit, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_alloc_bh(xa : *mut xarray, id : *mut u32, entry : *mut core::ffi::c_void, limit : xa_limit, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_alloc_cyclic(xa : *mut xarray, id : *mut u32, entry : *mut core::ffi::c_void, limit : xa_limit, next : *mut u32, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_alloc_cyclic_bh(xa : *mut xarray, id : *mut u32, entry : *mut core::ffi::c_void, limit : xa_limit, next : *mut u32, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_alloc_cyclic_irq(xa : *mut xarray, id : *mut u32, entry : *mut core::ffi::c_void, limit : xa_limit, next : *mut u32, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_alloc_irq(xa : *mut xarray, id : *mut u32, entry : *mut core::ffi::c_void, limit : xa_limit, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_clear_mark(param0 : *mut xarray, index : u64, param2 : xa_mark_t));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_cmpxchg(xa : *mut xarray, index : u64, old : *mut core::ffi::c_void, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_cmpxchg_bh(xa : *mut xarray, index : u64, old : *mut core::ffi::c_void, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_cmpxchg_irq(xa : *mut xarray, index : u64, old : *mut core::ffi::c_void, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_delete_node(param0 : *mut xa_node, param1 : xa_update_node_t));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_destroy(param0 : *mut xarray));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_dump(param0 : *const xarray));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_dump_node(param0 : *const xa_node));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_empty(xa : *const xarray) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_entry(xa : *const xarray, node : *const xa_node, offset : u32) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_entry_locked(xa : *const xarray, node : *const xa_node, offset : u32) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_erase(param0 : *mut xarray, index : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_erase_bh(xa : *mut xarray, index : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_erase_irq(xa : *mut xarray, index : u64) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn xa_err(entry : *mut core::ffi::c_void) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_extract(param0 : *mut xarray, dst : *mut *mut core::ffi::c_void, start : u64, max : u64, n : u32, param5 : xa_mark_t) -> u32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_find(xa : *mut xarray, index : *mut u64, max : u64, param3 : xa_mark_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_find_after(xa : *mut xarray, index : *mut u64, max : u64, param3 : xa_mark_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_get_mark(param0 : *mut xarray, index : u64, param2 : xa_mark_t) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_get_order(xa : *mut xarray, index : u64) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_head(xa : *const xarray) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_head_locked(xa : *const xarray) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_init(xa : *mut xarray));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_init_flags(xa : *mut xarray, flags : super::types:: gfp_t));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_insert(xa : *mut xarray, index : u64, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_insert_bh(xa : *mut xarray, index : u64, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_insert_irq(xa : *mut xarray, index : u64, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> i32);
windows_link::link!("kernel" "C" fn xa_is_advanced(entry : *const core::ffi::c_void) -> bool);
windows_link::link!("kernel" "C" fn xa_is_err(entry : *const core::ffi::c_void) -> bool);
windows_link::link!("kernel" "C" fn xa_is_internal(entry : *const core::ffi::c_void) -> bool);
windows_link::link!("kernel" "C" fn xa_is_node(entry : *const core::ffi::c_void) -> bool);
windows_link::link!("kernel" "C" fn xa_is_retry(entry : *const core::ffi::c_void) -> bool);
windows_link::link!("kernel" "C" fn xa_is_sibling(entry : *const core::ffi::c_void) -> bool);
windows_link::link!("kernel" "C" fn xa_is_value(entry : *const core::ffi::c_void) -> bool);
windows_link::link!("kernel" "C" fn xa_is_zero(entry : *const core::ffi::c_void) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_load(param0 : *mut xarray, index : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_marked(xa : *const xarray, mark : xa_mark_t) -> bool);
windows_link::link!("kernel" "C" fn xa_mk_internal(v : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_mk_node(node : *const xa_node) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn xa_mk_sibling(offset : u32) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn xa_mk_value(v : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_parent(xa : *const xarray, node : *const xa_node) -> *mut xa_node);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_parent_locked(xa : *const xarray, node : *const xa_node) -> *mut xa_node);
windows_link::link!("kernel" "C" fn xa_pointer_tag(entry : *mut core::ffi::c_void) -> u32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_release(xa : *mut xarray, index : u64));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_reserve(xa : *mut xarray, index : u64, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_reserve_bh(xa : *mut xarray, index : u64, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_reserve_irq(xa : *mut xarray, index : u64, gfp : super::types:: gfp_t) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_set_mark(param0 : *mut xarray, index : u64, param2 : xa_mark_t));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_store(param0 : *mut xarray, index : u64, entry : *mut core::ffi::c_void, param3 : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_store_bh(xa : *mut xarray, index : u64, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_store_irq(xa : *mut xarray, index : u64, entry : *mut core::ffi::c_void, gfp : super::types:: gfp_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_store_range(param0 : *mut xarray, first : u64, last : u64, entry : *mut core::ffi::c_void, param4 : super::types:: gfp_t) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn xa_tag_pointer(p : *mut core::ffi::c_void, tag : u64) -> *mut core::ffi::c_void);
windows_link::link!("kernel" "C" fn xa_to_internal(entry : *const core::ffi::c_void) -> u64);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xa_to_node(entry : *const core::ffi::c_void) -> *mut xa_node);
windows_link::link!("kernel" "C" fn xa_to_sibling(entry : *const core::ffi::c_void) -> u64);
windows_link::link!("kernel" "C" fn xa_to_value(entry : *const core::ffi::c_void) -> u64);
windows_link::link!("kernel" "C" fn xa_untag_pointer(entry : *mut core::ffi::c_void) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_advance(xas : *mut xa_state, index : u64));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_clear_mark(param0 : *const xa_state, param1 : xa_mark_t));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_create_range(param0 : *mut xa_state));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_destroy(param0 : *mut xa_state));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_error(xas : *const xa_state) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_find(param0 : *mut xa_state, max : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_find_chunk(xas : *mut xa_state, advance : bool, mark : xa_mark_t) -> u32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_find_conflict(param0 : *mut xa_state) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_find_marked(param0 : *mut xa_state, max : u64, param2 : xa_mark_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_frozen(node : *mut xa_node) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_get_mark(param0 : *const xa_state, param1 : xa_mark_t) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_get_order(xas : *mut xa_state) -> i32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_init_marks(param0 : *const xa_state));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_invalid(xas : *const xa_state) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_is_node(xas : *const xa_state) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_load(param0 : *mut xa_state) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_next(xas : *mut xa_state) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_next_entry(xas : *mut xa_state, max : u64) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_next_marked(xas : *mut xa_state, max : u64, mark : xa_mark_t) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_nomem(param0 : *mut xa_state, param1 : super::types:: gfp_t) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_not_node(node : *mut xa_node) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_pause(param0 : *mut xa_state));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_prev(xas : *mut xa_state) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_reload(xas : *mut xa_state) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_reset(xas : *mut xa_state));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_retry(xas : *mut xa_state, entry : *const core::ffi::c_void) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_set(xas : *mut xa_state, index : u64));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_set_err(xas : *mut xa_state, err : i64));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_set_lru(xas : *mut xa_state, lru : *mut list_lru));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_set_mark(param0 : *const xa_state, param1 : xa_mark_t));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_set_order(xas : *mut xa_state, index : u64, order : u32));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_set_update(xas : *mut xa_state, update : xa_update_node_t));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_split(xas : *mut xa_state, entry : *mut core::ffi::c_void, order : u32));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_split_alloc(xas : *mut xa_state, entry : *mut core::ffi::c_void, order : u32, gfp : super::types:: gfp_t));
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_store(param0 : *mut xa_state, entry : *mut core::ffi::c_void) -> *mut core::ffi::c_void);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_top(node : *mut xa_node) -> bool);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_try_split(xas : *mut xa_state, entry : *mut core::ffi::c_void, order : u32));
windows_link::link!("kernel" "C" fn xas_try_split_min_order(order : u32) -> u32);
#[cfg(all(feature = "sync", feature = "types"))]
windows_link::link!("kernel" "C" fn xas_valid(xas : *const xa_state) -> bool);
pub const LRU_REMOVED: u32 = 0u32;
pub const LRU_REMOVED_RETRY: u32 = 1u32;
pub const LRU_RETRY: u32 = 4u32;
pub const LRU_ROTATE: u32 = 2u32;
pub const LRU_SKIP: u32 = 3u32;
pub const LRU_STOP: u32 = 5u32;
pub const MAPLE_ARANGE64_SLOTS: i32 = 10i32;
pub const MAPLE_HEIGHT_MAX: i32 = 31i32;
pub const MAPLE_NODE_MASK: i32 = 255i32;
pub const MAPLE_NODE_SLOTS: i32 = 31i32;
pub const MAPLE_NODE_TYPE_MASK: i32 = 15i32;
pub const MAPLE_NODE_TYPE_SHIFT: i32 = 3i32;
pub const MAPLE_RANGE64_SLOTS: i32 = 16i32;
pub const MAPLE_RESERVED_RANGE: i32 = 4096i32;
pub const MT_FLAGS_ALLOC_RANGE: i32 = 1i32;
pub const MT_FLAGS_ALLOC_WRAPPED: i32 = 2048i32;
pub const MT_FLAGS_HEIGHT_MASK: i32 = 124i32;
pub const MT_FLAGS_HEIGHT_OFFSET: i32 = 2i32;
pub const MT_FLAGS_LOCK_BH: i32 = 512i32;
pub const MT_FLAGS_LOCK_EXTERN: i32 = 768i32;
pub const MT_FLAGS_LOCK_IRQ: i32 = 256i32;
pub const MT_FLAGS_LOCK_MASK: i32 = 768i32;
pub const MT_FLAGS_USE_RCU: i32 = 2i32;
pub const XA_CHECK_SCHED: u32 = 4096u32;
pub const XA_LOCK_BH: u32 = 2u32;
pub const XA_LOCK_IRQ: u32 = 1u32;
pub const XA_MAX_MARKS: i32 = 3i32;
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct list_lru {
    pub node: *mut list_lru_node,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for list_lru {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct list_lru_memcg {
    pub rcu: super::types::callback_head,
    pub node: *mut list_lru_one,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for list_lru_memcg {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(64))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct list_lru_node {
    pub lru: list_lru_one,
    pub nr_items: super::types::atomic64_t,
    pub _padding: [u8; 24],
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for list_lru_node {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct list_lru_one {
    pub list: super::types::list_head,
    pub nr_items: i64,
    pub lock: super::sync::spinlock_t,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for list_lru_one {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[cfg(all(feature = "sync", feature = "types"))]
pub type list_lru_walk_cb = Option<
    unsafe extern "system" fn(
        param0: *const super::types::list_head,
        param1: *const list_lru_one,
        param2: *const core::ffi::c_void,
    ) -> lru_status,
>;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct llist_head {
    pub first: *mut llist_node,
}
impl Default for llist_head {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct llist_node {
    pub next: *mut llist_node,
}
impl Default for llist_node {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type lru_status = u32;
pub const ma_active: u32 = 0u32;
pub const ma_error: u32 = 7u32;
pub const ma_none: u32 = 3u32;
pub const ma_overflow: u32 = 5u32;
pub const ma_pause: u32 = 4u32;
pub const ma_root: u32 = 2u32;
pub const ma_start: u32 = 1u32;
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct ma_state {
    pub tree: *mut maple_tree,
    pub index: u64,
    pub last: u64,
    pub node: *mut core::ffi::c_void,
    pub min: u64,
    pub max: u64,
    pub sheaf: *mut core::ffi::c_void,
    pub alloc: *mut maple_node,
    pub node_request: u64,
    pub status: maple_status,
    pub depth: u8,
    pub offset: u8,
    pub mas_flags: u8,
    pub end: u8,
    pub store_type: store_type,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for ma_state {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct ma_topiary {
    pub head: *mut core::ffi::c_void,
    pub tail: *mut core::ffi::c_void,
    pub mtree: *mut maple_tree,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for ma_topiary {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const ma_underflow: u32 = 6u32;
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct ma_wr_state {
    pub mas: *mut ma_state,
    pub node: *mut maple_node,
    pub r_min: u64,
    pub r_max: u64,
    pub r#type: maple_type,
    pub offset_end: u8,
    pub pivots: *mut u64,
    pub end_piv: u64,
    pub slots: *mut *mut core::ffi::c_void,
    pub entry: *mut core::ffi::c_void,
    pub content: *mut core::ffi::c_void,
    pub vacant_height: u8,
    pub sufficient_height: u8,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for ma_wr_state {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct maple_arange_64 {
    pub parent: *mut core::ffi::c_void,
    pub pivot: [u64; 9],
    pub slot: [*mut core::ffi::c_void; 10],
    pub gap: [u64; 10],
    pub meta: maple_metadata,
}
impl Default for maple_arange_64 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const maple_arange_64: u32 = 3u32;
pub const maple_dense: u32 = 0u32;
pub const maple_leaf_64: u32 = 1u32;
#[repr(C, packed(1))]
#[derive(Clone, Copy, Default)]
pub struct maple_metadata {
    pub end: u8,
    pub gap: u8,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct maple_node {
    pub maple_node__anon_0: maple_node__anon_0,
}
#[cfg(feature = "types")]
impl Default for maple_node {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union maple_node__anon_0 {
    pub maple_node__anon_0__anon_0: maple_node__anon_0__anon_0,
    pub maple_node__anon_0__anon_1: maple_node__anon_0__anon_1,
    pub mr64: maple_range_64,
    pub ma64: maple_arange_64,
}
#[cfg(feature = "types")]
impl Default for maple_node__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct maple_node__anon_0__anon_0 {
    pub parent: *mut core::ffi::c_void,
    pub slot: [*mut core::ffi::c_void; 31],
}
impl Default for maple_node__anon_0__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct maple_node__anon_0__anon_1 {
    pub pad: *mut core::ffi::c_void,
    pub rcu: super::types::callback_head,
    pub piv_parent: *mut core::ffi::c_void,
    pub parent_slot: u8,
    pub r#type: maple_type,
    pub slot_len: u8,
    pub ma_flags: u32,
}
#[cfg(feature = "types")]
impl Default for maple_node__anon_0__anon_1 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct maple_range_64 {
    pub parent: *mut core::ffi::c_void,
    pub pivot: [u64; 15],
    pub maple_range_64__anon_0: maple_range_64__anon_0,
}
impl Default for maple_range_64 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const maple_range_64: u32 = 2u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union maple_range_64__anon_0 {
    pub slot: [*mut core::ffi::c_void; 16],
    pub maple_range_64__anon_0__anon_0: maple_range_64__anon_0__anon_0,
}
impl Default for maple_range_64__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct maple_range_64__anon_0__anon_0 {
    pub pad: [*mut core::ffi::c_void; 15],
    pub meta: maple_metadata,
}
impl Default for maple_range_64__anon_0__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type maple_status = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct maple_topiary {
    pub parent: *mut core::ffi::c_void,
    pub next: *mut core::ffi::c_void,
}
impl Default for maple_topiary {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct maple_tree {
    pub maple_tree__anon_0: maple_tree__anon_0,
    pub ma_flags: u32,
    pub ma_root: *mut core::ffi::c_void,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for maple_tree {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub union maple_tree__anon_0 {
    pub ma_lock: super::sync::spinlock_t,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for maple_tree__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type maple_type = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rb_node {
    pub __rb_parent_color: u64,
    pub rb_right: *mut rb_node,
    pub rb_left: *mut rb_node,
}
impl Default for rb_node {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rb_root {
    pub rb_node: *mut rb_node,
}
impl Default for rb_root {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rb_root_cached {
    pub rb_root: rb_root,
    pub rb_leftmost: *mut rb_node,
}
impl Default for rb_root_cached {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rhash_head {
    pub next: *mut rhash_head,
}
impl Default for rhash_head {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct rhashtable {
    pub tbl: *mut core::ffi::c_void,
    pub key_len: u32,
    pub max_elems: u32,
    pub p: rhashtable_params,
    pub rhlist: bool,
    pub run_work: super::workqueue::work_struct,
    pub mutex: super::sync::mutex,
    pub lock: super::sync::spinlock_t,
    pub nelems: super::types::atomic_t,
}
#[cfg(all(
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for rhashtable {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct rhashtable_compare_arg {
    pub ht: *mut rhashtable,
    pub key: *mut core::ffi::c_void,
}
#[cfg(all(
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for rhashtable_compare_arg {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct rhashtable_iter {
    pub ht: *mut rhashtable,
    pub p: *mut rhash_head,
    pub list: *mut rhlist_head,
    pub walker: rhashtable_walker,
    pub slot: u32,
    pub skip: u32,
    pub end_of_table: bool,
}
#[cfg(all(
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for rhashtable_iter {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy, Default)]
pub struct rhashtable_params {
    pub nelem_hint: u16,
    pub key_len: u16,
    pub key_offset: u16,
    pub head_offset: u16,
    pub max_size: u32,
    pub min_size: u16,
    pub automatic_shrinking: bool,
    pub hashfn: rht_hashfn_t,
    pub obj_hashfn: rht_obj_hashfn_t,
    pub obj_cmpfn: rht_obj_cmpfn_t,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct rhashtable_walker {
    pub list: super::types::list_head,
    pub tbl: *mut core::ffi::c_void,
}
#[cfg(feature = "types")]
impl Default for rhashtable_walker {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rhlist_head {
    pub rhead: rhash_head,
    pub next: *mut rhlist_head,
}
impl Default for rhlist_head {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct rhltable {
    pub ht: rhashtable,
}
#[cfg(all(
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
impl Default for rhltable {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type rht_hashfn_t = Option<
    unsafe extern "system" fn(param0: *const core::ffi::c_void, param1: u32, param2: u32) -> u32,
>;
#[cfg(all(
    feature = "fs",
    feature = "sync",
    feature = "types",
    feature = "workqueue"
))]
pub type rht_obj_cmpfn_t = Option<
    unsafe extern "system" fn(
        param0: *const rhashtable_compare_arg,
        param1: *const core::ffi::c_void,
    ) -> i32,
>;
pub type rht_obj_hashfn_t = Option<
    unsafe extern "system" fn(param0: *const core::ffi::c_void, param1: u32, param2: u32) -> u32,
>;
pub type store_type = u32;
pub const wr_append: u32 = 7u32;
pub const wr_exact_fit: u32 = 3u32;
pub const wr_invalid: u32 = 0u32;
pub const wr_new_root: u32 = 1u32;
pub const wr_node_store: u32 = 8u32;
pub const wr_rebalance: u32 = 6u32;
pub const wr_slot_store: u32 = 9u32;
pub const wr_spanning_store: u32 = 4u32;
pub const wr_split_store: u32 = 5u32;
pub const wr_store_root: u32 = 2u32;
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct xa_limit {
    pub max: u32,
    pub min: u32,
}
pub type xa_lock_type = u32;
pub type xa_mark_t = u32;
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct xa_node {
    pub shift: u8,
    pub offset: u8,
    pub count: u8,
    pub nr_values: u8,
    pub parent: *mut xa_node,
    pub array: *mut xarray,
    pub xa_node__anon_0: xa_node__anon_0,
    pub slots: [*mut core::ffi::c_void; 64],
    pub xa_node__anon_1: xa_node__anon_1,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for xa_node {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union xa_node__anon_0 {
    pub private_list: super::types::list_head,
    pub callback_head: super::types::callback_head,
}
#[cfg(feature = "types")]
impl Default for xa_node__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union xa_node__anon_1 {
    pub tags: [[u64; 1]; 1],
    pub marks: [[u64; 1]; 1],
}
impl Default for xa_node__anon_1 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct xa_state {
    pub xa: *mut xarray,
    pub xa_index: u64,
    pub xa_shift: u8,
    pub xa_sibs: u8,
    pub xa_offset: u8,
    pub xa_pad: u8,
    pub xa_node: *mut xa_node,
    pub xa_alloc: *mut xa_node,
    pub xa_update: xa_update_node_t,
    pub xa_lru: *mut list_lru,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for xa_state {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[cfg(all(feature = "sync", feature = "types"))]
pub type xa_update_node_t = Option<unsafe extern "system" fn(param0: *const xa_node)>;
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct xarray {
    pub xa_lock: super::sync::spinlock_t,
    pub xa_flags: super::types::gfp_t,
    pub xa_head: *mut core::ffi::c_void,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for xarray {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
