// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __io_uring_cmd_do_in_task(ioucmd : *mut io_uring_cmd, task_work_cb : io_req_tw_func_t, flags : u32));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn __io_uring_cmd_done(cmd : *mut io_uring_cmd, ret : i32, res2 : u64, issue_flags : u32, is_cqe32 : bool));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn cmd_to_io_kiocb(ptr : *mut core::ffi::c_void) -> *mut io_kiocb);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_buffer_register_bvec(cmd : *mut io_uring_cmd, rq : *mut request, release : *mut isize, index : u32, issue_flags : u32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_buffer_unregister_bvec(cmd : *mut io_uring_cmd, index : u32, issue_flags : u32) -> i32);
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn io_kiocb_cmd_sz_check(cmd_sz : super::types:: size_t));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_cmd_buffer_select(ioucmd : *mut io_uring_cmd, buf_group : u32, len : *mut super::types:: size_t, issue_flags : u32) -> io_br_sel);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_cmd_complete_in_task(ioucmd : *mut io_uring_cmd, task_work_cb : io_req_tw_func_t));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_cmd_ctx_handle(cmd : *mut io_uring_cmd) -> *mut core::ffi::c_void);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_cmd_do_in_task_lazy(ioucmd : *mut io_uring_cmd, task_work_cb : io_req_tw_func_t));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_cmd_done(ioucmd : *mut io_uring_cmd, ret : i32, issue_flags : u32));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_cmd_done32(ioucmd : *mut io_uring_cmd, ret : i32, res2 : u64, issue_flags : u32));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_cmd_from_tw(tw_req : io_tw_req) -> *mut io_uring_cmd);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_cmd_get_task(cmd : *mut io_uring_cmd) -> *mut super::fs:: task_struct);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "net",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_cmd_import_fixed(ubuf : u64, len : u64, rw : i32, iter : *mut super::net:: iov_iter, ioucmd : *mut io_uring_cmd, issue_flags : u32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "net",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_cmd_import_fixed_vec(ioucmd : *mut io_uring_cmd, uvec : *const super::net:: iovec, uvec_segs : super::types:: size_t, ddir : i32, iter : *mut super::net:: iov_iter, issue_flags : u32) -> i32);
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_cmd_issue_blocking(ioucmd : *mut io_uring_cmd));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_cmd_mark_cancelable(cmd : *mut io_uring_cmd, issue_flags : u32));
#[cfg(feature = "types")]
windows_link::link!("kernel" "C" fn io_uring_cmd_private_sz_check(cmd_sz : super::types:: size_t));
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
windows_link::link!("kernel" "C" fn io_uring_mshot_cmd_post_cqe(ioucmd : *mut io_uring_cmd, sel : *mut io_br_sel, issue_flags : u32) -> bool);
pub const IORING_CQE_BUFFER_SHIFT: i32 = 16i32;
pub const IORING_MEM_REGION_REG_WAIT_ARG: u32 = 1u32;
pub const IORING_MEM_REGION_TYPE_USER: u32 = 1u32;
pub const IORING_MSG_DATA: u32 = 0u32;
pub const IORING_MSG_SEND_FD: u32 = 1u32;
pub const IORING_OFF_CQ_RING: i32 = 134217728i32;
pub const IORING_OFF_MMAP_MASK: i32 = -134217728i32;
pub const IORING_OFF_PBUF_RING: i32 = -2147483648i32;
pub const IORING_OFF_PBUF_SHIFT: i32 = 16i32;
pub const IORING_OFF_SQES: i32 = 268435456i32;
pub const IORING_OFF_SQ_RING: i32 = 0i32;
pub const IORING_OP_ACCEPT: u32 = 13u32;
pub const IORING_OP_ASYNC_CANCEL: u32 = 14u32;
pub const IORING_OP_BIND: u32 = 56u32;
pub const IORING_OP_CLOSE: u32 = 19u32;
pub const IORING_OP_CONNECT: u32 = 16u32;
pub const IORING_OP_EPOLL_CTL: u32 = 29u32;
pub const IORING_OP_EPOLL_WAIT: u32 = 59u32;
pub const IORING_OP_FADVISE: u32 = 24u32;
pub const IORING_OP_FALLOCATE: u32 = 17u32;
pub const IORING_OP_FGETXATTR: u32 = 43u32;
pub const IORING_OP_FILES_UPDATE: u32 = 20u32;
pub const IORING_OP_FIXED_FD_INSTALL: u32 = 54u32;
pub const IORING_OP_FSETXATTR: u32 = 41u32;
pub const IORING_OP_FSYNC: u32 = 3u32;
pub const IORING_OP_FTRUNCATE: u32 = 55u32;
pub const IORING_OP_FUTEX_WAIT: u32 = 51u32;
pub const IORING_OP_FUTEX_WAITV: u32 = 53u32;
pub const IORING_OP_FUTEX_WAKE: u32 = 52u32;
pub const IORING_OP_GETXATTR: u32 = 44u32;
pub const IORING_OP_LAST: u32 = 65u32;
pub const IORING_OP_LINKAT: u32 = 39u32;
pub const IORING_OP_LINK_TIMEOUT: u32 = 15u32;
pub const IORING_OP_LISTEN: u32 = 57u32;
pub const IORING_OP_MADVISE: u32 = 25u32;
pub const IORING_OP_MKDIRAT: u32 = 37u32;
pub const IORING_OP_MSG_RING: u32 = 40u32;
pub const IORING_OP_NOP: u32 = 0u32;
pub const IORING_OP_NOP128: u32 = 63u32;
pub const IORING_OP_OPENAT: u32 = 18u32;
pub const IORING_OP_OPENAT2: u32 = 28u32;
pub const IORING_OP_PIPE: u32 = 62u32;
pub const IORING_OP_POLL_ADD: u32 = 6u32;
pub const IORING_OP_POLL_REMOVE: u32 = 7u32;
pub const IORING_OP_PROVIDE_BUFFERS: u32 = 31u32;
pub const IORING_OP_READ: u32 = 22u32;
pub const IORING_OP_READV: u32 = 1u32;
pub const IORING_OP_READV_FIXED: u32 = 60u32;
pub const IORING_OP_READ_FIXED: u32 = 4u32;
pub const IORING_OP_READ_MULTISHOT: u32 = 49u32;
pub const IORING_OP_RECV: u32 = 27u32;
pub const IORING_OP_RECVMSG: u32 = 10u32;
pub const IORING_OP_RECV_ZC: u32 = 58u32;
pub const IORING_OP_REMOVE_BUFFERS: u32 = 32u32;
pub const IORING_OP_RENAMEAT: u32 = 35u32;
pub const IORING_OP_SEND: u32 = 26u32;
pub const IORING_OP_SENDMSG: u32 = 9u32;
pub const IORING_OP_SENDMSG_ZC: u32 = 48u32;
pub const IORING_OP_SEND_ZC: u32 = 47u32;
pub const IORING_OP_SETXATTR: u32 = 42u32;
pub const IORING_OP_SHUTDOWN: u32 = 34u32;
pub const IORING_OP_SOCKET: u32 = 45u32;
pub const IORING_OP_SPLICE: u32 = 30u32;
pub const IORING_OP_STATX: u32 = 21u32;
pub const IORING_OP_SYMLINKAT: u32 = 38u32;
pub const IORING_OP_SYNC_FILE_RANGE: u32 = 8u32;
pub const IORING_OP_TEE: u32 = 33u32;
pub const IORING_OP_TIMEOUT: u32 = 11u32;
pub const IORING_OP_TIMEOUT_REMOVE: u32 = 12u32;
pub const IORING_OP_UNLINKAT: u32 = 36u32;
pub const IORING_OP_URING_CMD: u32 = 46u32;
pub const IORING_OP_URING_CMD128: u32 = 64u32;
pub const IORING_OP_WAITID: u32 = 50u32;
pub const IORING_OP_WRITE: u32 = 23u32;
pub const IORING_OP_WRITEV: u32 = 2u32;
pub const IORING_OP_WRITEV_FIXED: u32 = 61u32;
pub const IORING_OP_WRITE_FIXED: u32 = 5u32;
pub const IORING_REGISTER_BPF_FILTER: u32 = 37u32;
pub const IORING_REGISTER_BUFFERS: u32 = 0u32;
pub const IORING_REGISTER_BUFFERS2: u32 = 15u32;
pub const IORING_REGISTER_BUFFERS_UPDATE: u32 = 16u32;
pub const IORING_REGISTER_CLOCK: u32 = 29u32;
pub const IORING_REGISTER_CLONE_BUFFERS: u32 = 30u32;
pub const IORING_REGISTER_DST_REPLACE: u32 = 2u32;
pub const IORING_REGISTER_ENABLE_RINGS: u32 = 12u32;
pub const IORING_REGISTER_EVENTFD: u32 = 4u32;
pub const IORING_REGISTER_EVENTFD_ASYNC: u32 = 7u32;
pub const IORING_REGISTER_FILES: u32 = 2u32;
pub const IORING_REGISTER_FILES2: u32 = 13u32;
pub const IORING_REGISTER_FILES_UPDATE: u32 = 6u32;
pub const IORING_REGISTER_FILES_UPDATE2: u32 = 14u32;
pub const IORING_REGISTER_FILE_ALLOC_RANGE: u32 = 25u32;
pub const IORING_REGISTER_IOWQ_AFF: u32 = 17u32;
pub const IORING_REGISTER_IOWQ_MAX_WORKERS: u32 = 19u32;
pub const IORING_REGISTER_LAST: u32 = 38u32;
pub const IORING_REGISTER_MEM_REGION: u32 = 34u32;
pub const IORING_REGISTER_NAPI: u32 = 27u32;
pub const IORING_REGISTER_PBUF_RING: u32 = 22u32;
pub const IORING_REGISTER_PBUF_STATUS: u32 = 26u32;
pub const IORING_REGISTER_PERSONALITY: u32 = 9u32;
pub const IORING_REGISTER_PROBE: u32 = 8u32;
pub const IORING_REGISTER_QUERY: u32 = 35u32;
pub const IORING_REGISTER_RESIZE_RINGS: u32 = 33u32;
pub const IORING_REGISTER_RESTRICTIONS: u32 = 11u32;
pub const IORING_REGISTER_RING_FDS: u32 = 20u32;
pub const IORING_REGISTER_SEND_MSG_RING: u32 = 31u32;
pub const IORING_REGISTER_SRC_REGISTERED: u32 = 1u32;
pub const IORING_REGISTER_SYNC_CANCEL: u32 = 24u32;
pub const IORING_REGISTER_USE_REGISTERED_RING: u32 = 2147483648u32;
pub const IORING_REGISTER_ZCRX_CTRL: u32 = 36u32;
pub const IORING_REGISTER_ZCRX_IFQ: u32 = 32u32;
pub const IORING_REG_WAIT_TS: u32 = 1u32;
pub const IORING_RESTRICTION_LAST: u32 = 4u32;
pub const IORING_RESTRICTION_REGISTER_OP: u32 = 0u32;
pub const IORING_RESTRICTION_SQE_FLAGS_ALLOWED: u32 = 2u32;
pub const IORING_RESTRICTION_SQE_FLAGS_REQUIRED: u32 = 3u32;
pub const IORING_RESTRICTION_SQE_OP: u32 = 1u32;
pub const IORING_TIMESTAMP_HW_SHIFT: i32 = 16i32;
pub const IORING_UNREGISTER_BUFFERS: u32 = 1u32;
pub const IORING_UNREGISTER_EVENTFD: u32 = 5u32;
pub const IORING_UNREGISTER_FILES: u32 = 3u32;
pub const IORING_UNREGISTER_IOWQ_AFF: u32 = 18u32;
pub const IORING_UNREGISTER_NAPI: u32 = 28u32;
pub const IORING_UNREGISTER_PBUF_RING: u32 = 23u32;
pub const IORING_UNREGISTER_PERSONALITY: u32 = 10u32;
pub const IORING_UNREGISTER_RING_FDS: u32 = 21u32;
pub const IORING_ZCRX_AREA_DMABUF: u32 = 1u32;
pub const IORING_ZCRX_AREA_SHIFT: i32 = 48i32;
pub const IOSQE_ASYNC_BIT: u32 = 4u32;
pub const IOSQE_BUFFER_SELECT_BIT: u32 = 5u32;
pub const IOSQE_CQE_SKIP_SUCCESS_BIT: u32 = 6u32;
pub const IOSQE_FIXED_FILE_BIT: u32 = 0u32;
pub const IOSQE_IO_DRAIN_BIT: u32 = 1u32;
pub const IOSQE_IO_HARDLINK_BIT: u32 = 3u32;
pub const IOSQE_IO_LINK_BIT: u32 = 2u32;
pub const IOU_F_TWQ_LAZY_WAKE: u32 = 1u32;
pub const IOU_PBUF_RING_INC: u32 = 2u32;
pub const IOU_PBUF_RING_MMAP: u32 = 1u32;
pub const IO_RINGFD_REG_MAX: i32 = 16i32;
pub const IO_URING_F_CANCEL: i32 = 2048i32;
pub const IO_URING_F_COMPAT: i32 = 4096i32;
pub const IO_URING_F_COMPLETE_DEFER: i32 = 1i32;
pub const IO_URING_F_CQE32: i32 = 512i32;
pub const IO_URING_F_INLINE: i32 = 16i32;
pub const IO_URING_F_IOPOLL: i32 = 1024i32;
pub const IO_URING_F_IOWQ: i32 = 8i32;
pub const IO_URING_F_MULTISHOT: i32 = 4i32;
pub const IO_URING_F_NONBLOCK: i32 = -2147483648i32;
pub const IO_URING_F_SQE128: i32 = 256i32;
pub const IO_URING_F_UNLOCKED: i32 = 2i32;
pub const IO_URING_NAPI_REGISTER_OP: u32 = 0u32;
pub const IO_URING_NAPI_STATIC_ADD_ID: u32 = 1u32;
pub const IO_URING_NAPI_STATIC_DEL_ID: u32 = 2u32;
pub const IO_URING_NAPI_TRACKING_DYNAMIC: u32 = 0u32;
pub const IO_URING_NAPI_TRACKING_INACTIVE: u32 = 255u32;
pub const IO_URING_NAPI_TRACKING_STATIC: u32 = 1u32;
pub const IO_WQ_BOUND: u32 = 0u32;
pub const IO_WQ_UNBOUND: u32 = 1u32;
pub const REQ_F_APOLL_MULTISHOT: u32 = 134217728u32;
pub const REQ_F_APOLL_MULTISHOT_BIT: u32 = 27u32;
pub const REQ_F_ARM_LTIMEOUT: u32 = 2097152u32;
pub const REQ_F_ARM_LTIMEOUT_BIT: u32 = 21u32;
pub const REQ_F_ASYNC_DATA: u32 = 4194304u32;
pub const REQ_F_ASYNC_DATA_BIT: u32 = 22u32;
pub const REQ_F_BL_EMPTY: u64 = 8589934592u64;
pub const REQ_F_BL_EMPTY_BIT: u32 = 33u32;
pub const REQ_F_BL_NO_RECYCLE: u64 = 17179869184u64;
pub const REQ_F_BL_NO_RECYCLE_BIT: u32 = 34u32;
pub const REQ_F_BUFFERS_COMMIT: u64 = 34359738368u64;
pub const REQ_F_BUFFERS_COMMIT_BIT: u32 = 35u32;
pub const REQ_F_BUFFER_RING: u32 = 131072u32;
pub const REQ_F_BUFFER_RING_BIT: u32 = 17u32;
pub const REQ_F_BUFFER_SELECT: u32 = 32u32;
pub const REQ_F_BUFFER_SELECTED: u32 = 65536u32;
pub const REQ_F_BUFFER_SELECTED_BIT: u32 = 16u32;
pub const REQ_F_BUFFER_SELECT_BIT: u32 = 5u32;
pub const REQ_F_BUF_MORE: u64 = 137438953472u64;
pub const REQ_F_BUF_MORE_BIT: u32 = 37u32;
pub const REQ_F_BUF_NODE: u64 = 68719476736u64;
pub const REQ_F_BUF_NODE_BIT: u32 = 36u32;
pub const REQ_F_CAN_POLL: u64 = 4294967296u64;
pub const REQ_F_CAN_POLL_BIT: u32 = 32u32;
pub const REQ_F_CLEAR_POLLIN: u32 = 268435456u32;
pub const REQ_F_CLEAR_POLLIN_BIT: u32 = 28u32;
pub const REQ_F_CQE_SKIP: u32 = 64u32;
pub const REQ_F_CQE_SKIP_BIT: u32 = 6u32;
pub const REQ_F_CREDS: u32 = 524288u32;
pub const REQ_F_CREDS_BIT: u32 = 19u32;
pub const REQ_F_CUR_POS: u32 = 1024u32;
pub const REQ_F_CUR_POS_BIT: u32 = 10u32;
pub const REQ_F_DOUBLE_POLL: u32 = 33554432u32;
pub const REQ_F_DOUBLE_POLL_BIT: u32 = 25u32;
pub const REQ_F_FAIL: u32 = 256u32;
pub const REQ_F_FAIL_BIT: u32 = 8u32;
pub const REQ_F_FIXED_FILE: u32 = 1u32;
pub const REQ_F_FIXED_FILE_BIT: u32 = 0u32;
pub const REQ_F_FORCE_ASYNC: u32 = 16u32;
pub const REQ_F_FORCE_ASYNC_BIT: u32 = 4u32;
pub const REQ_F_HARDLINK: u32 = 8u32;
pub const REQ_F_HARDLINK_BIT: u32 = 3u32;
pub const REQ_F_HAS_METADATA: u64 = 274877906944u64;
pub const REQ_F_HAS_METADATA_BIT: u32 = 38u32;
pub const REQ_F_HYBRID_IOPOLL_STATE_BIT: u32 = 15u32;
pub const REQ_F_IMPORT_BUFFER: u64 = 549755813888u64;
pub const REQ_F_IMPORT_BUFFER_BIT: u32 = 39u32;
pub const REQ_F_INFLIGHT: u32 = 512u32;
pub const REQ_F_INFLIGHT_BIT: u32 = 9u32;
pub const REQ_F_IOPOLL_STATE: u32 = 32768u32;
pub const REQ_F_IO_DRAIN: u32 = 2u32;
pub const REQ_F_IO_DRAIN_BIT: u32 = 1u32;
pub const REQ_F_ISREG: u32 = 1073741824u32;
pub const REQ_F_ISREG_BIT: u32 = 30u32;
pub const REQ_F_LINK: u32 = 4u32;
pub const REQ_F_LINK_BIT: u32 = 2u32;
pub const REQ_F_LINK_TIMEOUT: u32 = 4096u32;
pub const REQ_F_LINK_TIMEOUT_BIT: u32 = 12u32;
pub const REQ_F_MULTISHOT: u32 = 67108864u32;
pub const REQ_F_MULTISHOT_BIT: u32 = 26u32;
pub const REQ_F_NEED_CLEANUP: u32 = 8192u32;
pub const REQ_F_NEED_CLEANUP_BIT: u32 = 13u32;
pub const REQ_F_NOWAIT: u32 = 2048u32;
pub const REQ_F_NOWAIT_BIT: u32 = 11u32;
pub const REQ_F_POLLED: u32 = 16384u32;
pub const REQ_F_POLLED_BIT: u32 = 14u32;
pub const REQ_F_POLL_NO_LAZY: u32 = 2147483648u32;
pub const REQ_F_POLL_NO_LAZY_BIT: u32 = 31u32;
pub const REQ_F_REFCOUNT: u32 = 1048576u32;
pub const REQ_F_REFCOUNT_BIT: u32 = 20u32;
pub const REQ_F_REISSUE: u32 = 262144u32;
pub const REQ_F_REISSUE_BIT: u32 = 18u32;
pub const REQ_F_SINGLE_POLL: u32 = 16777216u32;
pub const REQ_F_SINGLE_POLL_BIT: u32 = 24u32;
pub const REQ_F_SKIP_LINK_CQES: u32 = 8388608u32;
pub const REQ_F_SKIP_LINK_CQES_BIT: u32 = 23u32;
pub const REQ_F_SQE_COPIED: u64 = 1099511627776u64;
pub const REQ_F_SQE_COPIED_BIT: u32 = 40u32;
pub const REQ_F_SUPPORT_NOWAIT: u32 = 536870912u32;
pub const REQ_F_SUPPORT_NOWAIT_BIT: u32 = 29u32;
pub const SOCKET_URING_OP_GETSOCKNAME: u32 = 5u32;
pub const SOCKET_URING_OP_GETSOCKOPT: u32 = 2u32;
pub const SOCKET_URING_OP_SETSOCKOPT: u32 = 3u32;
pub const SOCKET_URING_OP_SIOCINQ: u32 = 0u32;
pub const SOCKET_URING_OP_SIOCOUTQ: u32 = 1u32;
pub const SOCKET_URING_OP_TX_TIMESTAMP: u32 = 4u32;
pub const ZCRX_CTRL_EXPORT: u32 = 1u32;
pub const ZCRX_CTRL_FLUSH_RQ: u32 = 0u32;
pub const ZCRX_FEATURE_RX_PAGE_SIZE: u32 = 1u32;
pub const ZCRX_REG_IMPORT: u32 = 1u32;
pub const __REQ_F_LAST_BIT: u32 = 41u32;
pub const __ZCRX_CTRL_LAST: u32 = 2u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct blk_plug {
    pub _reserved: [u64; 4],
}
impl Default for blk_plug {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct io_alloc_cache {
    pub entries: *mut *mut core::ffi::c_void,
    pub nr_cached: u32,
    pub max_cached: u32,
    pub elem_size: u32,
    pub init_clear: u32,
}
impl Default for io_alloc_cache {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct io_big_cqe {
    pub _reserved: [u64; 2],
}
impl Default for io_big_cqe {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct io_bpf_filters {
    pub refs: super::sync::refcount_t,
    pub lock: super::sync::spinlock_t,
    pub filters: *mut *mut core::ffi::c_void,
    pub callback_head: super::types::callback_head,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for io_bpf_filters {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_br_sel {
    pub buf_list: *mut core::ffi::c_void,
    pub io_br_sel__anon_0: io_br_sel__anon_0,
}
#[cfg(feature = "types")]
impl Default for io_br_sel {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union io_br_sel__anon_0 {
    pub addr: *mut core::ffi::c_void,
    pub val: super::types::ssize_t,
}
#[cfg(feature = "types")]
impl Default for io_br_sel__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct io_cmd_data {
    pub file: *mut super::fs::file,
    pub data: [super::types::__u8; 56],
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for io_cmd_data {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_cqe {
    pub user_data: super::types::__u64,
    pub res: super::types::__s32,
    pub io_cqe__anon_0: io_cqe__anon_0,
}
#[cfg(feature = "types")]
impl Default for io_cqe {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union io_cqe__anon_0 {
    pub flags: super::types::__u32,
    pub fd: i32,
}
#[cfg(feature = "types")]
impl Default for io_cqe__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_cqring_offsets {
    pub head: super::types::__u32,
    pub tail: super::types::__u32,
    pub ring_mask: super::types::__u32,
    pub ring_entries: super::types::__u32,
    pub overflow: super::types::__u32,
    pub cqes: super::types::__u32,
    pub flags: super::types::__u32,
    pub resv1: super::types::__u32,
    pub user_addr: super::types::__u64,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct io_file_table {
    pub data: io_rsrc_data,
    pub bitmap: *mut u64,
    pub alloc_hint: u32,
}
impl Default for io_file_table {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(64))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_hash_bucket {
    pub list: super::types::hlist_head,
    pub _padding: [u8; 56],
}
#[cfg(feature = "types")]
impl Default for io_hash_bucket {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_hash_table {
    pub hbs: *mut io_hash_bucket,
    pub hash_bits: u32,
}
#[cfg(feature = "types")]
impl Default for io_hash_table {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct io_kiocb {
    pub io_kiocb__anon_0: io_kiocb__anon_0,
    pub opcode: u8,
    pub iopoll_completed: u8,
    pub buf_index: u16,
    pub nr_tw: u32,
    pub flags: io_req_flags_t,
    pub cqe: io_cqe,
    pub ctx: *mut io_ring_ctx,
    pub tctx: *mut io_uring_task,
    pub io_kiocb__anon_1: io_kiocb__anon_1,
    pub io_kiocb__anon_2: io_kiocb__anon_2,
    pub file_node: *mut core::ffi::c_void,
    pub refs: super::types::atomic_t,
    pub cancel_seq_set: bool,
    pub io_kiocb__anon_3: io_kiocb__anon_3,
    pub io_kiocb__anon_4: io_kiocb__anon_4,
    pub apoll: *mut core::ffi::c_void,
    pub async_data: *mut core::ffi::c_void,
    pub poll_refs: super::types::atomic_t,
    pub link: *mut io_kiocb,
    pub creds: *mut super::cred::cred,
    pub work: io_wq_work,
    pub big_cqe: io_big_cqe,
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for io_kiocb {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub union io_kiocb__anon_0 {
    pub file: *mut super::fs::file,
    pub cmd: io_cmd_data,
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for io_kiocb__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union io_kiocb__anon_1 {
    pub kbuf: *mut core::ffi::c_void,
    pub buf_node: *mut core::ffi::c_void,
}
impl Default for io_kiocb__anon_1 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union io_kiocb__anon_2 {
    pub comp_list: io_wq_work_node,
    pub apoll_events: super::types::__poll_t,
}
#[cfg(feature = "types")]
impl Default for io_kiocb__anon_2 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub union io_kiocb__anon_3 {
    pub io_task_work: io_task_work,
    pub iopoll_start: u64,
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for io_kiocb__anon_3 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union io_kiocb__anon_4 {
    pub hash_node: super::types::hlist_node,
    pub iopoll_node: super::types::list_head,
    pub callback_head: super::types::callback_head,
}
#[cfg(feature = "types")]
impl Default for io_kiocb__anon_4 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(feature = "ds", feature = "mm_types", feature = "types"))]
#[derive(Clone, Copy)]
pub struct io_mapped_region {
    pub pages: *mut *mut super::mm_types::page,
    pub ptr: *mut core::ffi::c_void,
    pub nr_pages: u32,
    pub flags: u32,
}
#[cfg(all(feature = "ds", feature = "mm_types", feature = "types"))]
impl Default for io_mapped_region {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_overflow_cqe {
    pub list: super::types::list_head,
    pub cqe: io_uring_cqe,
}
pub type io_req_flags_t = u64;
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
pub type io_req_tw_func_t =
    Option<unsafe extern "system" fn(param0: io_tw_req, param1: io_tw_token_t)>;
#[repr(C, packed(8))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct io_restriction {
    pub register_op: [u64; 1],
    pub sqe_op: [u64; 2],
    pub bpf_filters: *mut io_bpf_filters,
    pub bpf_filters_cow: bool,
    pub sqe_flags_allowed: u8,
    pub sqe_flags_required: u8,
    pub op_registered: bool,
    pub reg_registered: bool,
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for io_restriction {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(64))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct io_ring_ctx {
    pub io_ring_ctx__anon_0: io_ring_ctx__anon_0,
    pub io_ring_ctx__anon_1: io_ring_ctx__anon_1,
    pub io_ring_ctx__anon_2: io_ring_ctx__anon_2,
    pub io_ring_ctx__anon_3: io_ring_ctx__anon_3,
    pub io_ring_ctx__anon_4: io_ring_ctx__anon_4,
    pub completion_lock: super::sync::spinlock_t,
    pub cq_overflow_list: super::types::list_head,
    pub waitid_list: super::types::hlist_head,
    pub futex_list: super::types::hlist_head,
    pub futex_cache: io_alloc_cache,
    pub sq_creds: *mut super::cred::cred,
    pub sq_data: *mut core::ffi::c_void,
    pub sqo_sq_wait: super::wait::wait_queue_head,
    pub sqd_list: super::types::list_head,
    pub file_alloc_start: u32,
    pub file_alloc_end: u32,
    pub poll_wq: super::wait::wait_queue_head,
    pub restrictions: io_restriction,
    pub zcrx_ctxs: super::ds::xarray,
    pub pers_next: u32,
    pub personalities: super::ds::xarray,
    pub hash_map: *mut core::ffi::c_void,
    pub user: *mut super::cred::user_struct,
    pub mm_account: *mut super::mm_types::mm_struct,
    pub tctx_list: super::types::list_head,
    pub tctx_lock: super::sync::mutex,
    pub fallback_llist: super::ds::llist_head,
    pub fallback_work: super::workqueue::delayed_work,
    pub exit_work: super::workqueue::work_struct,
    pub ref_comp: super::wait::completion,
    pub iowq_limits: [u32; 2],
    pub poll_wq_task_work: super::types::callback_head,
    pub defer_list: super::types::list_head,
    pub nr_drained: u32,
    pub nr_req_allocated: u32,
    pub napi_list: super::types::list_head,
    pub napi_lock: super::sync::spinlock_t,
    pub napi_busy_poll_dt: super::types::ktime_t,
    pub napi_prefer_busy_poll: bool,
    pub napi_track_mode: u8,
    pub napi_ht: [super::types::hlist_head; 16],
    pub mmap_lock: super::sync::mutex,
    pub sq_region: io_mapped_region,
    pub ring_region: io_mapped_region,
    pub param_region: io_mapped_region,
    pub _padding: [u8; 48],
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for io_ring_ctx {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(64))]
#[cfg(all(feature = "fs", feature = "types"))]
#[derive(Clone, Copy)]
pub struct io_ring_ctx__anon_0 {
    pub flags: u32,
    pub _bitfield_0: u16,
    pub submitter_task: *mut super::fs::task_struct,
    pub rings: *mut io_rings,
    pub bpf_filters: *mut *mut core::ffi::c_void,
    pub refs: percpu_ref,
    pub clockid: super::types::clockid_t,
    pub clock_offset: tk_offsets,
    pub notify_method: task_work_notify_mode,
    pub sq_thread_idle: u32,
}
#[cfg(all(feature = "fs", feature = "types"))]
impl Default for io_ring_ctx__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(64))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct io_ring_ctx__anon_1 {
    pub uring_lock: super::sync::mutex,
    pub sq_array: *mut u32,
    pub sq_sqes: *mut io_uring_sqe,
    pub cached_sq_head: u32,
    pub sq_entries: u32,
    pub cancel_seq: super::types::atomic_t,
    pub poll_multi_queue: bool,
    pub iopoll_list: super::types::list_head,
    pub file_table: io_file_table,
    pub buf_table: io_rsrc_data,
    pub node_cache: io_alloc_cache,
    pub imu_cache: io_alloc_cache,
    pub submit_state: io_submit_state,
    pub io_bl_xa: super::ds::xarray,
    pub cancel_table: io_hash_table,
    pub apoll_cache: io_alloc_cache,
    pub netmsg_cache: io_alloc_cache,
    pub rw_cache: io_alloc_cache,
    pub cmd_cache: io_alloc_cache,
    pub cancelable_uring_cmd: super::types::hlist_head,
    pub hybrid_poll_time: u64,
    pub _padding: [u8; 16],
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for io_ring_ctx__anon_1 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(64))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_ring_ctx__anon_2 {
    pub cqe_cached: *mut io_uring_cqe,
    pub cqe_sentinel: *mut io_uring_cqe,
    pub cached_cq_tail: u32,
    pub cq_entries: u32,
    pub io_ev_fd: *mut core::ffi::c_void,
    pub cq_wait_arg: *mut core::ffi::c_void,
    pub cq_wait_size: super::types::size_t,
    pub _padding: [u8; 16],
}
#[cfg(feature = "types")]
impl Default for io_ring_ctx__anon_2 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(64))]
#[cfg(all(feature = "ds", feature = "sync", feature = "types", feature = "wait"))]
#[derive(Clone, Copy)]
pub struct io_ring_ctx__anon_3 {
    pub rings_rcu: *mut io_rings,
    pub work_llist: super::ds::llist_head,
    pub retry_llist: super::ds::llist_head,
    pub check_cq: u64,
    pub cq_wait_nr: super::types::atomic_t,
    pub cq_timeouts: super::types::atomic_t,
    pub cq_wait: super::wait::wait_queue_head,
}
#[cfg(all(feature = "ds", feature = "sync", feature = "types", feature = "wait"))]
impl Default for io_ring_ctx__anon_3 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(64))]
#[cfg(all(feature = "sync", feature = "types"))]
#[derive(Clone, Copy)]
pub struct io_ring_ctx__anon_4 {
    pub timeout_lock: super::sync::raw_spinlock_t,
    pub timeout_list: super::types::list_head,
    pub ltimeout_list: super::types::list_head,
    pub cq_last_tm_flush: u32,
    pub _padding: [u8; 20],
}
#[cfg(all(feature = "sync", feature = "types"))]
impl Default for io_ring_ctx__anon_4 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(64))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_rings {
    pub sq: io_uring,
    pub cq: io_uring,
    pub sq_ring_mask: u32,
    pub cq_ring_mask: u32,
    pub sq_ring_entries: u32,
    pub cq_ring_entries: u32,
    pub sq_dropped: u32,
    pub sq_flags: super::types::atomic_t,
    pub cq_flags: u32,
    pub cq_overflow: u32,
    pub _pad_0: [u8; 16],
    pub cqes: *mut io_uring_cqe,
}
#[cfg(feature = "types")]
impl Default for io_rings {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct io_rsrc_data {
    pub nr: u32,
    pub nodes: *mut *mut core::ffi::c_void,
}
impl Default for io_rsrc_data {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_sqring_offsets {
    pub head: super::types::__u32,
    pub tail: super::types::__u32,
    pub ring_mask: super::types::__u32,
    pub ring_entries: super::types::__u32,
    pub flags: super::types::__u32,
    pub dropped: super::types::__u32,
    pub array: super::types::__u32,
    pub resv1: super::types::__u32,
    pub user_addr: super::types::__u64,
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct io_submit_link {
    pub head: *mut io_kiocb,
    pub last: *mut io_kiocb,
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for io_submit_link {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy, Default)]
pub struct io_submit_state {
    pub free_list: io_wq_work_node,
    pub compl_reqs: io_wq_work_list,
    pub link: io_submit_link,
    pub plug_started: bool,
    pub need_plug: bool,
    pub cq_flush: bool,
    pub submit_nr: u16,
    pub plug: blk_plug,
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy, Default)]
pub struct io_task_work {
    pub node: super::ds::llist_node,
    pub func: io_req_tw_func_t,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_timespec {
    pub tv_sec: super::types::__u64,
    pub tv_nsec: super::types::__u64,
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct io_tw_req {
    pub req: *mut io_kiocb,
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for io_tw_req {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(1))]
#[derive(Clone, Copy, Default)]
pub struct io_tw_state {
    pub cancel: bool,
}
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct io_tw_token_t {
    pub Value: io_tw_state,
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct io_uring {
    pub head: u32,
    pub tail: u32,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_attr_pi {
    pub flags: super::types::__u16,
    pub app_tag: super::types::__u16,
    pub len: super::types::__u32,
    pub addr: super::types::__u64,
    pub seed: super::types::__u64,
    pub rsvd: super::types::__u64,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_buf {
    pub addr: super::types::__u64,
    pub len: super::types::__u32,
    pub bid: super::types::__u16,
    pub resv: super::types::__u16,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_buf_reg {
    pub ring_addr: super::types::__u64,
    pub ring_entries: super::types::__u32,
    pub bgid: super::types::__u16,
    pub flags: super::types::__u16,
    pub resv: [super::types::__u64; 3],
}
#[cfg(feature = "types")]
impl Default for io_uring_buf_reg {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_buf_ring {
    pub io_uring_buf_ring__anon_0: io_uring_buf_ring__anon_0,
}
#[cfg(feature = "types")]
impl Default for io_uring_buf_ring {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union io_uring_buf_ring__anon_0 {
    pub io_uring_buf_ring__anon_0__anon_0: io_uring_buf_ring__anon_0__anon_0,
    pub io_uring_buf_ring__anon_0__anon_1: io_uring_buf_ring__anon_0__anon_1,
}
#[cfg(feature = "types")]
impl Default for io_uring_buf_ring__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_buf_ring__anon_0__anon_0 {
    pub resv1: super::types::__u64,
    pub resv2: super::types::__u32,
    pub resv3: super::types::__u16,
    pub tail: super::types::__u16,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_buf_ring__anon_0__anon_1 {
    pub __empty_bufs: io_uring_buf_ring__anon_0__anon_1___empty_bufs,
    pub bufs: *mut io_uring_buf,
}
#[cfg(feature = "types")]
impl Default for io_uring_buf_ring__anon_0__anon_1 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(1))]
#[derive(Clone, Copy, Default)]
pub struct io_uring_buf_ring__anon_0__anon_1___empty_bufs(pub u8);
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_buf_status {
    pub buf_group: super::types::__u32,
    pub head: super::types::__u32,
    pub resv: [super::types::__u32; 8],
}
#[cfg(feature = "types")]
impl Default for io_uring_buf_status {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_clock_register {
    pub clockid: super::types::__u32,
    pub __resv: [super::types::__u32; 3],
}
#[cfg(feature = "types")]
impl Default for io_uring_clock_register {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_clone_buffers {
    pub src_fd: super::types::__u32,
    pub flags: super::types::__u32,
    pub src_off: super::types::__u32,
    pub dst_off: super::types::__u32,
    pub nr: super::types::__u32,
    pub pad: [super::types::__u32; 3],
}
#[cfg(feature = "types")]
impl Default for io_uring_clone_buffers {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct io_uring_cmd {
    pub file: *mut super::fs::file,
    pub sqe: *mut io_uring_sqe,
    pub cmd_op: u32,
    pub flags: u32,
    pub pdu: [u8; 32],
    pub unused: [u8; 8],
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for io_uring_cmd {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type io_uring_cmd_flags = i32;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_cqe {
    pub user_data: super::types::__u64,
    pub res: super::types::__s32,
    pub flags: super::types::__u32,
    pub big_cqe: *mut super::types::__u64,
}
#[cfg(feature = "types")]
impl Default for io_uring_cqe {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_file_index_range {
    pub off: super::types::__u32,
    pub len: super::types::__u32,
    pub resv: super::types::__u64,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_files_update {
    pub offset: super::types::__u32,
    pub resv: super::types::__u32,
    pub fds: super::types::__u64,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_getevents_arg {
    pub sigmask: super::types::__u64,
    pub sigmask_sz: super::types::__u32,
    pub min_wait_usec: super::types::__u32,
    pub ts: super::types::__u64,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_mem_region_reg {
    pub region_uptr: super::types::__u64,
    pub flags: super::types::__u64,
    pub __resv: [super::types::__u64; 2],
}
#[cfg(feature = "types")]
impl Default for io_uring_mem_region_reg {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type io_uring_msg_ring_flags = u32;
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_napi {
    pub busy_poll_to: super::types::__u32,
    pub prefer_busy_poll: super::types::__u8,
    pub opcode: super::types::__u8,
    pub pad: [super::types::__u8; 2],
    pub op_param: super::types::__u32,
    pub resv: super::types::__u32,
}
#[cfg(feature = "types")]
impl Default for io_uring_napi {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type io_uring_napi_op = u32;
pub type io_uring_napi_tracking_strategy = u32;
pub type io_uring_op = u32;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_params {
    pub sq_entries: super::types::__u32,
    pub cq_entries: super::types::__u32,
    pub flags: super::types::__u32,
    pub sq_thread_cpu: super::types::__u32,
    pub sq_thread_idle: super::types::__u32,
    pub features: super::types::__u32,
    pub wq_fd: super::types::__u32,
    pub resv: [super::types::__u32; 3],
    pub sq_off: io_sqring_offsets,
    pub cq_off: io_cqring_offsets,
}
#[cfg(feature = "types")]
impl Default for io_uring_params {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_probe {
    pub last_op: super::types::__u8,
    pub ops_len: super::types::__u8,
    pub resv: super::types::__u16,
    pub resv2: [super::types::__u32; 3],
    pub ops: *mut io_uring_probe_op,
}
#[cfg(feature = "types")]
impl Default for io_uring_probe {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_probe_op {
    pub op: super::types::__u8,
    pub resv: super::types::__u8,
    pub flags: super::types::__u16,
    pub resv2: super::types::__u32,
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_recvmsg_out {
    pub namelen: super::types::__u32,
    pub controllen: super::types::__u32,
    pub payloadlen: super::types::__u32,
    pub flags: super::types::__u32,
}
#[repr(C, packed(8))]
#[cfg(all(feature = "net", feature = "types"))]
#[derive(Clone, Copy)]
pub struct io_uring_reg_wait {
    pub ts: super::net::__kernel_timespec,
    pub min_wait_usec: super::types::__u32,
    pub flags: super::types::__u32,
    pub sigmask: super::types::__u64,
    pub sigmask_sz: super::types::__u32,
    pub pad: [super::types::__u32; 3],
    pub pad2: [super::types::__u64; 2],
}
#[cfg(all(feature = "net", feature = "types"))]
impl Default for io_uring_reg_wait {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_region_desc {
    pub user_addr: super::types::__u64,
    pub size: super::types::__u64,
    pub flags: super::types::__u32,
    pub id: super::types::__u32,
    pub mmap_offset: super::types::__u64,
    pub __resv: [super::types::__u64; 4],
}
#[cfg(feature = "types")]
impl Default for io_uring_region_desc {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type io_uring_register_op = u32;
pub type io_uring_register_pbuf_ring_flags = u32;
pub type io_uring_register_restriction_op = u32;
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_restriction {
    pub opcode: super::types::__u16,
    pub io_uring_restriction__anon_0: io_uring_restriction__anon_0,
    pub resv: super::types::__u8,
    pub resv2: [super::types::__u32; 3],
}
#[cfg(feature = "types")]
impl Default for io_uring_restriction {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(1))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union io_uring_restriction__anon_0 {
    pub register_op: super::types::__u8,
    pub sqe_op: super::types::__u8,
    pub sqe_flags: super::types::__u8,
}
#[cfg(feature = "types")]
impl Default for io_uring_restriction__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_rsrc_register {
    pub nr: super::types::__u32,
    pub flags: super::types::__u32,
    pub resv2: super::types::__u64,
    pub data: super::types::__u64,
    pub tags: super::types::__u64,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_rsrc_update {
    pub offset: super::types::__u32,
    pub resv: super::types::__u32,
    pub data: super::types::__u64,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_rsrc_update2 {
    pub offset: super::types::__u32,
    pub resv: super::types::__u32,
    pub data: super::types::__u64,
    pub tags: super::types::__u64,
    pub nr: super::types::__u32,
    pub resv2: super::types::__u32,
}
pub type io_uring_socket_op = u32;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_sqe {
    pub opcode: super::types::__u8,
    pub flags: super::types::__u8,
    pub ioprio: super::types::__u16,
    pub fd: super::types::__s32,
    pub io_uring_sqe__anon_0: io_uring_sqe__anon_0,
    pub io_uring_sqe__anon_1: io_uring_sqe__anon_1,
    pub len: super::types::__u32,
    pub io_uring_sqe__anon_2: io_uring_sqe__anon_2,
    pub user_data: super::types::__u64,
    pub io_uring_sqe__anon_3: io_uring_sqe__anon_3,
    pub personality: super::types::__u16,
    pub io_uring_sqe__anon_4: io_uring_sqe__anon_4,
    pub io_uring_sqe__anon_5: io_uring_sqe__anon_5,
}
#[cfg(feature = "types")]
impl Default for io_uring_sqe {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union io_uring_sqe__anon_0 {
    pub off: super::types::__u64,
    pub addr2: super::types::__u64,
    pub io_uring_sqe__anon_0__anon_0: io_uring_sqe__anon_0__anon_0,
}
#[cfg(feature = "types")]
impl Default for io_uring_sqe__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_sqe__anon_0__anon_0 {
    pub cmd_op: super::types::__u32,
    pub __pad1: super::types::__u32,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union io_uring_sqe__anon_1 {
    pub addr: super::types::__u64,
    pub splice_off_in: super::types::__u64,
    pub io_uring_sqe__anon_1__anon_0: io_uring_sqe__anon_1__anon_0,
}
#[cfg(feature = "types")]
impl Default for io_uring_sqe__anon_1 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_sqe__anon_1__anon_0 {
    pub level: super::types::__u32,
    pub optname: super::types::__u32,
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union io_uring_sqe__anon_2 {
    pub rw_flags: super::types::__u32,
    pub fsync_flags: super::types::__u32,
    pub poll_events: super::types::__u16,
    pub poll32_events: super::types::__u32,
    pub sync_range_flags: super::types::__u32,
    pub msg_flags: super::types::__u32,
    pub timeout_flags: super::types::__u32,
    pub accept_flags: super::types::__u32,
    pub cancel_flags: super::types::__u32,
    pub open_flags: super::types::__u32,
    pub statx_flags: super::types::__u32,
    pub fadvise_advice: super::types::__u32,
    pub splice_flags: super::types::__u32,
    pub rename_flags: super::types::__u32,
    pub unlink_flags: super::types::__u32,
    pub hardlink_flags: super::types::__u32,
    pub xattr_flags: super::types::__u32,
    pub msg_ring_flags: super::types::__u32,
    pub uring_cmd_flags: super::types::__u32,
    pub waitid_flags: super::types::__u32,
    pub futex_flags: super::types::__u32,
    pub install_fd_flags: super::types::__u32,
    pub nop_flags: super::types::__u32,
    pub pipe_flags: super::types::__u32,
}
#[cfg(feature = "types")]
impl Default for io_uring_sqe__anon_2 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(1))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union io_uring_sqe__anon_3 {
    pub buf_index: super::types::__u16,
    pub buf_group: super::types::__u16,
}
#[cfg(feature = "types")]
impl Default for io_uring_sqe__anon_3 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union io_uring_sqe__anon_4 {
    pub splice_fd_in: super::types::__s32,
    pub file_index: super::types::__u32,
    pub zcrx_ifq_idx: super::types::__u32,
    pub optlen: super::types::__u32,
    pub io_uring_sqe__anon_4__anon_0: io_uring_sqe__anon_4__anon_0,
    pub io_uring_sqe__anon_4__anon_1: io_uring_sqe__anon_4__anon_1,
}
#[cfg(feature = "types")]
impl Default for io_uring_sqe__anon_4 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(2))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_sqe__anon_4__anon_0 {
    pub addr_len: super::types::__u16,
    pub __pad3: [super::types::__u16; 1],
}
#[cfg(feature = "types")]
impl Default for io_uring_sqe__anon_4__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(1))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_sqe__anon_4__anon_1 {
    pub write_stream: super::types::__u8,
    pub __pad4: [super::types::__u8; 3],
}
#[cfg(feature = "types")]
impl Default for io_uring_sqe__anon_4__anon_1 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union io_uring_sqe__anon_5 {
    pub io_uring_sqe__anon_5__anon_0: io_uring_sqe__anon_5__anon_0,
    pub io_uring_sqe__anon_5__anon_1: io_uring_sqe__anon_5__anon_1,
    pub optval: super::types::__u64,
    pub cmd: [super::types::__u8; 0],
}
#[cfg(feature = "types")]
impl Default for io_uring_sqe__anon_5 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_sqe__anon_5__anon_0 {
    pub addr3: super::types::__u64,
    pub __pad2: [super::types::__u64; 1],
}
#[cfg(feature = "types")]
impl Default for io_uring_sqe__anon_5__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_sqe__anon_5__anon_1 {
    pub attr_ptr: super::types::__u64,
    pub attr_type_mask: super::types::__u64,
}
pub type io_uring_sqe_flags_bit = u32;
#[repr(C, packed(8))]
#[cfg(all(feature = "net", feature = "types"))]
#[derive(Clone, Copy)]
pub struct io_uring_sync_cancel_reg {
    pub addr: super::types::__u64,
    pub fd: super::types::__s32,
    pub flags: super::types::__u32,
    pub timeout: super::net::__kernel_timespec,
    pub opcode: super::types::__u8,
    pub pad: [super::types::__u8; 7],
    pub pad2: [super::types::__u64; 3],
}
#[cfg(all(feature = "net", feature = "types"))]
impl Default for io_uring_sync_cancel_reg {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(64))]
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
#[derive(Clone, Copy)]
pub struct io_uring_task {
    pub cached_refs: i32,
    pub last: *mut io_ring_ctx,
    pub task: *mut super::fs::task_struct,
    pub io_wq: *mut core::ffi::c_void,
    pub registered_rings: [*mut super::fs::file; 16],
    pub xa: super::ds::xarray,
    pub wait: super::wait::wait_queue_head,
    pub in_cancel: super::types::atomic_t,
    pub inflight_tracked: super::types::atomic_t,
    pub inflight: super::fs::percpu_counter,
    pub io_uring_task__anon_0: io_uring_task__anon_0,
    pub _padding: [u8; 8],
}
#[cfg(all(
    feature = "cred",
    feature = "dcache",
    feature = "ds",
    feature = "fs",
    feature = "mm_types",
    feature = "sync",
    feature = "types",
    feature = "wait",
    feature = "workqueue"
))]
impl Default for io_uring_task {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(64))]
#[cfg(all(feature = "ds", feature = "types"))]
#[derive(Clone, Copy)]
pub struct io_uring_task__anon_0 {
    pub task_list: super::ds::llist_head,
    pub task_work: super::types::callback_head,
    pub _padding: [u8; 40],
}
#[cfg(all(feature = "ds", feature = "types"))]
impl Default for io_uring_task__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_task_restriction {
    pub flags: super::types::__u16,
    pub nr_res: super::types::__u16,
    pub resv: [super::types::__u32; 3],
    pub io_uring_task_restriction__anon_0: io_uring_task_restriction__anon_0,
}
#[cfg(feature = "types")]
impl Default for io_uring_task_restriction {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_task_restriction__anon_0 {
    pub __empty_restrictions: io_uring_task_restriction__anon_0___empty_restrictions,
    pub restrictions: *mut io_uring_restriction,
}
#[cfg(feature = "types")]
impl Default for io_uring_task_restriction__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(1))]
#[derive(Clone, Copy, Default)]
pub struct io_uring_task_restriction__anon_0___empty_restrictions(pub u8);
pub type io_uring_zcrx_area_flags = u32;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_zcrx_area_reg {
    pub addr: super::types::__u64,
    pub len: super::types::__u64,
    pub rq_area_token: super::types::__u64,
    pub flags: super::types::__u32,
    pub dmabuf_fd: super::types::__u32,
    pub __resv2: [super::types::__u64; 2],
}
#[cfg(feature = "types")]
impl Default for io_uring_zcrx_area_reg {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_zcrx_cqe {
    pub off: super::types::__u64,
    pub __pad: super::types::__u64,
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_zcrx_ifq_reg {
    pub if_idx: super::types::__u32,
    pub if_rxq: super::types::__u32,
    pub rq_entries: super::types::__u32,
    pub flags: super::types::__u32,
    pub area_ptr: super::types::__u64,
    pub region_ptr: super::types::__u64,
    pub offsets: io_uring_zcrx_offsets,
    pub zcrx_id: super::types::__u32,
    pub rx_buf_len: super::types::__u32,
    pub __resv: [super::types::__u64; 3],
}
#[cfg(feature = "types")]
impl Default for io_uring_zcrx_ifq_reg {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct io_uring_zcrx_offsets {
    pub head: super::types::__u32,
    pub tail: super::types::__u32,
    pub rqes: super::types::__u32,
    pub __resv2: super::types::__u32,
    pub __resv: [super::types::__u64; 2],
}
#[cfg(feature = "types")]
impl Default for io_uring_zcrx_offsets {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_uring_zcrx_rqe {
    pub off: super::types::__u64,
    pub len: super::types::__u32,
    pub __pad: super::types::__u32,
}
pub type io_wq_type = u32;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy, Default)]
pub struct io_wq_work {
    pub list: io_wq_work_node,
    pub flags: super::types::atomic_t,
    pub cancel_seq: i32,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct io_wq_work_list {
    pub first: *mut io_wq_work_node,
    pub last: *mut io_wq_work_node,
}
impl Default for io_wq_work_list {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct io_wq_work_node {
    pub next: *mut io_wq_work_node,
}
impl Default for io_wq_work_node {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "ds",
    feature = "iomap",
    feature = "mm_types",
    feature = "net",
    feature = "types"
))]
#[derive(Clone, Copy)]
pub struct iou_vec {
    pub iou_vec__anon_0: iou_vec__anon_0,
    pub nr: u32,
    pub _padding: [u8; 4],
}
#[cfg(all(
    feature = "ds",
    feature = "iomap",
    feature = "mm_types",
    feature = "net",
    feature = "types"
))]
impl Default for iou_vec {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(all(
    feature = "ds",
    feature = "iomap",
    feature = "mm_types",
    feature = "net",
    feature = "types"
))]
#[derive(Clone, Copy)]
pub union iou_vec__anon_0 {
    pub iovec: *mut super::net::iovec,
    pub bvec: *mut super::iomap::bio_vec,
}
#[cfg(all(
    feature = "ds",
    feature = "iomap",
    feature = "mm_types",
    feature = "net",
    feature = "types"
))]
impl Default for iou_vec__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct percpu_ref {
    pub _reserved: [u64; 4],
}
impl Default for percpu_ref {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct request {
    pub _reserved: [u64; 4],
}
impl Default for request {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type task_work_notify_mode = i32;
pub type tk_offsets = i32;
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct zcrx_ctrl {
    pub zcrx_id: super::types::__u32,
    pub op: super::types::__u32,
    pub __resv: [super::types::__u64; 2],
    pub zcrx_ctrl__anon_0: zcrx_ctrl__anon_0,
}
#[cfg(feature = "types")]
impl Default for zcrx_ctrl {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub union zcrx_ctrl__anon_0 {
    pub zc_export: zcrx_ctrl_export,
    pub zc_flush: zcrx_ctrl_flush_rq,
}
#[cfg(feature = "types")]
impl Default for zcrx_ctrl__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct zcrx_ctrl_export {
    pub zcrx_fd: super::types::__u32,
    pub __resv1: [super::types::__u32; 11],
}
#[cfg(feature = "types")]
impl Default for zcrx_ctrl_export {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "types")]
#[derive(Clone, Copy)]
pub struct zcrx_ctrl_flush_rq {
    pub __resv: [super::types::__u64; 6],
}
#[cfg(feature = "types")]
impl Default for zcrx_ctrl_flush_rq {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type zcrx_ctrl_op = u32;
pub type zcrx_features = u32;
pub type zcrx_reg_flags = u32;
