name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      CMAKE_C_COMPILER_LAUNCHER: "sccache"
      CMAKE_CXX_COMPILER_LAUNCHER: "sccache"
    steps:
    - uses: actions/checkout@v5

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9
      with:
        version: "v0.10.0"

    - name: Read rust version from rust-toolchain.toml
      id: rust-version
      run: echo "version=$(grep '^channel' rust-toolchain.toml | sed 's/.*"\(.*\)"/\1/')" >> "$GITHUB_OUTPUT"

    - name: Install rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ steps.rust-version.outputs.version }}
        components: rustfmt, clippy, rust-src
        targets: x86_64-unknown-linux-musl

    - name: Set rust version
      run: rustup override set ${{ steps.rust-version.outputs.version }}

    - uses: taiki-e/install-action@v2
      with:
        tool: bindgen-cli

    - name: Install LLVM toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y clang llvm lld libelf-dev libssl-dev libclang-dev cpio busybox-static qemu-system-x86 musl-tools

    - name: Clone linux to /linux dir with commit
      run: |
        git clone --branch ${{ env.TAG }} --depth 1 https://github.com/torvalds/linux.git ./linux
      env:
        TAG: v7.0

    - name: Configure cmake
      run: cmake -S . -B build -DENABLE_KVM=OFF

    - name: configure linux
      run: cmake --build build --target configure_linux --verbose

    - name: Build linux
      run: cmake --build build --target make_linux --parallel 4 --verbose

    - name: Check build artifacts
      run: |
        cargo --version
        ls -la linux_bin/scripts/

    - name: Run cargo check
      run: cargo check

    - name: Run cargo fmt
      run: cargo fmt --all -- --check
    
    - name: Run cargo clippy
      run: cargo clippy --all-targets -- -D warnings

    - name: Build all kmods
      run: cmake --build build --target all

    - name: Run QEMU tests
      run: ctest --test-dir build --verbose